/**
 * Catalogue de lois absurdes pour la question Quiz CEO `absurd-law`.
 *
 *   - `text`  : énoncé de la loi (vraie ou inventée)
 *   - `value` : true si la loi existe vraiment en 2026, false sinon
 *
 * 300 entrées : 100 EASY (verdict devinable) + 100 MEDIUM (plausible) +
 * 100 HARD (contre-intuitif). Mélange France pittoresque + lois étrangères
 * documentées (Singapour, UK, Suisse, Italie, USA, Tonga, Australie…).
 *
 * Source de vérité runtime = la DB. Ce fichier sert au seed initial.
 * Les corrections en prod se font par UPDATE direct (cf. expressions/translations).
 */

export interface AbsurdLawEntry {
  text: string;
  value: boolean;
}

export const ABSURD_LAWS_EASY: AbsurdLawEntry[] = [
  // Vraies (37 — j'ai retiré le #38 douteux)
  { text: 'À Châteauneuf-du-Pape, le survol des soucoupes volantes est interdit.', value: true },
  { text: 'À Singapour, importer du chewing-gum est puni d\'amende.', value: true },
  { text: 'En Suisse, posséder un seul cochon d\'Inde est illégal.', value: true },
  { text: 'En Allemagne, tomber en panne d\'essence sur l\'autoroute est passible d\'amende.', value: true },
  { text: 'À Eraclea (Italie), les châteaux de sable sont interdits sur la plage.', value: true },
  { text: 'À Capri (Italie), les chaussures bruyantes (tongs, sabots) sont interdites en centre-ville.', value: true },
  { text: 'À Venise, il est interdit de nager dans les canaux.', value: true },
  { text: 'À Venise, nourrir les pigeons place Saint-Marc est interdit.', value: true },
  { text: 'À Rome, s\'asseoir, manger ou boire sur les marches de la Place d\'Espagne est interdit.', value: true },
  { text: 'En Espagne, conduire en tongs ou en sandales ouvertes est passible d\'amende.', value: true },
  { text: 'En Grèce, porter des talons hauts sur les sites antiques est interdit.', value: true },
  { text: 'Au Royaume-Uni, il est illégal d\'être ivre dans un pub.', value: true },
  { text: 'À Tonga, jouer au foot le dimanche est passible d\'amende ou de prison.', value: true },
  { text: 'Au Texas, prendre plus de trois gorgées de bière debout est interdit.', value: true },
  { text: 'En Floride, il est interdit de vendre de l\'alcool pendant un ouragan.', value: true },
  { text: 'En Iowa, vendre de la margarine en la faisant passer pour du beurre est un délit.', value: true },
  { text: 'En Alabama, jouer aux dominos le dimanche est interdit.', value: true },
  { text: 'En Alabama, transporter un cône de glace dans sa poche arrière est interdit.', value: true },
  { text: 'À Granville (Manche), les éléphants ont l\'interdiction de se baigner dans la mer.', value: true },
  { text: 'En Thaïlande, marcher sur un billet de banque est un crime de lèse-majesté.', value: true },
  { text: 'À Singapour, marcher nu chez soi avec les rideaux ouverts est un délit.', value: true },
  { text: 'En Australie occidentale, posséder plus de 50 kg de pommes de terre est un délit.', value: true },
  { text: 'À Cugnaux (Haute-Garonne), il est interdit de mourir sans avoir de tombe.', value: false },
  { text: 'Au Royaume-Uni, mourir dans l\'enceinte du Parlement est officiellement illégal.', value: true },
  { text: 'En Australie (État de Victoria), ne pas verrouiller sa voiture est passible d\'amende.', value: true },
  { text: 'En Italie, nourrir les pigeons sur les places principales est généralement interdit.', value: true },
  { text: 'Au Portugal, il est interdit d\'uriner dans l\'océan.', value: true },
  { text: 'À Singapour, jeter un mégot par terre est passible d\'amende.', value: true },
  { text: 'Au Danemark, il est obligatoire de vérifier sous sa voiture avant de démarrer.', value: true },
  { text: 'En Suède, publier la photo d\'un billet de couronne suédoise viole le droit d\'auteur.', value: true },
  { text: 'Au Canada, on ne peut pas payer en trop grand nombre de pièces de monnaie en une seule transaction.', value: true },
  { text: 'À Ychoux (Landes), un arrêté municipal interdit aux habitants de tomber malade.', value: true },
  { text: 'En Floride, le « lancer de nain » dans un bar est interdit.', value: true },
  { text: 'À Singapour, cracher dans la rue est passible d\'amende.', value: true },
  { text: 'En Idaho, le cannibalisme est interdit, sauf en cas de survie sous menace de mort.', value: true },
  { text: 'Au Japon, importer des médicaments contenant de la pseudoéphédrine (Vicks, Sudafed) est interdit.', value: true },
  { text: 'À Cerdon (Ain), un maire a pris un arrêté interdisant à la neige de tomber.', value: true },

  // Fausses (63)
  { text: 'À Marseille, il est interdit de manger un sandwich sans avoir d\'abord salué la mer.', value: false },
  { text: 'En Belgique, il est obligatoire de boire une bière par jour pour les salariés à temps plein.', value: false },
  { text: 'À Lille, on doit prêter serment d\'honnêteté avant de porter une moustache.', value: false },
  { text: 'À Avignon, bâiller pendant un office religieux est passible d\'amende.', value: false },
  { text: 'À Toulouse, on doit saluer en occitan tout étranger venu de plus de 50 km.', value: false },
  { text: 'En Bretagne, chanter en breton est obligatoire avant la pêche à la sardine.', value: false },
  { text: 'À Bordeaux, les sommeliers doivent porter un foulard rouge le 14 juillet.', value: false },
  { text: 'À Lyon, on doit obligatoirement saluer son boulanger en français.', value: false },
  { text: 'À Nice, il est interdit de pleurer en public.', value: false },
  { text: 'À Strasbourg, on doit chanter en alsacien avant chaque repas en restaurant.', value: false },
  { text: 'À Reims, le champagne est obligatoire au petit-déjeuner du 1er janvier.', value: false },
  { text: 'À Cannes, il faut applaudir au coucher du soleil sur la Croisette.', value: false },
  { text: 'À Quimper, le breton est obligatoire dans les commerces de plus de 5 employés.', value: false },
  { text: 'En Norvège, refuser un duel oblige à fournir 4 cerfs en compensation.', value: false },
  { text: 'En Russie, dire une phrase de plus de 4 mots en anglais est interdit.', value: false },
  { text: 'En Belgique, vendre du pain rassis sans étiquette « pain d\'hier » est interdit.', value: false },
  { text: 'À Bourges, les chats errants doivent être déclarés à la mairie.', value: false },
  { text: 'À Annecy, la baignade dans le lac est obligatoire en été pour les habitants.', value: false },
  { text: 'En Italie du Sud, il est obligatoire de chanter en italien pendant la cuisson des pâtes.', value: false },
  { text: 'À Briançon, skier sans bonnet entre décembre et mars est interdit.', value: false },
  { text: 'À Évian, boire de l\'eau d\'une autre marque en public est interdit.', value: false },
  { text: 'À Bayonne, le jambon doit être tranché par un employé certifié.', value: false },
  { text: 'À Cassis, chanter sur le port après 21h est interdit aux touristes.', value: false },
  { text: 'À Fontainebleau, pique-niquer sans permis municipal est interdit.', value: false },
  { text: 'À La Rochelle, manger des huîtres en pull blanc est interdit.', value: false },
  { text: 'À Roubaix, on doit chanter en chœur le 14 juillet.', value: false },
  { text: 'À Limoges, importer de la porcelaine sans accord municipal est interdit.', value: false },
  { text: 'À Rennes, manger des galettes sans cidre en restaurant est interdit.', value: false },
  { text: 'À Caen, chanter en chœur le 6 juin chaque année est obligatoire.', value: false },
  { text: 'À Cherbourg, les Anglais ne peuvent pas pêcher la morue le dimanche.', value: false },
  { text: 'À Concarneau, les marins doivent siffler en partant en mer.', value: false },
  { text: 'À Lourdes, prendre des photos pendant les processions est interdit.', value: false },
  { text: 'À Saint-Tropez, porter des sandales noires est interdit.', value: false },
  { text: 'À Versailles, faire la révérence au gardien du château est obligatoire.', value: false },
  { text: 'En Suède, peindre sa maison en rose nécessite l\'accord de 3 voisins.', value: false },
  { text: 'Au Japon, il est obligatoire de pleurer aux enterrements sous peine d\'amende.', value: false },
  { text: 'À Athènes, les vestes en cuir sont interdites en juillet et août.', value: false },
  { text: 'En Finlande, jouer au curling sans gants noirs est interdit.', value: false },
  { text: 'À Berlin, chuchoter dans le métro après 23h est passible d\'amende.', value: false },
  { text: 'À Madrid, manger une paella debout est interdit.', value: false },
  { text: 'Au Mexique, jongler en public sans assurance est interdit.', value: false },
  { text: 'En Inde, prendre l\'ascenseur avec une vache porte-bonheur est obligatoire.', value: false },
  { text: 'À Tokyo, déballer un onigiri dans le métro est interdit.', value: false },
  { text: 'À Buenos Aires, danser le tango sans permis est passible d\'amende.', value: false },
  { text: 'À Vienne, parler fort dans une pâtisserie après 17h est interdit.', value: false },
  { text: 'En Corée du Sud, les couples mariés doivent assister à 2 mariages par an.', value: false },
  { text: 'À Stockholm, marcher en sens inverse de la foule est passible d\'avertissement.', value: false },
  { text: 'En Norvège, avoir un sapin de Noël entre le 1er décembre et le 6 janvier est obligatoire.', value: false },
  { text: 'À Lisbonne, le port du chapeau est interdit dans les tramways.', value: false },
  { text: 'À Dubaï, les touristes doivent saluer le ciel chaque matin.', value: false },
  { text: 'À Athènes, courir avec un drapeau grec est interdit hors compétition.', value: false },
  { text: 'En Belgique, la pluie est officiellement « patrimoine national ».', value: false },
  { text: 'À Munich, boire de la bière sans bretzel est interdit en Oktoberfest.', value: false },
  { text: 'À Édimbourg, jouer de la cornemuse après 22h est passible d\'amende.', value: false },
  { text: 'À Helsinki, traverser un parc avec une caisse de bière nécessite une autorisation.', value: false },
  { text: 'À New Delhi, traverser la route avec une vache devant soi est obligatoire.', value: false },
  { text: 'À Casablanca, prendre l\'ascenseur sans saluer est mal vu par décret.', value: false },
  { text: 'À Istanbul, manger des loukoums en marchant est interdit le vendredi.', value: false },
  { text: 'À Lima, danser sans partenaire dans la rue est interdit.', value: false },
  { text: 'À Quito, regarder un volcan plus de 5 minutes nécessite un guide.', value: false },
  { text: 'À Sofia, parler russe en magasin est mal vu par décret de 1991.', value: false },
  { text: 'À Oulan-Bator, boire du thé tiède est interdit aux touristes.', value: false },
  { text: 'En Norvège, posséder une carte routière où le Svalbard n\'est pas représenté est sanctionné.', value: false },
];

export const ABSURD_LAWS_MEDIUM: AbsurdLawEntry[] = [
  // Vraies (35)
  { text: 'Au Royaume-Uni, manipuler du saumon « dans des circonstances suspectes » est un délit.', value: true },
  { text: 'À Singapour, marcher nu chez soi visible depuis l\'extérieur est un délit.', value: true },
  { text: 'À Capri, les sandales claquantes peuvent valoir une amende sur place.', value: true },
  { text: 'En Allemagne, l\'oreiller est juridiquement classé comme « arme passive » en bagarre.', value: true },
  { text: 'En Espagne, conduire pieds nus est passible d\'une amende.', value: true },
  { text: 'À Tonga, danser le dimanche est interdit.', value: true },
  { text: 'En Iran, insulter le Prophète est passible de la peine capitale.', value: true },
  { text: 'En Russie, blesser les sentiments religieux des croyants est un délit pénal.', value: true },
  { text: 'En Arabie saoudite, aux Philippines et à Oman, porter du camouflage en civil est interdit.', value: true },
  { text: 'À Eraclea (Italie), un château de sable doit être détruit avant le passage de la patrouille.', value: true },
  { text: 'À Singapour, le vandalisme peut être puni de coups de bâton (caning).', value: true },
  { text: 'À Tonga, pêcher le dimanche est puni d\'amende ou de 6 mois de prison.', value: true },
  { text: 'À Reykjavík (Islande), posséder un chien nécessite un permis municipal.', value: true },
  { text: 'Au Texas, posséder plus de 6 sex-toys constitue un délit.', value: true },
  { text: 'À Sarpourenx (Pyrénées-Atlantiques), il est interdit de mourir si l\'on n\'a pas de tombe.', value: false },
  { text: 'En Suisse, dans certaines copropriétés, uriner debout après 22h est interdit.', value: true },
  { text: 'Au Laos, embrasser en public peut valoir une amende.', value: true },
  { text: 'En Thaïlande, conduire torse nu est passible d\'amende.', value: true },
  { text: 'À Tonga, faire du jet-ski le dimanche est interdit, sauf urgence.', value: true },
  { text: 'En Suède, klaxonner sans raison est interdit.', value: true },
  { text: 'En Birmanie, porter un tatouage de Bouddha sur le bas du corps peut valoir l\'expulsion.', value: true },
  { text: 'Aux Émirats arabes unis, jurer en messagerie privée peut valoir une amende et l\'expulsion.', value: true },
  { text: 'À Athènes, montrer ses fesses sur un site historique peut conduire à l\'arrestation.', value: true },
  { text: 'À Singapour, brancher un appareil sur la prise d\'autrui sans permission est un vol d\'électricité.', value: true },
  { text: 'À Tonga, écouter de la musique forte le dimanche est punissable.', value: true },
  { text: 'En Suisse, tondre sa pelouse le dimanche est interdit dans la plupart des cantons.', value: true },
  { text: 'À Châteauneuf-du-Pape, en cas d\'atterrissage de soucoupe, le garde champêtre doit confisquer l\'engin.', value: true },
  { text: 'En Inde, conduire en sandales sans semelle complète est interdit dans certaines villes.', value: true },
  { text: 'À Pékin, distribuer des tracts politiques sans permis est passible d\'arrestation.', value: true },
  { text: 'À Téhéran, écouter de la musique occidentale forte en voiture peut entraîner une amende.', value: true },
  { text: 'Au Vietnam, traverser la rue en regardant son téléphone est passible d\'amende dans les grandes villes.', value: true },
  { text: 'À Singapour, importer un durian dans le métro (MRT) est interdit.', value: true },
  { text: 'En Floride, organiser un concours de lancer de nain dans un bar est interdit.', value: true },
  { text: 'À Saint-Marin, posséder un fusil mitrailleur est légal sous conditions.', value: true },
  { text: 'À Pékin, porter un t-shirt à message politique est passible d\'arrestation.', value: true },

  // Fausses (65)
  { text: 'En Italie, fournir de l\'eau du robinet gratuite est obligatoire dans tous les restaurants.', value: false },
  { text: 'À Pise, prendre la tour qui penche en photo en faisant semblant de la tenir est interdit.', value: false },
  { text: 'À Vienne, les chiens doivent porter une médaille en argent dans les parcs publics.', value: false },
  { text: 'À Madrid, embrasser sa partenaire avant 9h du matin est mal vu par décret.', value: false },
  { text: 'À Athènes, il est obligatoire de porter du blanc pendant les solstices.', value: false },
  { text: 'À Berlin, peindre sa maison en jaune nécessite un accord du quartier.', value: false },
  { text: 'En Suède, entrer dans un sauna avec un parapluie est interdit.', value: false },
  { text: 'Au Portugal, jouer du fado en public sans diplôme est mal vu par tradition.', value: false },
  { text: 'À Bruxelles, manger une gaufre en marchant après 22h est interdit.', value: false },
  { text: 'À Amsterdam, les vélos doivent obligatoirement être noirs ou rouges.', value: false },
  { text: 'À Naples, manger une pizza avec des couverts est interdit.', value: false },
  { text: 'À Florence, photographier le David sans flash est interdit aux moins de 18 ans.', value: false },
  { text: 'À Helsinki, saluer les ours sauvages en finnois est obligatoire.', value: false },
  { text: 'En Bavière, porter du Lederhose hors d\'Oktoberfest est interdit.', value: false },
  { text: 'À Bilbao, les supporteurs de l\'équipe rivale ne peuvent entrer en ville en jersey.', value: false },
  { text: 'À Édimbourg, les Écossais en kilt ne peuvent pas s\'asseoir sur les bancs publics.', value: false },
  { text: 'Au Pays de Galles, manger un poireau en public sans cérémonie est mal vu par tradition.', value: false },
  { text: 'À Liverpool, chanter du Beatles sans avoir payé une licence est interdit.', value: false },
  { text: 'À Manchester, il pleut au moins 200 jours par an par charte municipale.', value: false },
  { text: 'À Glasgow, parler doucement après 18h est passible d\'amende.', value: false },
  { text: 'À Belfast, danser sans partenaire est interdit dans les pubs.', value: false },
  { text: 'À Athènes, jeter un olivier en mer est passible d\'amende.', value: false },
  { text: 'À Nicosie, manger un kebab à l\'envers est mal vu.', value: false },
  { text: 'À Sofia, fumer en bus est puni par une danse forcée à la sortie.', value: false },
  { text: 'À Bucarest, posséder un chien sans laisse en rue piétonne est interdit le mardi.', value: false },
  { text: 'À Belgrade, chanter en cyrillique après minuit est interdit.', value: false },
  { text: 'À Zagreb, porter une cravate hors-fonction est passible d\'amende.', value: false },
  { text: 'À Ljubljana, dormir dans un parc public en chaussures rouges est interdit.', value: false },
  { text: 'À Vilnius, traverser la place de la cathédrale en sautillant est interdit.', value: false },
  { text: 'À Riga, parler letton avec un accent étranger est mal vu par décret.', value: false },
  { text: 'À Tallinn, photographier les Estoniens sans demander en estonien est interdit.', value: false },
  { text: 'À Tokyo, traverser à un feu rouge piéton la nuit entraîne un avertissement public.', value: false },
  { text: 'À Séoul, manger du kimchi en marchant est interdit dans le métro.', value: false },
  { text: 'À Hanoï, traverser sans regarder est obligatoire pour s\'intégrer.', value: false },
  { text: 'À Manille, conduire avec une chemise hawaïenne est interdit dans le centre-ville.', value: false },
  { text: 'À Bangkok, baigner dans une fontaine est passible de prison ferme.', value: false },
  { text: 'À Phnom Penh, jouer des congas après 22h est interdit.', value: false },
  { text: 'À Vientiane, marcher pieds nus en ville est interdit aux étrangers.', value: false },
  { text: 'À Yangon, sauter dans une flaque d\'eau pendant la mousson est interdit.', value: false },
  { text: 'À Kuala Lumpur, jouer du tambour la nuit est interdit en pleine ville.', value: false },
  { text: 'À Mumbai, conduire un tuk-tuk sans portrait de Ganesh est mal vu.', value: false },
  { text: 'À Chennai, manger un curry sans pain est interdit.', value: false },
  { text: 'À Calcutta, parler français dans un tramway est mal vu (vestige colonial).', value: false },
  { text: 'À Karachi, klaxonner avant 7h est passible d\'amende.', value: false },
  { text: 'À Dakar, conduire avec un manioc visible sur la banquette est mal vu.', value: false },
  { text: 'À Tunis, jouer aux cartes en café après minuit est interdit.', value: false },
  { text: 'À Marrakech, marchander un tapis sans demander un thé d\'abord est mal vu.', value: false },
  { text: 'À Brazzaville, manger en marchant en costume est mal vu.', value: false },
  { text: 'À Kinshasa, chanter dans un bus est interdit après 22h.', value: false },
  { text: 'À Antananarivo, prendre une photo sans sourire est interdit aux touristes.', value: false },
  { text: 'À Buenos Aires, prendre un tango pour un adieu est interdit.', value: false },
  { text: 'À Santiago, porter un pull rouge le dimanche est interdit dans le centre.', value: false },
  { text: 'À Caracas, klaxonner en chanson est passible d\'amende.', value: false },
  { text: 'À La Paz, courir à plus de 4000m d\'altitude sans certificat est interdit.', value: false },
  { text: 'À Asunción, manger un mate seul en public est mal vu.', value: false },
  { text: 'À Quito, parler espagnol castillan en marchand local est interdit.', value: false },
  { text: 'À Bogotá, jouer au yo-yo dans un bus est passible d\'amende.', value: false },
  { text: 'À Milan, sourire en permanence sauf aux funérailles est obligatoire par vieux décret.', value: false },
  { text: 'Au Royaume-Uni, mettre un timbre représentant le monarque à l\'envers est un acte de trahison.', value: false },
  { text: 'À Helsinki, tondre sa pelouse le dimanche est interdit toute l\'année.', value: false },
  { text: 'À Oslo, manger du saumon fumé avec des couverts en plastique est interdit.', value: false },
  { text: 'À Copenhague, traverser un pont en chantant est passible d\'amende.', value: false },
  { text: 'À Reykjavik, mettre du ketchup dans un hot-dog est interdit aux touristes.', value: false },
  { text: 'À Vienne, écouter de la valse dans un parc nécessite un permis musical.', value: false },
  { text: 'À Zurich, dire « bonjour » en français à un commerçant est mal vu.', value: false },
  { text: 'À Genève, parler de la Suisse alémanique au-delà du Röstigraben est mal vu.', value: false },
];

export const ABSURD_LAWS_HARD: AbsurdLawEntry[] = [
  // Vraies (33)
  { text: 'Au Royaume-Uni, entrer au Parlement en armure est interdit.', value: true },
  { text: 'En Floride, vendre de l\'alcool à pieds nus est interdit dans certains comtés.', value: true },
  { text: 'En Alabama, prétendre être un religieux (prêtre, rabbin, imam) sans l\'être est un délit.', value: true },
  { text: 'En Iowa, faire passer de la margarine pour du beurre dans un restaurant est un délit alimentaire.', value: true },
  { text: 'En Idaho, le cannibalisme est légal en cas de survie sous menace de mort.', value: true },
  { text: 'Au Texas, posséder plus de six « obscene devices » (sex-toys) est un délit.', value: true },
  { text: 'Au Lavandou (Var), il est interdit aux non-titulaires d\'une concession funéraire de mourir.', value: false },
  { text: 'À Laigneville (Oise), un arrêté municipal interdit de mourir.', value: true },
  { text: 'À Tonga, prendre une photo d\'un bateau le dimanche peut valoir un avertissement.', value: true },
  { text: 'À Pékin, distribuer des tracts politiques sans permis est passible d\'arrestation.', value: true },
  { text: 'À Téhéran, écouter de la musique occidentale forte en voiture peut entraîner une amende.', value: true },
  { text: 'Au Vietnam, traverser la rue en regardant son téléphone est passible d\'amende dans les grandes villes.', value: true },
  { text: 'À Capri, manger une glace en marchant en groupe peut être verbalisé en saison.', value: true },
  { text: 'À Venise, transporter une valise rigide à roulettes sur les ponts est interdit.', value: true },
  { text: 'À Singapour, ne pas tirer la chasse d\'eau dans les WC publics est passible d\'amende.', value: true },
  { text: 'À Pékin, photographier la Cité interdite avec un trépied nécessite un permis.', value: true },
  { text: 'En Suède, le démarchage en porte-à-porte le dimanche est interdit dans certaines communes.', value: true },
  { text: 'En Allemagne, traverser hors clous (jaywalking) est passible d\'amende.', value: true },
  { text: 'En Italie, gifler son enfant en public est juridiquement assimilé à un coup et susceptible de plainte.', value: true },
  { text: 'À Saint-Marin, posséder une réplique d\'arme sans la déclarer est un délit.', value: true },
  { text: 'En Écosse, il est interdit aux propriétaires de pubs de servir un client visiblement ivre.', value: true },
  { text: 'En Suisse, vidanger son lave-vaisselle pendant la nuit dans les copropriétés est souvent interdit.', value: true },
  { text: 'Aux Pays-Bas, un cycliste ivre peut être verbalisé comme un automobiliste.', value: true },
  { text: 'Au Royaume-Uni, manipuler un saumon « de manière suspecte » est puni par le Salmon Act 1986.', value: true },
  { text: 'En Russie, conduire une voiture sale peut valoir une amende administrative.', value: true },
  { text: 'En Suisse, jardiner le dimanche en zone résidentielle est restreint dans certains cantons.', value: true },
  { text: 'À Tonga, naviguer un bateau de plaisance le dimanche peut valoir une amende.', value: true },
  { text: 'À Florence, manger sur les marches de certains sites historiques est interdit.', value: true },
  { text: 'À Singapour, ne pas mettre la ceinture en taxi peut valoir une amende au passager.', value: true },
  { text: 'À Yokohama (Japon), fumer en marchant dans le centre-ville est interdit.', value: true },
  { text: 'Au Mont-Saint-Michel, marcher dans la baie sans guide officiel est interdit.', value: true },
  { text: 'À Cherbourg, photographier les sous-marins de la base militaire est interdit.', value: true },
  { text: 'À Niort, photographier le Marais poitevin avec un drone amateur sans déclaration est interdit.', value: true },
  { text: 'À Saint-Émilion, marcher dans les vignes sans accompagnant est interdit.', value: true },
  { text: 'À Libourne, traverser la Dordogne à la nage est interdit.', value: true },
  { text: 'À Foix, photographier un château avec un drone amateur sans déclaration est interdit.', value: true },
  { text: 'À Lourdes, parler fort dans la grotte est passible d\'avertissement.', value: true },

  // Fausses (64)
  { text: 'À Lyon, manger une quenelle avec les mains est passible d\'amende dans les bouchons traditionnels.', value: false },
  { text: 'À Marseille, porter un maillot de l\'OM dans une boulangerie le dimanche est mal vu par usage.', value: false },
  { text: 'À Toulouse, manger un cassoulet en moins de 30 minutes est interdit (atteinte au patrimoine).', value: false },
  { text: 'À Bordeaux, déguster du vin en moins de 3 gorgées est mal vu par charte de la profession.', value: false },
  { text: 'À Strasbourg, parler français à un Allemand est mal vu par tradition.', value: false },
  { text: 'À Lille, ne pas chanter au moins une chanson de Brel par an est passible d\'amende.', value: false },
  { text: 'À Nice, traverser la Promenade des Anglais en sandales claquantes est interdit.', value: false },
  { text: 'À Cannes, ne pas applaudir à la fin d\'un film en festival est passible d\'avertissement.', value: false },
  { text: 'À Brest, regarder fixement un marin pendant plus de 5 secondes est mal vu.', value: false },
  { text: 'À Reims, le port d\'un chapeau de paille en hiver est interdit dans les hôtels.', value: false },
  { text: 'À Avignon, parler du pape avant midi est interdit dans certaines paroisses.', value: false },
  { text: 'À Carcassonne, sortir d\'une taverne sans dire « santé » est passible d\'amende symbolique.', value: false },
  { text: 'À Annecy, plonger dans le lac sans bonnet de bain est interdit.', value: false },
  { text: 'À Chamonix, descendre une piste verte avec un bonnet rouge est mal vu par les guides.', value: false },
  { text: 'À Biarritz, surfer en costume trois pièces est interdit.', value: false },
  { text: 'À Saint-Malo, jeter un bigorneau en mer est interdit (gaspillage).', value: false },
  { text: 'À Honfleur, peindre sans permis sur le port est interdit aux non-résidents.', value: false },
  { text: 'À Dieppe, manger une moule à la fourchette est interdit dans les restaurants typiques.', value: false },
  { text: 'À Calais, embarquer sur un ferry en short est interdit après 18h.', value: false },
  { text: 'À Boulogne, parler avec un poisson est interdit aux poissonniers.', value: false },
  { text: 'À Le Havre, klaxonner près d\'une mouette est passible d\'amende environnementale.', value: false },
  { text: 'À La Baule, marcher pieds nus sur le sable hors plage déclarée est interdit.', value: false },
  { text: 'À Bayeux, regarder la tapisserie en mangeant un sandwich est interdit.', value: false },
  { text: 'À Rouen, déguster un cidre sans cidrière homologuée est mal vu.', value: false },
  { text: 'À Caen, dîner avec une bougie après 22h est passible d\'avertissement.', value: false },
  { text: 'À Ouistreham, prendre un bain à 6h du matin est interdit.', value: false },
  { text: 'À Granville, prendre une photo du carnaval est interdit aux moins de 12 ans.', value: false },
  { text: 'À Saint-Tropez, débarquer d\'un yacht en sandales en cuir est interdit.', value: false },
  { text: 'À Cassis, manger une bouillabaisse en moins de 20 minutes est interdit.', value: false },
  { text: 'À Hyères, transporter un chat sans laisse est passible d\'amende.', value: false },
  { text: 'À Bandol, déguster un rosé sans verre transparent est mal vu.', value: false },
  { text: 'À Aix-en-Provence, traverser le Cours Mirabeau en patin à roulettes est interdit.', value: false },
  { text: 'À Avignon, jouer du violoncelle sous le pont est interdit (sauf festival).', value: false },
  { text: 'À Orange, parler latin en plein été est mal vu (héritage romain).', value: false },
  { text: 'À Nîmes, parler de Rome en plein cœur des arènes est mal vu.', value: false },
  { text: 'À Montpellier, manger une socca sans s\'être lavé les mains est interdit.', value: false },
  { text: 'À Béziers, importer du chorizo non labellisé est passible d\'amende.', value: false },
  { text: 'À Perpignan, parler espagnol avec un accent argentin est mal vu.', value: false },
  { text: 'À Toulouse, décliner un pastis offert est mal vu par usage.', value: false },
  { text: 'À Albi, traverser la cathédrale en running est interdit.', value: false },
  { text: 'À Rodez, manger un aligot avec une cuillère plate est interdit.', value: false },
  { text: 'À Auch, ne pas siffler en mangeant un foie gras est mal vu.', value: false },
  { text: 'À Pau, contempler les Pyrénées plus de 10 minutes est mal vu (signe de paresse).', value: false },
  { text: 'À Tarbes, transporter un foulard rouge en juillet est mal vu.', value: false },
  { text: 'À Biarritz, prendre un café en bord de mer en cravate est interdit.', value: false },
  { text: 'À Bayonne, manger un jambon hors AOP est passible d\'amende symbolique.', value: false },
  { text: 'À Saint-Jean-de-Luz, manger un macaron en marchant est interdit.', value: false },
  { text: 'À Hendaye, parler espagnol côté français est mal vu (et l\'inverse).', value: false },
  { text: 'À Ciboure, prendre une photo du port à l\'aube est mal vu.', value: false },
  { text: 'À Anglet, surfer sans plaque d\'identification est interdit.', value: false },
  { text: 'À Bordeaux, sortir d\'un château viticole sans avoir acheté est mal vu.', value: false },
  { text: 'À Pessac, parler du Médoc dans une cave de Graves est passible d\'avertissement.', value: false },
  { text: 'À Cognac, mélanger du cognac avec du soda est interdit dans les bars labellisés.', value: false },
  { text: 'À Angoulême, parler de bande dessinée en pâtisserie est mal vu.', value: false },
  { text: 'À La Rochelle, ne pas saluer la mer en partant en bateau est passible d\'amende portuaire.', value: false },
  { text: 'À Royan, prendre un bain de mer en costume sombre est interdit.', value: false },
  { text: 'À Saintes, traverser la Charente en pédalo est interdit le dimanche.', value: false },
  { text: 'À Poitiers, parler vite dans une boulangerie est passible d\'avertissement.', value: false },
  { text: 'À Limoges, polir une porcelaine en public est interdit aux mineurs.', value: false },
  { text: 'À Clermont-Ferrand, manger une potée auvergnate sans bénir le repas est mal vu.', value: false },
  { text: 'À Vichy, boire de l\'eau du robinet est mal vu en présence d\'un thermaliste.', value: false },
  { text: 'À Saint-Étienne, parler du club rival (OL) est passible d\'avertissement dans les bars.', value: false },
  { text: 'À Grenoble, descendre du téléphérique en chantant est interdit en hiver.', value: false },
  { text: 'À Dijon, sortir d\'un restaurant sans pot de moutarde est mal vu.', value: false },
];
