/**
 * Catalogue d'acronymes / sigles pour le Quiz CEO type `acronyme-sigle`.
 * Format StringAnswer : le joueur tape la signification, validation manuelle
 * par le créateur en review (les `aliases` sont informatifs).
 *
 * Distribution : 50 EASY + 50 MEDIUM + 50 HARD = 150 entrées.
 *   - EASY   : sigles ultra-grand-public (SNCF, OTAN, ADN, USA…)
 *   - MEDIUM : sigles connus mais moins immédiats (UNESCO, OCDE, RGPD…)
 *   - HARD   : sigles administratifs / techniques / de niche (URSSAF, ANSSI,
 *              ARCEP, CSAPA…)
 */

export interface AcronymEntry {
  text: string; // l'acronyme
  answer: string; // la signification développée
  aliases?: string[]; // variantes acceptables (informatif)
}

export const ACRONYMS_EASY: AcronymEntry[] = [
  { text: 'SNCF', answer: 'Société nationale des chemins de fer français' },
  { text: 'OTAN', answer: "Organisation du traité de l'Atlantique Nord", aliases: ['NATO'] },
  { text: 'ADN', answer: 'Acide désoxyribonucléique' },
  { text: 'FBI', answer: 'Federal Bureau of Investigation' },
  { text: 'USA', answer: "United States of America", aliases: ["États-Unis d'Amérique"] },
  { text: 'OVNI', answer: 'Objet volant non identifié' },
  { text: 'OGM', answer: 'Organisme génétiquement modifié' },
  { text: 'PIB', answer: 'Produit intérieur brut' },
  { text: 'RER', answer: 'Réseau express régional' },
  { text: 'SDF', answer: 'Sans domicile fixe' },
  { text: 'RIB', answer: "Relevé d'identité bancaire" },
  { text: 'BAC', answer: 'Baccalauréat' },
  { text: 'PDG', answer: 'Président-directeur général' },
  { text: 'CV', answer: 'Curriculum vitae' },
  { text: 'SOS', answer: 'Save Our Souls', aliases: ['Save Our Ship', 'signal de détresse'] },
  { text: 'FAQ', answer: 'Foire aux questions', aliases: ['Frequently Asked Questions'] },
  { text: 'SMS', answer: 'Short Message Service' },
  { text: 'URL', answer: 'Uniform Resource Locator' },
  { text: 'NASA', answer: 'National Aeronautics and Space Administration' },
  { text: 'RAM', answer: 'Random Access Memory' },
  { text: 'PC', answer: 'Personal Computer', aliases: ['ordinateur personnel'] },
  { text: 'WC', answer: 'Water Closet' },
  { text: 'TV', answer: 'Télévision' },
  { text: 'CD', answer: 'Compact Disc' },
  { text: 'DVD', answer: 'Digital Versatile Disc', aliases: ['Digital Video Disc'] },
  { text: 'HTML', answer: 'HyperText Markup Language' },
  { text: 'PDF', answer: 'Portable Document Format' },
  { text: 'WIFI', answer: 'Wireless Fidelity', aliases: ['Wi-Fi'] },
  { text: 'CEO', answer: 'Chief Executive Officer' },
  { text: 'RDV', answer: 'Rendez-vous' },
  { text: 'LOL', answer: 'Laughing Out Loud' },
  { text: 'CIA', answer: 'Central Intelligence Agency' },
  { text: 'NBA', answer: 'National Basketball Association' },
  { text: 'UEFA', answer: 'Union of European Football Associations', aliases: ['Union des associations européennes de football'] },
  { text: 'FIFA', answer: 'Fédération Internationale de Football Association' },
  { text: 'SAMU', answer: "Service d'aide médicale urgente" },
  { text: 'BMW', answer: 'Bayerische Motoren Werke' },
  { text: 'SARL', answer: 'Société à responsabilité limitée' },
  { text: 'SA', answer: 'Société anonyme' },
  { text: 'RH', answer: 'Ressources humaines' },
  { text: 'RSA', answer: 'Revenu de solidarité active' },
  { text: 'CDI', answer: 'Contrat à durée indéterminée' },
  { text: 'CDD', answer: 'Contrat à durée déterminée' },
  { text: 'SMIC', answer: 'Salaire minimum interprofessionnel de croissance' },
  { text: 'TVA', answer: 'Taxe sur la valeur ajoutée' },
  { text: 'JO', answer: 'Jeux olympiques' },
  { text: 'GPS', answer: 'Global Positioning System' },
  { text: 'CO2', answer: 'Dioxyde de carbone' },
  { text: 'TGV', answer: 'Train à grande vitesse' },
  { text: 'EDF', answer: "Électricité de France" },
];

export const ACRONYMS_MEDIUM: AcronymEntry[] = [
  { text: 'UNESCO', answer: 'United Nations Educational, Scientific and Cultural Organization' },
  { text: 'OMS', answer: 'Organisation mondiale de la santé', aliases: ['WHO'] },
  { text: 'OCDE', answer: 'Organisation de coopération et de développement économiques' },
  { text: 'RATP', answer: 'Régie autonome des transports parisiens' },
  { text: 'AVC', answer: 'Accident vasculaire cérébral' },
  { text: 'SIDA', answer: "Syndrome d'immunodéficience acquise" },
  { text: 'UV', answer: 'Ultraviolet' },
  { text: 'CRS', answer: 'Compagnies républicaines de sécurité' },
  { text: 'MMA', answer: 'Mixed Martial Arts', aliases: ['arts martiaux mixtes'] },
  { text: 'NSA', answer: 'National Security Agency' },
  { text: 'KGB', answer: "Komitet Gossoudarstvennoï Bezopasnosti", aliases: ["Comité pour la sécurité de l'État"] },
  { text: 'UFC', answer: 'Ultimate Fighting Championship' },
  { text: 'RPG', answer: 'Role Playing Game', aliases: ['jeu de rôle'] },
  { text: 'FPS', answer: 'First-Person Shooter' },
  { text: 'MMO', answer: 'Massively Multiplayer Online' },
  { text: 'DLC', answer: 'Downloadable Content' },
  { text: 'NPC', answer: 'Non-Player Character' },
  { text: 'AFP', answer: 'Agence France-Presse' },
  { text: 'INSEE', answer: "Institut national de la statistique et des études économiques" },
  { text: 'CNRS', answer: 'Centre national de la recherche scientifique' },
  { text: 'RGPD', answer: 'Règlement général sur la protection des données' },
  { text: 'IRM', answer: 'Imagerie par résonance magnétique' },
  { text: 'OPEP', answer: "Organisation des pays exportateurs de pétrole", aliases: ['OPEC'] },
  { text: 'NSFW', answer: 'Not Safe For Work' },
  { text: 'SCOP', answer: 'Société coopérative et participative' },
  { text: 'SCI', answer: 'Société civile immobilière' },
  { text: 'DOM', answer: "Département d'outre-mer" },
  { text: 'TOM', answer: "Territoire d'outre-mer" },
  { text: 'SDIS', answer: "Service départemental d'incendie et de secours" },
  { text: 'CFA', answer: "Centre de formation d'apprentis" },
  { text: 'RTT', answer: 'Réduction du temps de travail' },
  { text: 'PMU', answer: 'Pari mutuel urbain' },
  { text: 'RGB', answer: 'Red Green Blue', aliases: ['rouge vert bleu'] },
  { text: 'CMJN', answer: 'Cyan Magenta Jaune Noir' },
  { text: 'PAO', answer: 'Publication assistée par ordinateur' },
  { text: 'CNIL', answer: "Commission nationale de l'informatique et des libertés" },
  { text: 'ARS', answer: 'Agence régionale de santé' },
  { text: 'IBAN', answer: 'International Bank Account Number' },
  { text: 'PNL', answer: 'Programmation neuro-linguistique' },
  { text: 'TOC', answer: 'Trouble obsessionnel compulsif' },
  { text: 'PMA', answer: 'Procréation médicalement assistée' },
  { text: 'GPA', answer: 'Gestation pour autrui' },
  { text: 'IVG', answer: 'Interruption volontaire de grossesse' },
  { text: 'AOC', answer: "Appellation d'origine contrôlée" },
  { text: 'ATM', answer: 'Automated Teller Machine', aliases: ['distributeur automatique'] },
  { text: 'ASAP', answer: 'As Soon As Possible' },
  { text: 'BTS', answer: 'Brevet de technicien supérieur' },
  { text: 'DUT', answer: 'Diplôme universitaire de technologie' },
  { text: 'CES', answer: 'Consumer Electronics Show' },
  { text: 'BCE', answer: 'Banque centrale européenne' },
];

export const ACRONYMS_HARD: AcronymEntry[] = [
  { text: 'ARCEP', answer: "Autorité de régulation des communications électroniques, des postes et de la distribution de la presse" },
  { text: 'AFNOR', answer: 'Association française de normalisation' },
  { text: 'EHPAD', answer: "Établissement d'hébergement pour personnes âgées dépendantes" },
  { text: 'INPI', answer: "Institut national de la propriété industrielle" },
  { text: 'AMF', answer: 'Autorité des marchés financiers' },
  { text: 'ANSSI', answer: "Agence nationale de la sécurité des systèmes d'information" },
  { text: 'ANSM', answer: "Agence nationale de sécurité du médicament et des produits de santé" },
  { text: 'URSSAF', answer: "Union de recouvrement des cotisations de sécurité sociale et d'allocations familiales" },
  { text: 'PACS', answer: 'Pacte civil de solidarité' },
  { text: 'BTP', answer: 'Bâtiment et travaux publics' },
  { text: 'APEC', answer: "Association pour l'emploi des cadres" },
  { text: 'AGIRC', answer: 'Association générale des institutions de retraite des cadres' },
  { text: 'ARRCO', answer: 'Association pour le régime de retraite complémentaire des salariés' },
  { text: 'ANAH', answer: "Agence nationale de l'habitat" },
  { text: 'ANRU', answer: "Agence nationale pour la rénovation urbaine" },
  { text: 'CAF', answer: "Caisse d'allocations familiales" },
  { text: 'CPAM', answer: "Caisse primaire d'assurance maladie" },
  { text: 'CNAM', answer: "Caisse nationale d'assurance maladie" },
  { text: 'CMU', answer: 'Couverture maladie universelle' },
  { text: 'DGSE', answer: "Direction générale de la sécurité extérieure" },
  { text: 'DGSI', answer: "Direction générale de la sécurité intérieure" },
  { text: 'GIGN', answer: "Groupe d'intervention de la gendarmerie nationale" },
  { text: 'RAID', answer: 'Recherche, assistance, intervention, dissuasion' },
  { text: 'BRI', answer: "Brigade de recherche et d'intervention" },
  { text: 'CRPC', answer: 'Comparution sur reconnaissance préalable de culpabilité' },
  { text: 'AOP', answer: "Appellation d'origine protégée" },
  { text: 'IGP', answer: 'Indication géographique protégée' },
  { text: 'STMG', answer: 'Sciences et technologies du management et de la gestion' },
  { text: 'STAPS', answer: 'Sciences et techniques des activités physiques et sportives' },
  { text: 'BUT', answer: 'Bachelor universitaire de technologie' },
  { text: 'CFE', answer: 'Contribution foncière des entreprises' },
  { text: 'CIR', answer: "Crédit d'impôt recherche" },
  { text: 'CET', answer: 'Compte épargne-temps' },
  { text: 'PEL', answer: "Plan d'épargne logement" },
  { text: 'CEL', answer: 'Compte épargne logement' },
  { text: 'PEA', answer: "Plan d'épargne en actions" },
  { text: 'SICAV', answer: "Société d'investissement à capital variable" },
  { text: 'FCP', answer: 'Fonds commun de placement' },
  { text: 'CSG', answer: 'Contribution sociale généralisée' },
  { text: 'CRDS', answer: 'Contribution au remboursement de la dette sociale' },
  { text: 'ZNIEFF', answer: "Zone naturelle d'intérêt écologique, faunistique et floristique" },
  { text: 'BPCO', answer: 'Bronchopneumopathie chronique obstructive' },
  { text: 'CESEDA', answer: "Code de l'entrée et du séjour des étrangers et du droit d'asile" },
  { text: 'OQTF', answer: 'Obligation de quitter le territoire français' },
  { text: 'CSAPA', answer: "Centre de soins, d'accompagnement et de prévention en addictologie" },
  { text: 'CESE', answer: 'Conseil économique, social et environnemental' },
  { text: 'ZAC', answer: "Zone d'aménagement concerté" },
  { text: 'ZEP', answer: "Zone d'éducation prioritaire" },
  { text: 'POS', answer: "Plan d'occupation des sols" },
  { text: 'ENA', answer: "École nationale d'administration" },
];
