/**
 * Liste exhaustive ISO 3166-1 alpha-2 → nom français, pour les SVG « contour
 * de pays » du Quiz CEO.
 *
 * Source CDN : https://cdn-assets.teuteuf.fr/data/common/country-shapes/<iso2>.svg
 * Cible      : public/country-shapes/<iso2>.svg (téléchargés une fois)
 *
 * Utilisé par `scripts/download-country-shapes.ts` quand on veut tout le monde
 * (option `--all` ou env `ALL=1`). La liste worldle (`lib/worldle/countries.ts`)
 * reste plus restreinte (44 pays choisis) et sert de défaut pour Worldle.
 */

export interface CountryEntry {
  /** Code ISO 3166-1 alpha-2 minuscule. */
  id: string;
  /** Nom canonique en français (affiché en review, utilisé pour la comparaison fuzzy). */
  name: string;
  /** Variantes acceptées (anglais, sans accents, locales courantes). */
  aliases: string[];
}

export const ALL_COUNTRIES: CountryEntry[] = [
  { id: 'ad', name: 'Andorre', aliases: ['Andorra'] },
  { id: 'ae', name: 'Émirats arabes unis', aliases: ['United Arab Emirates', 'UAE', 'Emirats arabes unis'] },
  { id: 'af', name: 'Afghanistan', aliases: [] },
  { id: 'ag', name: 'Antigua-et-Barbuda', aliases: ['Antigua and Barbuda'] },
  { id: 'al', name: 'Albanie', aliases: ['Albania'] },
  { id: 'am', name: 'Arménie', aliases: ['Armenia', 'Armenie'] },
  { id: 'ao', name: 'Angola', aliases: [] },
  { id: 'ar', name: 'Argentine', aliases: ['Argentina'] },
  { id: 'at', name: 'Autriche', aliases: ['Austria'] },
  { id: 'au', name: 'Australie', aliases: ['Australia'] },
  { id: 'az', name: 'Azerbaïdjan', aliases: ['Azerbaijan', 'Azerbaidjan'] },
  { id: 'ba', name: 'Bosnie-Herzégovine', aliases: ['Bosnia and Herzegovina', 'Bosnie'] },
  { id: 'bb', name: 'Barbade', aliases: ['Barbados'] },
  { id: 'bd', name: 'Bangladesh', aliases: [] },
  { id: 'be', name: 'Belgique', aliases: ['Belgium'] },
  { id: 'bf', name: 'Burkina Faso', aliases: [] },
  { id: 'bg', name: 'Bulgarie', aliases: ['Bulgaria'] },
  { id: 'bh', name: 'Bahreïn', aliases: ['Bahrain', 'Bahrein'] },
  { id: 'bi', name: 'Burundi', aliases: [] },
  { id: 'bj', name: 'Bénin', aliases: ['Benin'] },
  { id: 'bn', name: 'Brunei', aliases: ['Brunei Darussalam'] },
  { id: 'bo', name: 'Bolivie', aliases: ['Bolivia'] },
  { id: 'br', name: 'Brésil', aliases: ['Brazil', 'Bresil'] },
  { id: 'bs', name: 'Bahamas', aliases: [] },
  { id: 'bt', name: 'Bhoutan', aliases: ['Bhutan'] },
  { id: 'bw', name: 'Botswana', aliases: [] },
  { id: 'by', name: 'Biélorussie', aliases: ['Belarus', 'Bielorussie'] },
  { id: 'bz', name: 'Belize', aliases: [] },
  { id: 'ca', name: 'Canada', aliases: [] },
  { id: 'cd', name: 'République démocratique du Congo', aliases: ['DRC', 'Congo-Kinshasa', 'Democratic Republic of the Congo'] },
  { id: 'cf', name: 'République centrafricaine', aliases: ['Central African Republic', 'Centrafrique'] },
  { id: 'cg', name: 'République du Congo', aliases: ['Congo', 'Congo-Brazzaville', 'Republic of the Congo'] },
  { id: 'ch', name: 'Suisse', aliases: ['Switzerland', 'Schweiz'] },
  { id: 'ci', name: "Côte d'Ivoire", aliases: ["Cote d'Ivoire", 'Ivory Coast'] },
  { id: 'cl', name: 'Chili', aliases: ['Chile'] },
  { id: 'cm', name: 'Cameroun', aliases: ['Cameroon'] },
  { id: 'cn', name: 'Chine', aliases: ['China'] },
  { id: 'co', name: 'Colombie', aliases: ['Colombia'] },
  { id: 'cr', name: 'Costa Rica', aliases: [] },
  { id: 'cu', name: 'Cuba', aliases: [] },
  { id: 'cv', name: 'Cap-Vert', aliases: ['Cape Verde', 'Cabo Verde'] },
  { id: 'cy', name: 'Chypre', aliases: ['Cyprus'] },
  { id: 'cz', name: 'Tchéquie', aliases: ['Czech Republic', 'Czechia', 'Republique Tcheque'] },
  { id: 'de', name: 'Allemagne', aliases: ['Germany', 'Deutschland'] },
  { id: 'dj', name: 'Djibouti', aliases: [] },
  { id: 'dk', name: 'Danemark', aliases: ['Denmark'] },
  { id: 'dm', name: 'Dominique', aliases: ['Dominica'] },
  { id: 'do', name: 'République dominicaine', aliases: ['Dominican Republic'] },
  { id: 'dz', name: 'Algérie', aliases: ['Algeria', 'Algerie'] },
  { id: 'ec', name: 'Équateur', aliases: ['Ecuador', 'Equateur'] },
  { id: 'ee', name: 'Estonie', aliases: ['Estonia'] },
  { id: 'eg', name: 'Égypte', aliases: ['Egypt', 'Egypte'] },
  { id: 'er', name: 'Érythrée', aliases: ['Eritrea', 'Erythree'] },
  { id: 'es', name: 'Espagne', aliases: ['Spain', 'España', 'Espana'] },
  { id: 'et', name: 'Éthiopie', aliases: ['Ethiopia', 'Ethiopie'] },
  { id: 'fi', name: 'Finlande', aliases: ['Finland'] },
  { id: 'fj', name: 'Fidji', aliases: ['Fiji'] },
  { id: 'fm', name: 'Micronésie', aliases: ['Micronesia', 'Micronesie'] },
  { id: 'fr', name: 'France', aliases: [] },
  { id: 'ga', name: 'Gabon', aliases: [] },
  { id: 'gb', name: 'Royaume-Uni', aliases: ['United Kingdom', 'UK', 'Angleterre', 'England', 'Great Britain'] },
  { id: 'gd', name: 'Grenade', aliases: ['Grenada'] },
  { id: 'ge', name: 'Géorgie', aliases: ['Georgia', 'Georgie'] },
  { id: 'gh', name: 'Ghana', aliases: [] },
  { id: 'gm', name: 'Gambie', aliases: ['Gambia'] },
  { id: 'gn', name: 'Guinée', aliases: ['Guinea', 'Guinee'] },
  { id: 'gq', name: 'Guinée équatoriale', aliases: ['Equatorial Guinea', 'Guinee equatoriale'] },
  { id: 'gr', name: 'Grèce', aliases: ['Greece', 'Grece'] },
  { id: 'gt', name: 'Guatemala', aliases: [] },
  { id: 'gw', name: 'Guinée-Bissau', aliases: ['Guinea-Bissau', 'Guinee-Bissau'] },
  { id: 'gy', name: 'Guyana', aliases: ['Guyane'] },
  { id: 'hn', name: 'Honduras', aliases: [] },
  { id: 'hr', name: 'Croatie', aliases: ['Croatia', 'Hrvatska'] },
  { id: 'ht', name: 'Haïti', aliases: ['Haiti'] },
  { id: 'hu', name: 'Hongrie', aliases: ['Hungary', 'Magyarország'] },
  { id: 'id', name: 'Indonésie', aliases: ['Indonesia', 'Indonesie'] },
  { id: 'ie', name: 'Irlande', aliases: ['Ireland'] },
  { id: 'il', name: 'Israël', aliases: ['Israel'] },
  { id: 'in', name: 'Inde', aliases: ['India'] },
  { id: 'iq', name: 'Irak', aliases: ['Iraq'] },
  { id: 'ir', name: 'Iran', aliases: [] },
  { id: 'is', name: 'Islande', aliases: ['Iceland'] },
  { id: 'it', name: 'Italie', aliases: ['Italy', 'Italia'] },
  { id: 'jm', name: 'Jamaïque', aliases: ['Jamaica', 'Jamaique'] },
  { id: 'jo', name: 'Jordanie', aliases: ['Jordan'] },
  { id: 'jp', name: 'Japon', aliases: ['Japan'] },
  { id: 'ke', name: 'Kenya', aliases: [] },
  { id: 'kg', name: 'Kirghizistan', aliases: ['Kyrgyzstan'] },
  { id: 'kh', name: 'Cambodge', aliases: ['Cambodia'] },
  { id: 'ki', name: 'Kiribati', aliases: [] },
  { id: 'km', name: 'Comores', aliases: ['Comoros'] },
  { id: 'kn', name: 'Saint-Kitts-et-Nevis', aliases: ['Saint Kitts and Nevis'] },
  { id: 'kp', name: 'Corée du Nord', aliases: ['North Korea', 'Coree du Nord', 'DPRK'] },
  { id: 'kr', name: 'Corée du Sud', aliases: ['South Korea', 'Coree du Sud'] },
  { id: 'kw', name: 'Koweït', aliases: ['Kuwait', 'Koweit'] },
  { id: 'kz', name: 'Kazakhstan', aliases: [] },
  { id: 'la', name: 'Laos', aliases: [] },
  { id: 'lb', name: 'Liban', aliases: ['Lebanon'] },
  { id: 'lc', name: 'Sainte-Lucie', aliases: ['Saint Lucia'] },
  { id: 'li', name: 'Liechtenstein', aliases: [] },
  { id: 'lk', name: 'Sri Lanka', aliases: [] },
  { id: 'lr', name: 'Liberia', aliases: ['Libéria'] },
  { id: 'ls', name: 'Lesotho', aliases: [] },
  { id: 'lt', name: 'Lituanie', aliases: ['Lithuania'] },
  { id: 'lu', name: 'Luxembourg', aliases: [] },
  { id: 'lv', name: 'Lettonie', aliases: ['Latvia'] },
  { id: 'ly', name: 'Libye', aliases: ['Libya'] },
  { id: 'ma', name: 'Maroc', aliases: ['Morocco'] },
  { id: 'mc', name: 'Monaco', aliases: [] },
  { id: 'md', name: 'Moldavie', aliases: ['Moldova'] },
  { id: 'me', name: 'Monténégro', aliases: ['Montenegro'] },
  { id: 'mg', name: 'Madagascar', aliases: [] },
  { id: 'mh', name: 'Îles Marshall', aliases: ['Marshall Islands', 'Iles Marshall'] },
  { id: 'mk', name: 'Macédoine du Nord', aliases: ['North Macedonia', 'Macedoine'] },
  { id: 'ml', name: 'Mali', aliases: [] },
  { id: 'mm', name: 'Birmanie', aliases: ['Myanmar', 'Burma'] },
  { id: 'mn', name: 'Mongolie', aliases: ['Mongolia'] },
  { id: 'mr', name: 'Mauritanie', aliases: ['Mauritania'] },
  { id: 'mt', name: 'Malte', aliases: ['Malta'] },
  { id: 'mu', name: 'Maurice', aliases: ['Mauritius'] },
  { id: 'mv', name: 'Maldives', aliases: [] },
  { id: 'mw', name: 'Malawi', aliases: [] },
  { id: 'mx', name: 'Mexique', aliases: ['Mexico', 'México'] },
  { id: 'my', name: 'Malaisie', aliases: ['Malaysia'] },
  { id: 'mz', name: 'Mozambique', aliases: [] },
  { id: 'na', name: 'Namibie', aliases: ['Namibia'] },
  { id: 'ne', name: 'Niger', aliases: [] },
  { id: 'ng', name: 'Nigéria', aliases: ['Nigeria'] },
  { id: 'ni', name: 'Nicaragua', aliases: [] },
  { id: 'nl', name: 'Pays-Bas', aliases: ['Netherlands', 'Holland', 'Nederland'] },
  { id: 'no', name: 'Norvège', aliases: ['Norway', 'Norge', 'Norvege'] },
  { id: 'np', name: 'Népal', aliases: ['Nepal'] },
  { id: 'nr', name: 'Nauru', aliases: [] },
  { id: 'nz', name: 'Nouvelle-Zélande', aliases: ['New Zealand', 'Nouvelle Zelande'] },
  { id: 'om', name: 'Oman', aliases: [] },
  { id: 'pa', name: 'Panama', aliases: ['Panamá'] },
  { id: 'pe', name: 'Pérou', aliases: ['Peru', 'Perou'] },
  { id: 'pg', name: 'Papouasie-Nouvelle-Guinée', aliases: ['Papua New Guinea'] },
  { id: 'ph', name: 'Philippines', aliases: ['Pilipinas'] },
  { id: 'pk', name: 'Pakistan', aliases: [] },
  { id: 'pl', name: 'Pologne', aliases: ['Poland', 'Polska'] },
  { id: 'pt', name: 'Portugal', aliases: [] },
  { id: 'pw', name: 'Palaos', aliases: ['Palau'] },
  { id: 'py', name: 'Paraguay', aliases: [] },
  { id: 'qa', name: 'Qatar', aliases: [] },
  { id: 'ro', name: 'Roumanie', aliases: ['Romania'] },
  { id: 'rs', name: 'Serbie', aliases: ['Serbia'] },
  { id: 'ru', name: 'Russie', aliases: ['Russia'] },
  { id: 'rw', name: 'Rwanda', aliases: [] },
  { id: 'sa', name: 'Arabie saoudite', aliases: ['Saudi Arabia', 'Arabie Saoudite'] },
  { id: 'sb', name: 'Îles Salomon', aliases: ['Solomon Islands', 'Iles Salomon'] },
  { id: 'sc', name: 'Seychelles', aliases: [] },
  { id: 'sd', name: 'Soudan', aliases: ['Sudan'] },
  { id: 'se', name: 'Suède', aliases: ['Sweden', 'Sverige', 'Suede'] },
  { id: 'sg', name: 'Singapour', aliases: ['Singapore'] },
  { id: 'si', name: 'Slovénie', aliases: ['Slovenia', 'Slovenie'] },
  { id: 'sk', name: 'Slovaquie', aliases: ['Slovakia'] },
  { id: 'sl', name: 'Sierra Leone', aliases: [] },
  { id: 'sm', name: 'Saint-Marin', aliases: ['San Marino'] },
  { id: 'sn', name: 'Sénégal', aliases: ['Senegal'] },
  { id: 'so', name: 'Somalie', aliases: ['Somalia'] },
  { id: 'sr', name: 'Suriname', aliases: [] },
  { id: 'ss', name: 'Soudan du Sud', aliases: ['South Sudan'] },
  { id: 'st', name: 'Sao Tomé-et-Principe', aliases: ['Sao Tome and Principe'] },
  { id: 'sv', name: 'Salvador', aliases: ['El Salvador'] },
  { id: 'sy', name: 'Syrie', aliases: ['Syria'] },
  { id: 'sz', name: 'Eswatini', aliases: ['Swaziland'] },
  { id: 'td', name: 'Tchad', aliases: ['Chad'] },
  { id: 'tg', name: 'Togo', aliases: [] },
  { id: 'th', name: 'Thaïlande', aliases: ['Thailand', 'Thailande'] },
  { id: 'tj', name: 'Tadjikistan', aliases: ['Tajikistan'] },
  { id: 'tl', name: 'Timor oriental', aliases: ['East Timor', 'Timor-Leste'] },
  { id: 'tm', name: 'Turkménistan', aliases: ['Turkmenistan'] },
  { id: 'tn', name: 'Tunisie', aliases: ['Tunisia'] },
  { id: 'to', name: 'Tonga', aliases: [] },
  { id: 'tr', name: 'Turquie', aliases: ['Turkey', 'Türkiye'] },
  { id: 'tt', name: 'Trinité-et-Tobago', aliases: ['Trinidad and Tobago'] },
  { id: 'tv', name: 'Tuvalu', aliases: [] },
  { id: 'tw', name: 'Taïwan', aliases: ['Taiwan'] },
  { id: 'tz', name: 'Tanzanie', aliases: ['Tanzania'] },
  { id: 'ua', name: 'Ukraine', aliases: [] },
  { id: 'ug', name: 'Ouganda', aliases: ['Uganda'] },
  { id: 'us', name: 'États-Unis', aliases: ['United States', 'USA', 'US', 'Etats-Unis', 'America'] },
  { id: 'uy', name: 'Uruguay', aliases: [] },
  { id: 'uz', name: 'Ouzbékistan', aliases: ['Uzbekistan'] },
  { id: 'va', name: 'Vatican', aliases: ['Holy See', 'Cité du Vatican'] },
  { id: 'vc', name: 'Saint-Vincent-et-les-Grenadines', aliases: ['Saint Vincent and the Grenadines'] },
  { id: 've', name: 'Venezuela', aliases: [] },
  { id: 'vn', name: 'Vietnam', aliases: ['Viet Nam'] },
  { id: 'vu', name: 'Vanuatu', aliases: [] },
  { id: 'ws', name: 'Samoa', aliases: [] },
  { id: 'ye', name: 'Yémen', aliases: ['Yemen'] },
  { id: 'za', name: 'Afrique du Sud', aliases: ['South Africa'] },
  { id: 'zm', name: 'Zambie', aliases: ['Zambia'] },
  { id: 'zw', name: 'Zimbabwe', aliases: [] },
];
