/**
 * Catalogue de marques pour la question Quiz CEO `brand-logo`.
 *
 * Source des SVG : **simple-icons** (CC0, ~3000 logos monochromes).
 *   - CDN : https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/<slug>.svg
 *   - Documentation des slugs : https://github.com/simple-icons/simple-icons/blob/develop/slugs.md
 *
 * Les SVG téléchargés une fois via `npm run download:brand-logos` et stockés
 * sous `public/brand-logos/<slug>.svg`. Servis ensuite par Next.js avec cache
 * HTTP optimal — aucun runtime dépendance externe.
 *
 * Le script `cleanup-brand-logos.ts` bascule la couleur en blanc pour
 * visibilité sur le fond sombre du Quiz CEO.
 *
 * **Sélection** : ~500 marques connues en France (pas forcément françaises).
 * Certains slugs peuvent être absents de simple-icons → le script de
 * download skip silencieusement les 404. La liste finale réelle est ce qui
 * est présent dans `public/brand-logos/`.
 *
 * Si tu ajoutes une marque ici : relancer
 *   `npm run download:brand-logos && npm run cleanup:brand-logos`
 * (idempotent, skip ce qui existe déjà).
 */

export interface BrandEntry {
  /** Slug simple-icons — c'est aussi le nom du fichier SVG local. */
  slug: string;
  /** Nom canonique en français (affiché en review, source de vérité Bon/Faux). */
  name: string;
  /** Variantes acceptées (anglais, sans accents, cas alternatifs). */
  aliases: string[];
}

export const BRANDS: BrandEntry[] = [
  // ============ TECH / GAFAM / INTERNET ============
  { slug: 'apple', name: 'Apple', aliases: [] },
  { slug: 'google', name: 'Google', aliases: [] },
  { slug: 'microsoft', name: 'Microsoft', aliases: [] },
  { slug: 'amazon', name: 'Amazon', aliases: [] },
  { slug: 'meta', name: 'Meta', aliases: ['Facebook'] },
  { slug: 'facebook', name: 'Facebook', aliases: [] },
  { slug: 'netflix', name: 'Netflix', aliases: [] },
  { slug: 'youtube', name: 'YouTube', aliases: [] },
  { slug: 'instagram', name: 'Instagram', aliases: [] },
  { slug: 'x', name: 'X', aliases: ['Twitter'] },
  { slug: 'tiktok', name: 'TikTok', aliases: [] },
  { slug: 'snapchat', name: 'Snapchat', aliases: [] },
  { slug: 'linkedin', name: 'LinkedIn', aliases: [] },
  { slug: 'whatsapp', name: 'WhatsApp', aliases: [] },
  { slug: 'telegram', name: 'Telegram', aliases: [] },
  { slug: 'signal', name: 'Signal', aliases: [] },
  { slug: 'discord', name: 'Discord', aliases: [] },
  { slug: 'slack', name: 'Slack', aliases: [] },
  { slug: 'zoom', name: 'Zoom', aliases: [] },
  { slug: 'skype', name: 'Skype', aliases: [] },
  { slug: 'pinterest', name: 'Pinterest', aliases: [] },
  { slug: 'reddit', name: 'Reddit', aliases: [] },
  { slug: 'twitch', name: 'Twitch', aliases: [] },
  { slug: 'spotify', name: 'Spotify', aliases: [] },
  { slug: 'soundcloud', name: 'SoundCloud', aliases: [] },
  { slug: 'deezer', name: 'Deezer', aliases: [] },
  { slug: 'shazam', name: 'Shazam', aliases: [] },
  { slug: 'dropbox', name: 'Dropbox', aliases: [] },
  { slug: 'github', name: 'GitHub', aliases: [] },
  { slug: 'gitlab', name: 'GitLab', aliases: [] },
  { slug: 'bitbucket', name: 'Bitbucket', aliases: [] },
  { slug: 'figma', name: 'Figma', aliases: [] },
  { slug: 'notion', name: 'Notion', aliases: [] },
  { slug: 'trello', name: 'Trello', aliases: [] },
  { slug: 'asana', name: 'Asana', aliases: [] },
  { slug: 'jira', name: 'Jira', aliases: [] },
  { slug: 'airtable', name: 'Airtable', aliases: [] },
  { slug: 'evernote', name: 'Evernote', aliases: [] },
  { slug: 'stripe', name: 'Stripe', aliases: [] },
  { slug: 'shopify', name: 'Shopify', aliases: [] },
  { slug: 'paypal', name: 'PayPal', aliases: [] },
  { slug: 'visa', name: 'Visa', aliases: [] },
  { slug: 'mastercard', name: 'Mastercard', aliases: [] },
  { slug: 'americanexpress', name: 'American Express', aliases: ['Amex'] },
  { slug: 'wise', name: 'Wise', aliases: ['TransferWise'] },
  { slug: 'revolut', name: 'Revolut', aliases: [] },
  { slug: 'n26', name: 'N26', aliases: [] },
  { slug: 'airbnb', name: 'Airbnb', aliases: [] },
  { slug: 'uber', name: 'Uber', aliases: [] },
  { slug: 'ubereats', name: 'Uber Eats', aliases: [] },
  { slug: 'deliveroo', name: 'Deliveroo', aliases: [] },
  { slug: 'doordash', name: 'DoorDash', aliases: [] },
  { slug: 'lyft', name: 'Lyft', aliases: [] },
  { slug: 'blablacar', name: 'BlaBlaCar', aliases: [] },
  { slug: 'tesla', name: 'Tesla', aliases: [] },
  { slug: 'spacex', name: 'SpaceX', aliases: [] },
  { slug: 'nvidia', name: 'Nvidia', aliases: ['NVIDIA'] },
  { slug: 'intel', name: 'Intel', aliases: [] },
  { slug: 'amd', name: 'AMD', aliases: [] },
  { slug: 'arm', name: 'ARM', aliases: [] },
  { slug: 'ibm', name: 'IBM', aliases: [] },
  { slug: 'oracle', name: 'Oracle', aliases: [] },
  { slug: 'sap', name: 'SAP', aliases: [] },
  { slug: 'salesforce', name: 'Salesforce', aliases: [] },
  { slug: 'adobe', name: 'Adobe', aliases: [] },
  { slug: 'samsung', name: 'Samsung', aliases: [] },
  { slug: 'lg', name: 'LG', aliases: [] },
  { slug: 'sony', name: 'Sony', aliases: [] },
  { slug: 'huawei', name: 'Huawei', aliases: [] },
  { slug: 'xiaomi', name: 'Xiaomi', aliases: [] },
  { slug: 'oppo', name: 'OPPO', aliases: [] },
  { slug: 'oneplus', name: 'OnePlus', aliases: [] },
  { slug: 'lenovo', name: 'Lenovo', aliases: [] },
  { slug: 'dell', name: 'Dell', aliases: [] },
  { slug: 'hp', name: 'HP', aliases: ['Hewlett-Packard'] },
  { slug: 'asus', name: 'Asus', aliases: ['ASUS'] },
  { slug: 'acer', name: 'Acer', aliases: [] },
  { slug: 'msi', name: 'MSI', aliases: [] },
  { slug: 'razer', name: 'Razer', aliases: [] },
  { slug: 'logitech', name: 'Logitech', aliases: [] },
  { slug: 'corsair', name: 'Corsair', aliases: [] },
  { slug: 'canon', name: 'Canon', aliases: [] },
  { slug: 'nikon', name: 'Nikon', aliases: [] },
  { slug: 'leica', name: 'Leica', aliases: [] },
  { slug: 'gopro', name: 'GoPro', aliases: [] },
  { slug: 'dji', name: 'DJI', aliases: [] },
  { slug: 'bose', name: 'Bose', aliases: [] },
  { slug: 'beatsbydre', name: 'Beats by Dre', aliases: ['Beats'] },
  { slug: 'jbl', name: 'JBL', aliases: [] },
  { slug: 'sennheiser', name: 'Sennheiser', aliases: [] },
  { slug: 'harmankardon', name: 'Harman Kardon', aliases: [] },
  { slug: 'philips', name: 'Philips', aliases: [] },
  { slug: 'siemens', name: 'Siemens', aliases: [] },
  { slug: 'panasonic', name: 'Panasonic', aliases: [] },
  { slug: 'electrolux', name: 'Electrolux', aliases: [] },
  { slug: 'whirlpool', name: 'Whirlpool', aliases: [] },
  { slug: 'dyson', name: 'Dyson', aliases: [] },
  { slug: 'roomba', name: 'Roomba', aliases: ['iRobot'] },

  // ============ NAVIGATEURS / OS / OUTILS ============
  { slug: 'firefox', name: 'Firefox', aliases: [] },
  { slug: 'googlechrome', name: 'Google Chrome', aliases: ['Chrome'] },
  { slug: 'safari', name: 'Safari', aliases: [] },
  { slug: 'opera', name: 'Opera', aliases: [] },
  { slug: 'microsoftedge', name: 'Microsoft Edge', aliases: ['Edge'] },
  { slug: 'brave', name: 'Brave', aliases: [] },
  { slug: 'tor', name: 'Tor', aliases: [] },
  { slug: 'duckduckgo', name: 'DuckDuckGo', aliases: [] },
  { slug: 'mozilla', name: 'Mozilla', aliases: [] },
  { slug: 'linux', name: 'Linux', aliases: [] },
  { slug: 'ubuntu', name: 'Ubuntu', aliases: [] },
  { slug: 'debian', name: 'Debian', aliases: [] },
  { slug: 'fedora', name: 'Fedora', aliases: [] },
  { slug: 'archlinux', name: 'Arch Linux', aliases: [] },
  { slug: 'redhat', name: 'Red Hat', aliases: [] },
  { slug: 'android', name: 'Android', aliases: [] },
  { slug: 'ios', name: 'iOS', aliases: [] },

  // ============ APPS / SaaS / Productivité ============
  { slug: 'gmail', name: 'Gmail', aliases: [] },
  { slug: 'googledrive', name: 'Google Drive', aliases: [] },
  { slug: 'googlemaps', name: 'Google Maps', aliases: [] },
  { slug: 'googletranslate', name: 'Google Translate', aliases: [] },
  { slug: 'googleplay', name: 'Google Play', aliases: [] },
  { slug: 'googlecalendar', name: 'Google Calendar', aliases: [] },
  { slug: 'googlephotos', name: 'Google Photos', aliases: [] },
  { slug: 'waze', name: 'Waze', aliases: [] },
  { slug: 'icloud', name: 'iCloud', aliases: [] },
  { slug: 'applemusic', name: 'Apple Music', aliases: [] },
  { slug: 'applepodcasts', name: 'Apple Podcasts', aliases: [] },
  { slug: 'applepay', name: 'Apple Pay', aliases: [] },
  { slug: 'applestore', name: 'App Store', aliases: ['Apple Store'] },
  { slug: 'appletv', name: 'Apple TV', aliases: ['Apple TV+'] },
  { slug: 'microsoftonedrive', name: 'OneDrive', aliases: [] },
  { slug: 'microsoftoffice', name: 'Microsoft Office', aliases: ['Office'] },
  { slug: 'microsoftword', name: 'Word', aliases: ['Microsoft Word'] },
  { slug: 'microsoftexcel', name: 'Excel', aliases: ['Microsoft Excel'] },
  { slug: 'microsoftpowerpoint', name: 'PowerPoint', aliases: ['Microsoft PowerPoint'] },
  { slug: 'microsoftoutlook', name: 'Outlook', aliases: [] },
  { slug: 'microsoftteams', name: 'Microsoft Teams', aliases: [] },
  { slug: 'adobephotoshop', name: 'Photoshop', aliases: [] },
  { slug: 'adobeillustrator', name: 'Illustrator', aliases: [] },
  { slug: 'adobepremierepro', name: 'Premiere Pro', aliases: [] },
  { slug: 'adobeaftereffects', name: 'After Effects', aliases: [] },
  { slug: 'adobelightroom', name: 'Lightroom', aliases: [] },
  { slug: 'canva', name: 'Canva', aliases: [] },
  { slug: 'sketch', name: 'Sketch', aliases: [] },
  { slug: 'blender', name: 'Blender', aliases: [] },
  { slug: 'unrealengine', name: 'Unreal Engine', aliases: [] },
  { slug: 'unity', name: 'Unity', aliases: [] },
  { slug: 'docker', name: 'Docker', aliases: [] },
  { slug: 'kubernetes', name: 'Kubernetes', aliases: [] },
  { slug: 'vercel', name: 'Vercel', aliases: [] },
  { slug: 'netlify', name: 'Netlify', aliases: [] },
  { slug: 'cloudflare', name: 'Cloudflare', aliases: [] },
  { slug: 'wordpress', name: 'WordPress', aliases: [] },
  { slug: 'tinder', name: 'Tinder', aliases: [] },
  { slug: 'bumble', name: 'Bumble', aliases: [] },
  { slug: 'duolingo', name: 'Duolingo', aliases: [] },
  { slug: 'medium', name: 'Medium', aliases: [] },
  { slug: 'quora', name: 'Quora', aliases: [] },
  { slug: 'stackoverflow', name: 'Stack Overflow', aliases: [] },
  { slug: 'wikipedia', name: 'Wikipedia', aliases: [] },
  { slug: 'patreon', name: 'Patreon', aliases: [] },
  { slug: 'onlyfans', name: 'OnlyFans', aliases: [] },
  { slug: 'tumblr', name: 'Tumblr', aliases: [] },
  { slug: 'vimeo', name: 'Vimeo', aliases: [] },
  { slug: 'dailymotion', name: 'Dailymotion', aliases: [] },
  { slug: 'mastodon', name: 'Mastodon', aliases: [] },
  { slug: 'threads', name: 'Threads', aliases: [] },
  { slug: 'bluesky', name: 'Bluesky', aliases: [] },
  { slug: 'bereal', name: 'BeReal', aliases: [] },

  // ============ VOITURES ============
  { slug: 'bmw', name: 'BMW', aliases: [] },
  { slug: 'mercedes', name: 'Mercedes-Benz', aliases: ['Mercedes'] },
  { slug: 'audi', name: 'Audi', aliases: [] },
  { slug: 'porsche', name: 'Porsche', aliases: [] },
  { slug: 'volkswagen', name: 'Volkswagen', aliases: ['VW'] },
  { slug: 'peugeot', name: 'Peugeot', aliases: [] },
  { slug: 'renault', name: 'Renault', aliases: [] },
  { slug: 'citroen', name: 'Citroën', aliases: ['Citroen'] },
  { slug: 'dacia', name: 'Dacia', aliases: [] },
  { slug: 'ds', name: 'DS Automobiles', aliases: ['DS'] },
  { slug: 'ferrari', name: 'Ferrari', aliases: [] },
  { slug: 'lamborghini', name: 'Lamborghini', aliases: [] },
  { slug: 'maserati', name: 'Maserati', aliases: [] },
  { slug: 'alfaromeo', name: 'Alfa Romeo', aliases: [] },
  { slug: 'fiat', name: 'Fiat', aliases: [] },
  { slug: 'lancia', name: 'Lancia', aliases: [] },
  { slug: 'toyota', name: 'Toyota', aliases: [] },
  { slug: 'honda', name: 'Honda', aliases: [] },
  { slug: 'nissan', name: 'Nissan', aliases: [] },
  { slug: 'mazda', name: 'Mazda', aliases: [] },
  { slug: 'subaru', name: 'Subaru', aliases: [] },
  { slug: 'mitsubishi', name: 'Mitsubishi', aliases: [] },
  { slug: 'suzuki', name: 'Suzuki', aliases: [] },
  { slug: 'hyundai', name: 'Hyundai', aliases: [] },
  { slug: 'kia', name: 'Kia', aliases: [] },
  { slug: 'ford', name: 'Ford', aliases: [] },
  { slug: 'chevrolet', name: 'Chevrolet', aliases: ['Chevy'] },
  { slug: 'cadillac', name: 'Cadillac', aliases: [] },
  { slug: 'jeep', name: 'Jeep', aliases: [] },
  { slug: 'dodge', name: 'Dodge', aliases: [] },
  { slug: 'gmc', name: 'GMC', aliases: [] },
  { slug: 'volvo', name: 'Volvo', aliases: [] },
  { slug: 'bentley', name: 'Bentley', aliases: [] },
  { slug: 'rollsroyce', name: 'Rolls-Royce', aliases: ['Rolls Royce'] },
  { slug: 'mclarenautomotive', name: 'McLaren', aliases: [] },
  { slug: 'astonmartin', name: 'Aston Martin', aliases: [] },
  { slug: 'jaguar', name: 'Jaguar', aliases: [] },
  { slug: 'landrover', name: 'Land Rover', aliases: [] },
  { slug: 'mini', name: 'Mini', aliases: ['MINI'] },
  { slug: 'smart', name: 'Smart', aliases: [] },
  { slug: 'lotus', name: 'Lotus', aliases: [] },
  { slug: 'skoda', name: 'Škoda', aliases: ['Skoda'] },
  { slug: 'seat', name: 'Seat', aliases: ['SEAT'] },
  { slug: 'cupra', name: 'Cupra', aliases: [] },
  { slug: 'opel', name: 'Opel', aliases: [] },
  { slug: 'lexus', name: 'Lexus', aliases: [] },
  { slug: 'infiniti', name: 'Infiniti', aliases: [] },
  { slug: 'acura', name: 'Acura', aliases: [] },
  { slug: 'genesis', name: 'Genesis', aliases: [] },
  { slug: 'bugatti', name: 'Bugatti', aliases: [] },
  { slug: 'rivian', name: 'Rivian', aliases: [] },
  { slug: 'lucidmotors', name: 'Lucid Motors', aliases: ['Lucid'] },
  { slug: 'polestar', name: 'Polestar', aliases: [] },
  { slug: 'byd', name: 'BYD', aliases: [] },
  { slug: 'nio', name: 'NIO', aliases: [] },

  // ============ MOTOS / 2-ROUES ============
  { slug: 'ducati', name: 'Ducati', aliases: [] },
  { slug: 'yamaha', name: 'Yamaha', aliases: [] },
  { slug: 'kawasaki', name: 'Kawasaki', aliases: [] },
  { slug: 'harleydavidson', name: 'Harley-Davidson', aliases: [] },
  { slug: 'vespa', name: 'Vespa', aliases: [] },
  { slug: 'triumph', name: 'Triumph', aliases: [] },
  { slug: 'ktm', name: 'KTM', aliases: [] },

  // ============ PNEUS / OUTILS / BRICOLAGE ============
  { slug: 'michelin', name: 'Michelin', aliases: [] },
  { slug: 'bridgestone', name: 'Bridgestone', aliases: [] },
  { slug: 'pirelli', name: 'Pirelli', aliases: [] },
  { slug: 'goodyear', name: 'Goodyear', aliases: [] },
  { slug: 'continental', name: 'Continental', aliases: [] },
  { slug: 'bosch', name: 'Bosch', aliases: [] },
  { slug: 'makita', name: 'Makita', aliases: [] },
  { slug: 'dewalt', name: 'DeWalt', aliases: [] },
  { slug: 'stanley', name: 'Stanley', aliases: [] },
  { slug: 'blackanddecker', name: 'Black & Decker', aliases: [] },
  { slug: 'karcher', name: 'Kärcher', aliases: ['Karcher'] },

  // ============ RESTAURATION FRANCAISE / FAST-FOOD ============
  { slug: 'mcdonalds', name: "McDonald's", aliases: ['McDo', 'MacDo'] },
  { slug: 'kfc', name: 'KFC', aliases: ['Kentucky Fried Chicken'] },
  { slug: 'burgerking', name: 'Burger King', aliases: [] },
  { slug: 'subway', name: 'Subway', aliases: [] },
  { slug: 'starbucks', name: 'Starbucks', aliases: [] },
  { slug: 'dominos', name: "Domino's Pizza", aliases: ["Domino's", 'Dominos'] },
  { slug: 'pizzahut', name: 'Pizza Hut', aliases: [] },
  { slug: 'tacobell', name: 'Taco Bell', aliases: [] },
  { slug: 'chipotle', name: 'Chipotle', aliases: [] },
  { slug: 'dunkin', name: 'Dunkin Donuts', aliases: ['Dunkin'] },
  { slug: 'wendys', name: "Wendy's", aliases: [] },
  { slug: 'chickfila', name: 'Chick-fil-A', aliases: [] },
  { slug: 'panera', name: 'Panera Bread', aliases: ['Panera'] },
  { slug: 'paul', name: 'Paul', aliases: [] },
  { slug: 'briochedoree', name: 'Brioche Dorée', aliases: [] },
  { slug: 'krispykreme', name: 'Krispy Kreme', aliases: [] },
  { slug: 'iams', name: 'Iams', aliases: [] },

  // ============ BOISSONS / SODAS / EAU ============
  { slug: 'cocacola', name: 'Coca-Cola', aliases: ['Coca', 'Coke'] },
  { slug: 'pepsi', name: 'Pepsi', aliases: ['Pepsi-Cola'] },
  { slug: 'sprite', name: 'Sprite', aliases: [] },
  { slug: 'fanta', name: 'Fanta', aliases: [] },
  { slug: 'redbull', name: 'Red Bull', aliases: [] },
  { slug: 'monster', name: 'Monster Energy', aliases: ['Monster'] },
  { slug: 'schweppes', name: 'Schweppes', aliases: [] },
  { slug: 'orangina', name: 'Orangina', aliases: [] },
  { slug: 'perrier', name: 'Perrier', aliases: [] },
  { slug: 'evian', name: 'Evian', aliases: [] },
  { slug: 'volvic', name: 'Volvic', aliases: [] },
  { slug: 'badoit', name: 'Badoit', aliases: [] },
  { slug: 'sanpellegrino', name: 'San Pellegrino', aliases: [] },
  { slug: 'tropicana', name: 'Tropicana', aliases: [] },
  { slug: 'innocent', name: 'Innocent', aliases: [] },
  { slug: 'lipton', name: 'Lipton', aliases: [] },
  { slug: 'nesquik', name: 'Nesquik', aliases: [] },

  // ============ ALCOOL / BIÈRE / VIN ============
  { slug: 'heineken', name: 'Heineken', aliases: [] },
  { slug: 'carlsberg', name: 'Carlsberg', aliases: [] },
  { slug: 'budweiser', name: 'Budweiser', aliases: ['Bud'] },
  { slug: 'corona', name: 'Corona', aliases: [] },
  { slug: 'guinness', name: 'Guinness', aliases: [] },
  { slug: 'kronenbourg', name: 'Kronenbourg', aliases: [] },
  { slug: '1664', name: '1664', aliases: [] },
  { slug: 'leffe', name: 'Leffe', aliases: [] },
  { slug: 'hoegaarden', name: 'Hoegaarden', aliases: [] },
  { slug: 'stellaartois', name: 'Stella Artois', aliases: [] },
  { slug: 'desperados', name: 'Desperados', aliases: [] },
  { slug: 'jagermeister', name: 'Jägermeister', aliases: [] },
  { slug: 'bacardi', name: 'Bacardi', aliases: [] },
  { slug: 'absolutvodka', name: 'Absolut', aliases: [] },
  { slug: 'jackdaniels', name: "Jack Daniel's", aliases: [] },
  { slug: 'jameson', name: 'Jameson', aliases: [] },
  { slug: 'baileys', name: "Bailey's", aliases: [] },
  { slug: 'martini', name: 'Martini', aliases: [] },
  { slug: 'campari', name: 'Campari', aliases: [] },

  // ============ ALIMENTAIRE / CHOCOLAT / SNACKS ============
  { slug: 'nestle', name: 'Nestlé', aliases: ['Nestle'] },
  { slug: 'danone', name: 'Danone', aliases: [] },
  { slug: 'lindt', name: 'Lindt', aliases: [] },
  { slug: 'milka', name: 'Milka', aliases: [] },
  { slug: 'cadbury', name: 'Cadbury', aliases: [] },
  { slug: 'ferrero', name: 'Ferrero', aliases: [] },
  { slug: 'kitkat', name: 'KitKat', aliases: ['Kit Kat'] },
  { slug: 'mars', name: 'Mars', aliases: [] },
  { slug: 'snickers', name: 'Snickers', aliases: [] },
  { slug: 'twix', name: 'Twix', aliases: [] },
  { slug: 'oreo', name: 'Oreo', aliases: [] },
  { slug: 'haribo', name: 'Haribo', aliases: [] },
  { slug: 'mentos', name: 'Mentos', aliases: [] },
  { slug: 'pringles', name: 'Pringles', aliases: [] },
  { slug: 'lays', name: "Lay's", aliases: [] },
  { slug: 'doritos', name: 'Doritos', aliases: [] },
  { slug: 'cheetos', name: 'Cheetos', aliases: [] },
  { slug: 'kelloggs', name: "Kellogg's", aliases: [] },
  { slug: 'heinz', name: 'Heinz', aliases: [] },
  { slug: 'hellmanns', name: "Hellmann's", aliases: [] },
  { slug: 'mccain', name: 'McCain', aliases: [] },
  { slug: 'barilla', name: 'Barilla', aliases: [] },

  // ============ MODE / SPORTSWEAR ============
  { slug: 'nike', name: 'Nike', aliases: [] },
  { slug: 'adidas', name: 'Adidas', aliases: [] },
  { slug: 'puma', name: 'Puma', aliases: [] },
  { slug: 'reebok', name: 'Reebok', aliases: [] },
  { slug: 'underarmour', name: 'Under Armour', aliases: [] },
  { slug: 'newbalance', name: 'New Balance', aliases: [] },
  { slug: 'asics', name: 'Asics', aliases: ['ASICS'] },
  { slug: 'vans', name: 'Vans', aliases: [] },
  { slug: 'converse', name: 'Converse', aliases: [] },
  { slug: 'fila', name: 'Fila', aliases: [] },
  { slug: 'kappa', name: 'Kappa', aliases: [] },
  { slug: 'champion', name: 'Champion', aliases: [] },
  { slug: 'lacoste', name: 'Lacoste', aliases: [] },
  { slug: 'levis', name: "Levi's", aliases: ['Levis'] },
  { slug: 'wrangler', name: 'Wrangler', aliases: [] },
  { slug: 'calvinklein', name: 'Calvin Klein', aliases: [] },
  { slug: 'tommyhilfiger', name: 'Tommy Hilfiger', aliases: [] },
  { slug: 'ralphlauren', name: 'Ralph Lauren', aliases: [] },
  { slug: 'hugoboss', name: 'Hugo Boss', aliases: [] },
  { slug: 'diesel', name: 'Diesel', aliases: [] },
  { slug: 'gap', name: 'Gap', aliases: [] },
  { slug: 'zara', name: 'Zara', aliases: [] },
  { slug: 'hm', name: 'H&M', aliases: ['Hennes & Mauritz'] },
  { slug: 'uniqlo', name: 'Uniqlo', aliases: [] },
  { slug: 'mango', name: 'Mango', aliases: [] },
  { slug: 'thenorthface', name: 'The North Face', aliases: [] },
  { slug: 'patagonia', name: 'Patagonia', aliases: [] },
  { slug: 'columbia', name: 'Columbia', aliases: [] },
  { slug: 'salomon', name: 'Salomon', aliases: [] },
  { slug: 'aigle', name: 'Aigle', aliases: [] },

  // ============ LUXE / HAUTE-COUTURE / PARFUMS ============
  { slug: 'gucci', name: 'Gucci', aliases: [] },
  { slug: 'prada', name: 'Prada', aliases: [] },
  { slug: 'louisvuitton', name: 'Louis Vuitton', aliases: ['LV'] },
  { slug: 'chanel', name: 'Chanel', aliases: [] },
  { slug: 'hermes', name: 'Hermès', aliases: ['Hermes'] },
  { slug: 'dior', name: 'Dior', aliases: [] },
  { slug: 'versace', name: 'Versace', aliases: [] },
  { slug: 'burberry', name: 'Burberry', aliases: [] },
  { slug: 'givenchy', name: 'Givenchy', aliases: [] },
  { slug: 'balmain', name: 'Balmain', aliases: [] },
  { slug: 'kenzo', name: 'Kenzo', aliases: [] },
  { slug: 'lancome', name: 'Lancôme', aliases: ['Lancome'] },
  { slug: 'loreal', name: "L'Oréal", aliases: ['LOreal'] },
  { slug: 'garnier', name: 'Garnier', aliases: [] },
  { slug: 'maybelline', name: 'Maybelline', aliases: [] },
  { slug: 'esteelauder', name: 'Estée Lauder', aliases: [] },
  { slug: 'sephora', name: 'Sephora', aliases: [] },
  { slug: 'mac', name: 'MAC', aliases: ['MAC Cosmetics'] },

  // ============ HORLOGERIE / BIJOUX ============
  { slug: 'rolex', name: 'Rolex', aliases: [] },
  { slug: 'omega', name: 'Omega', aliases: [] },
  { slug: 'cartier', name: 'Cartier', aliases: [] },
  { slug: 'tagheuer', name: 'TAG Heuer', aliases: [] },
  { slug: 'breitling', name: 'Breitling', aliases: [] },
  { slug: 'tissot', name: 'Tissot', aliases: [] },
  { slug: 'casio', name: 'Casio', aliases: [] },
  { slug: 'swatch', name: 'Swatch', aliases: [] },
  { slug: 'fossil', name: 'Fossil', aliases: [] },
  { slug: 'tiffanyandco', name: 'Tiffany & Co.', aliases: ['Tiffany'] },

  // ============ JEUX VIDÉO / GAMING ============
  { slug: 'nintendo', name: 'Nintendo', aliases: [] },
  { slug: 'playstation', name: 'PlayStation', aliases: [] },
  { slug: 'xbox', name: 'Xbox', aliases: [] },
  { slug: 'steam', name: 'Steam', aliases: [] },
  { slug: 'epicgames', name: 'Epic Games', aliases: [] },
  { slug: 'ubisoft', name: 'Ubisoft', aliases: [] },
  { slug: 'ea', name: 'Electronic Arts', aliases: ['EA'] },
  { slug: 'activision', name: 'Activision', aliases: [] },
  { slug: 'blizzard', name: 'Blizzard', aliases: [] },
  { slug: 'riotgames', name: 'Riot Games', aliases: ['Riot'] },
  { slug: 'squareenix', name: 'Square Enix', aliases: [] },
  { slug: 'sega', name: 'Sega', aliases: ['SEGA'] },
  { slug: 'rockstargames', name: 'Rockstar Games', aliases: ['Rockstar'] },
  { slug: 'capcom', name: 'Capcom', aliases: [] },
  { slug: 'konami', name: 'Konami', aliases: [] },
  { slug: 'bandainamco', name: 'Bandai Namco', aliases: [] },
  { slug: 'minecraft', name: 'Minecraft', aliases: [] },
  { slug: 'roblox', name: 'Roblox', aliases: [] },
  { slug: 'fortnite', name: 'Fortnite', aliases: [] },
  { slug: 'leagueoflegends', name: 'League of Legends', aliases: ['LoL'] },
  { slug: 'valorant', name: 'Valorant', aliases: [] },
  { slug: 'counterstrike', name: 'Counter-Strike', aliases: ['CS'] },
  { slug: 'pubg', name: 'PUBG', aliases: [] },
  { slug: 'apexlegends', name: 'Apex Legends', aliases: [] },
  { slug: 'gta', name: 'Grand Theft Auto', aliases: ['GTA'] },
  { slug: 'pokemon', name: 'Pokémon', aliases: ['Pokemon'] },
  { slug: 'fifa', name: 'FIFA', aliases: [] },
  { slug: 'callofduty', name: 'Call of Duty', aliases: ['CoD'] },

  // ============ MÉDIAS / STREAMING / CINÉMA ============
  { slug: 'disney', name: 'Disney', aliases: [] },
  { slug: 'disneyplus', name: 'Disney+', aliases: ['Disney Plus'] },
  { slug: 'marvel', name: 'Marvel', aliases: [] },
  { slug: 'dccomics', name: 'DC Comics', aliases: ['DC'] },
  { slug: 'pixar', name: 'Pixar', aliases: [] },
  { slug: 'hbo', name: 'HBO', aliases: [] },
  { slug: 'paramountplus', name: 'Paramount+', aliases: ['Paramount'] },
  { slug: 'primevideo', name: 'Prime Video', aliases: ['Amazon Prime Video'] },
  { slug: 'imdb', name: 'IMDb', aliases: [] },
  { slug: 'rottentomatoes', name: 'Rotten Tomatoes', aliases: [] },
  { slug: 'allocine', name: 'AlloCiné', aliases: ['Allocine'] },
  { slug: 'crunchyroll', name: 'Crunchyroll', aliases: [] },
  { slug: 'mubi', name: 'MUBI', aliases: [] },

  // ============ TÉLÉ / PRESSE FRANÇAISE ============
  { slug: 'lemonde', name: 'Le Monde', aliases: [] },
  { slug: 'lefigaro', name: 'Le Figaro', aliases: [] },
  { slug: 'liberation', name: 'Libération', aliases: ['Liberation'] },
  { slug: 'lequipe', name: "L'Équipe", aliases: ['LEquipe'] },
  { slug: 'mediapart', name: 'Mediapart', aliases: [] },
  { slug: 'leparisien', name: 'Le Parisien', aliases: [] },
  { slug: 'rfi', name: 'RFI', aliases: [] },
  { slug: 'franceinfo', name: 'France Info', aliases: [] },
  { slug: 'francetvinfo', name: 'France TV', aliases: [] },
  { slug: 'tf1', name: 'TF1', aliases: [] },
  { slug: 'm6', name: 'M6', aliases: [] },
  { slug: 'arte', name: 'Arte', aliases: [] },
  { slug: 'canalplus', name: 'Canal+', aliases: ['Canal Plus'] },
  { slug: 'bfmtv', name: 'BFM TV', aliases: ['BFMTV'] },

  // ============ MÉDIAS INTERNATIONAUX ============
  { slug: 'bbc', name: 'BBC', aliases: [] },
  { slug: 'cnn', name: 'CNN', aliases: [] },
  { slug: 'nbc', name: 'NBC', aliases: [] },
  { slug: 'foxnews', name: 'Fox News', aliases: [] },
  { slug: 'theguardian', name: 'The Guardian', aliases: [] },
  { slug: 'thenewyorktimes', name: 'The New York Times', aliases: ['NYT'] },
  { slug: 'thewashingtonpost', name: 'The Washington Post', aliases: [] },
  { slug: 'forbes', name: 'Forbes', aliases: [] },
  { slug: 'bloomberg', name: 'Bloomberg', aliases: [] },
  { slug: 'reuters', name: 'Reuters', aliases: [] },
  { slug: 'nationalgeographic', name: 'National Geographic', aliases: [] },

  // ============ DISTRIBUTION / SUPERMARCHÉS / MAGASINS FR ============
  { slug: 'carrefour', name: 'Carrefour', aliases: [] },
  { slug: 'auchan', name: 'Auchan', aliases: [] },
  { slug: 'leclerc', name: 'E.Leclerc', aliases: ['Leclerc'] },
  { slug: 'casino', name: 'Casino', aliases: [] },
  { slug: 'monoprix', name: 'Monoprix', aliases: [] },
  { slug: 'lidl', name: 'Lidl', aliases: [] },
  { slug: 'aldi', name: 'Aldi', aliases: [] },
  { slug: 'intermarche', name: 'Intermarché', aliases: ['Intermarche'] },
  { slug: 'picard', name: 'Picard', aliases: [] },
  { slug: 'walmart', name: 'Walmart', aliases: [] },
  { slug: 'costco', name: 'Costco', aliases: [] },
  { slug: 'target', name: 'Target', aliases: [] },
  { slug: 'tesco', name: 'Tesco', aliases: [] },
  { slug: 'aldinord', name: 'Aldi Nord', aliases: [] },

  // ============ BRICOLAGE / DECO / ELECTROMÉNAGER FR ============
  { slug: 'ikea', name: 'IKEA', aliases: ['Ikea'] },
  { slug: 'leroymerlin', name: 'Leroy Merlin', aliases: [] },
  { slug: 'castorama', name: 'Castorama', aliases: [] },
  { slug: 'fnac', name: 'Fnac', aliases: ['FNAC'] },
  { slug: 'darty', name: 'Darty', aliases: [] },
  { slug: 'boulanger', name: 'Boulanger', aliases: [] },
  { slug: 'conforama', name: 'Conforama', aliases: [] },
  { slug: 'maisonsdumonde', name: 'Maisons du Monde', aliases: [] },
  { slug: 'decathlon', name: 'Decathlon', aliases: ['Décathlon'] },

  // ============ E-COMMERCE / VENTE EN LIGNE ============
  { slug: 'ebay', name: 'eBay', aliases: [] },
  { slug: 'aliexpress', name: 'AliExpress', aliases: [] },
  { slug: 'alibaba', name: 'Alibaba', aliases: [] },
  { slug: 'shein', name: 'Shein', aliases: [] },
  { slug: 'temu', name: 'Temu', aliases: [] },
  { slug: 'wish', name: 'Wish', aliases: [] },
  { slug: 'etsy', name: 'Etsy', aliases: [] },
  { slug: 'vinted', name: 'Vinted', aliases: [] },
  { slug: 'leboncoin', name: 'Le Bon Coin', aliases: [] },
  { slug: 'backmarket', name: 'Back Market', aliases: ['BackMarket'] },
  { slug: 'cdiscount', name: 'Cdiscount', aliases: [] },
  { slug: 'asos', name: 'ASOS', aliases: [] },
  { slug: 'zalando', name: 'Zalando', aliases: [] },

  // ============ LIVRAISON / LOGISTIQUE ============
  { slug: 'fedex', name: 'FedEx', aliases: [] },
  { slug: 'ups', name: 'UPS', aliases: [] },
  { slug: 'dhl', name: 'DHL', aliases: [] },
  { slug: 'laposte', name: 'La Poste', aliases: [] },
  { slug: 'chronopost', name: 'Chronopost', aliases: [] },
  { slug: 'colissimo', name: 'Colissimo', aliases: [] },
  { slug: 'mondialrelay', name: 'Mondial Relay', aliases: [] },

  // ============ COMPAGNIES AÉRIENNES / TRAINS ============
  { slug: 'airfrance', name: 'Air France', aliases: [] },
  { slug: 'klm', name: 'KLM', aliases: [] },
  { slug: 'lufthansa', name: 'Lufthansa', aliases: [] },
  { slug: 'britishairways', name: 'British Airways', aliases: [] },
  { slug: 'iberia', name: 'Iberia', aliases: [] },
  { slug: 'ryanair', name: 'Ryanair', aliases: [] },
  { slug: 'easyjet', name: 'EasyJet', aliases: [] },
  { slug: 'transavia', name: 'Transavia', aliases: [] },
  { slug: 'vueling', name: 'Vueling', aliases: [] },
  { slug: 'wizzair', name: 'Wizz Air', aliases: [] },
  { slug: 'emirates', name: 'Emirates', aliases: [] },
  { slug: 'qatarairways', name: 'Qatar Airways', aliases: [] },
  { slug: 'turkishairlines', name: 'Turkish Airlines', aliases: [] },
  { slug: 'singaporeairlines', name: 'Singapore Airlines', aliases: [] },
  { slug: 'unitedairlines', name: 'United Airlines', aliases: ['United'] },
  { slug: 'americanairlines', name: 'American Airlines', aliases: [] },
  { slug: 'deltaairlines', name: 'Delta Air Lines', aliases: ['Delta'] },
  { slug: 'jetblue', name: 'JetBlue', aliases: [] },
  { slug: 'southwestairlines', name: 'Southwest Airlines', aliases: ['Southwest'] },
  { slug: 'sncf', name: 'SNCF', aliases: [] },
  { slug: 'tgv', name: 'TGV', aliases: [] },
  { slug: 'eurostar', name: 'Eurostar', aliases: [] },
  { slug: 'thalys', name: 'Thalys', aliases: [] },
  { slug: 'ratp', name: 'RATP', aliases: [] },

  // ============ HÔTELLERIE / VOYAGE ============
  { slug: 'bookingdotcom', name: 'Booking.com', aliases: ['Booking'] },
  { slug: 'expedia', name: 'Expedia', aliases: [] },
  { slug: 'tripadvisor', name: 'Tripadvisor', aliases: [] },
  { slug: 'trivago', name: 'Trivago', aliases: [] },
  { slug: 'skyscanner', name: 'Skyscanner', aliases: [] },
  { slug: 'lastminute', name: 'Lastminute.com', aliases: [] },
  { slug: 'hilton', name: 'Hilton', aliases: [] },
  { slug: 'marriott', name: 'Marriott', aliases: [] },
  { slug: 'accor', name: 'Accor', aliases: [] },
  { slug: 'ibis', name: 'Ibis', aliases: [] },
  { slug: 'mercure', name: 'Mercure', aliases: [] },
  { slug: 'sofitel', name: 'Sofitel', aliases: [] },
  { slug: 'novotel', name: 'Novotel', aliases: [] },
  { slug: 'fourseasons', name: 'Four Seasons', aliases: [] },

  // ============ TÉLÉPHONIE / FAI / OPÉRATEURS FR ============
  { slug: 'orange', name: 'Orange', aliases: [] },
  { slug: 'sfr', name: 'SFR', aliases: [] },
  { slug: 'bouyguestelecom', name: 'Bouygues Telecom', aliases: ['Bouygues'] },
  { slug: 'free', name: 'Free', aliases: [] },
  { slug: 'verizon', name: 'Verizon', aliases: [] },
  { slug: 'att', name: 'AT&T', aliases: [] },
  { slug: 'tmobile', name: 'T-Mobile', aliases: [] },
  { slug: 'vodafone', name: 'Vodafone', aliases: [] },
  { slug: 'o2', name: 'O2', aliases: [] },
  { slug: 'telefonica', name: 'Telefónica', aliases: ['Telefonica'] },

  // ============ FINANCE / BANQUE ============
  { slug: 'hsbc', name: 'HSBC', aliases: [] },
  { slug: 'santander', name: 'Santander', aliases: [] },
  { slug: 'bnpparibas', name: 'BNP Paribas', aliases: [] },
  { slug: 'societegenerale', name: 'Société Générale', aliases: ['SocGen'] },
  { slug: 'creditagricole', name: 'Crédit Agricole', aliases: [] },
  { slug: 'lcl', name: 'LCL', aliases: [] },
  { slug: 'banquepopulaire', name: 'Banque Populaire', aliases: [] },
  { slug: 'caissedepargne', name: "Caisse d'Épargne", aliases: ['Caisse Epargne'] },
  { slug: 'barclays', name: 'Barclays', aliases: [] },
  { slug: 'deutschebank', name: 'Deutsche Bank', aliases: [] },
  { slug: 'morganstanley', name: 'Morgan Stanley', aliases: [] },
  { slug: 'goldmansachs', name: 'Goldman Sachs', aliases: [] },
  { slug: 'jpmorgan', name: 'JPMorgan Chase', aliases: ['JP Morgan', 'JPMorgan'] },
  { slug: 'allianz', name: 'Allianz', aliases: [] },
  { slug: 'axa', name: 'AXA', aliases: [] },
  { slug: 'maif', name: 'Maif', aliases: ['MAIF'] },
  { slug: 'macif', name: 'Macif', aliases: ['MACIF'] },

  // ============ CRYPTO ============
  { slug: 'bitcoin', name: 'Bitcoin', aliases: [] },
  { slug: 'ethereum', name: 'Ethereum', aliases: [] },
  { slug: 'binance', name: 'Binance', aliases: [] },
  { slug: 'coinbase', name: 'Coinbase', aliases: [] },
  { slug: 'kraken', name: 'Kraken', aliases: [] },

  // ============ ENERGIE / PETROLE ============
  { slug: 'totalenergies', name: 'TotalEnergies', aliases: ['Total'] },
  { slug: 'shell', name: 'Shell', aliases: [] },
  { slug: 'bp', name: 'BP', aliases: [] },
  { slug: 'exxon', name: 'ExxonMobil', aliases: ['Exxon'] },
  { slug: 'engie', name: 'Engie', aliases: [] },
  { slug: 'edf', name: 'EDF', aliases: [] },

  // ============ MUSIQUE / LABELS ============
  { slug: 'universalmusic', name: 'Universal Music', aliases: [] },
  { slug: 'sonymusic', name: 'Sony Music', aliases: [] },
  { slug: 'warnermusic', name: 'Warner Music', aliases: [] },
  { slug: 'pandora', name: 'Pandora', aliases: [] },

  // ============ TECH DEV / FRAMEWORKS ============
  { slug: 'react', name: 'React', aliases: [] },
  { slug: 'nextdotjs', name: 'Next.js', aliases: ['NextJS'] },
  { slug: 'angular', name: 'Angular', aliases: [] },
  { slug: 'vuedotjs', name: 'Vue.js', aliases: ['Vue'] },
  { slug: 'svelte', name: 'Svelte', aliases: [] },
  { slug: 'nodedotjs', name: 'Node.js', aliases: ['NodeJS'] },
  { slug: 'python', name: 'Python', aliases: [] },
  { slug: 'java', name: 'Java', aliases: [] },
  { slug: 'javascript', name: 'JavaScript', aliases: [] },
  { slug: 'typescript', name: 'TypeScript', aliases: [] },
  { slug: 'mongodb', name: 'MongoDB', aliases: [] },
  { slug: 'postgresql', name: 'PostgreSQL', aliases: ['Postgres'] },
  { slug: 'mysql', name: 'MySQL', aliases: [] },
  { slug: 'redis', name: 'Redis', aliases: [] },
  { slug: 'elasticsearch', name: 'Elasticsearch', aliases: [] },
  { slug: 'firebase', name: 'Firebase', aliases: [] },
  { slug: 'amazonwebservices', name: 'AWS', aliases: ['Amazon Web Services'] },
  { slug: 'googlecloud', name: 'Google Cloud', aliases: [] },
  { slug: 'digitalocean', name: 'DigitalOcean', aliases: [] },
  { slug: 'heroku', name: 'Heroku', aliases: [] },

  // ============ AJOUTS — IA / LLM / SaaS ============
  { slug: 'openai', name: 'OpenAI', aliases: [] },
  { slug: 'anthropic', name: 'Anthropic', aliases: [] },
  { slug: 'huggingface', name: 'Hugging Face', aliases: [] },
  { slug: 'perplexity', name: 'Perplexity', aliases: [] },
  { slug: 'githubcopilot', name: 'GitHub Copilot', aliases: ['Copilot'] },
  { slug: 'gemini', name: 'Gemini', aliases: ['Google Gemini'] },
  { slug: 'replicate', name: 'Replicate', aliases: [] },
  { slug: 'langchain', name: 'LangChain', aliases: [] },
  { slug: 'mailchimp', name: 'Mailchimp', aliases: [] },
  { slug: 'hubspot', name: 'HubSpot', aliases: [] },
  { slug: 'intercom', name: 'Intercom', aliases: [] },
  { slug: 'zendesk', name: 'Zendesk', aliases: [] },
  { slug: 'twilio', name: 'Twilio', aliases: [] },
  { slug: 'sendgrid', name: 'SendGrid', aliases: [] },
  { slug: 'zoho', name: 'Zoho', aliases: [] },
  { slug: 'segment', name: 'Segment', aliases: [] },
  { slug: 'mixpanel', name: 'Mixpanel', aliases: [] },
  { slug: 'amplitude', name: 'Amplitude', aliases: [] },
  { slug: 'googleanalytics', name: 'Google Analytics', aliases: [] },
  { slug: 'datadog', name: 'Datadog', aliases: [] },
  { slug: 'newrelic', name: 'New Relic', aliases: [] },
  { slug: 'sentry', name: 'Sentry', aliases: [] },
  { slug: 'cloudflareworkers', name: 'Cloudflare Workers', aliases: [] },
  { slug: 'supabase', name: 'Supabase', aliases: [] },
  { slug: 'planetscale', name: 'PlanetScale', aliases: [] },
  { slug: 'render', name: 'Render', aliases: [] },
  { slug: 'flydotio', name: 'Fly.io', aliases: [] },
  { slug: 'railway', name: 'Railway', aliases: [] },

  // ============ AJOUTS — Productivity / Outils ============
  { slug: 'obsidian', name: 'Obsidian', aliases: [] },
  { slug: 'roamresearch', name: 'Roam Research', aliases: [] },
  { slug: 'monday', name: 'Monday.com', aliases: [] },
  { slug: 'clickup', name: 'ClickUp', aliases: [] },
  { slug: 'basecamp', name: 'Basecamp', aliases: [] },
  { slug: 'linear', name: 'Linear', aliases: [] },
  { slug: 'miro', name: 'Miro', aliases: [] },
  { slug: 'mural', name: 'Mural', aliases: [] },
  { slug: 'webex', name: 'Webex', aliases: [] },
  { slug: 'googlemeet', name: 'Google Meet', aliases: [] },
  { slug: 'protonmail', name: 'ProtonMail', aliases: ['Proton Mail'] },
  { slug: 'proton', name: 'Proton', aliases: [] },
  { slug: 'protonvpn', name: 'Proton VPN', aliases: [] },
  { slug: 'nordvpn', name: 'NordVPN', aliases: [] },
  { slug: 'expressvpn', name: 'ExpressVPN', aliases: [] },
  { slug: 'surfshark', name: 'Surfshark', aliases: [] },
  { slug: 'mullvad', name: 'Mullvad', aliases: [] },
  { slug: '1password', name: '1Password', aliases: [] },
  { slug: 'bitwarden', name: 'Bitwarden', aliases: [] },
  { slug: 'lastpass', name: 'LastPass', aliases: [] },
  { slug: 'dashlane', name: 'Dashlane', aliases: [] },
  { slug: 'raycast', name: 'Raycast', aliases: [] },
  { slug: 'alfred', name: 'Alfred', aliases: [] },

  // ============ AJOUTS — Streaming / Médias ============
  { slug: 'amazonprime', name: 'Amazon Prime', aliases: [] },
  { slug: 'youtubemusic', name: 'YouTube Music', aliases: [] },
  { slug: 'audible', name: 'Audible', aliases: [] },
  { slug: 'amazonkindle', name: 'Kindle', aliases: ['Amazon Kindle'] },
  { slug: 'kobo', name: 'Kobo', aliases: [] },
  { slug: 'scribd', name: 'Scribd', aliases: [] },
  { slug: 'wattpad', name: 'Wattpad', aliases: [] },
  { slug: 'goodreads', name: 'Goodreads', aliases: [] },
  { slug: 'letterboxd', name: 'Letterboxd', aliases: [] },
  { slug: 'tidal', name: 'Tidal', aliases: [] },
  { slug: 'bandcamp', name: 'Bandcamp', aliases: [] },
  { slug: 'mixcloud', name: 'Mixcloud', aliases: [] },
  { slug: 'beatport', name: 'Beatport', aliases: [] },
  { slug: 'hbomax', name: 'HBO Max', aliases: ['Max'] },
  { slug: 'peacock', name: 'Peacock', aliases: [] },
  { slug: 'hulu', name: 'Hulu', aliases: [] },

  // ============ AJOUTS — Réseaux sociaux ============
  { slug: 'wechat', name: 'WeChat', aliases: [] },
  { slug: 'line', name: 'LINE', aliases: [] },
  { slug: 'kakaotalk', name: 'KakaoTalk', aliases: [] },
  { slug: 'viber', name: 'Viber', aliases: [] },
  { slug: 'weibo', name: 'Weibo', aliases: [] },
  { slug: 'flickr', name: 'Flickr', aliases: [] },
  { slug: 'foursquare', name: 'Foursquare', aliases: [] },
  { slug: 'yelp', name: 'Yelp', aliases: [] },
  { slug: 'tripadvisor', name: 'Tripadvisor', aliases: [] },
  { slug: 'unsplash', name: 'Unsplash', aliases: [] },
  { slug: 'pexels', name: 'Pexels', aliases: [] },
  { slug: 'dribbble', name: 'Dribbble', aliases: [] },
  { slug: 'behance', name: 'Behance', aliases: [] },
  { slug: 'deviantart', name: 'DeviantArt', aliases: [] },
  { slug: 'artstation', name: 'ArtStation', aliases: [] },
  { slug: 'linktree', name: 'Linktree', aliases: [] },

  // ============ AJOUTS — Hardware / Gaming ============
  { slug: 'oculus', name: 'Oculus', aliases: ['Meta Quest'] },
  { slug: 'steamdeck', name: 'Steam Deck', aliases: [] },
  { slug: 'raspberrypi', name: 'Raspberry Pi', aliases: [] },
  { slug: 'arduino', name: 'Arduino', aliases: [] },
  { slug: 'fujifilm', name: 'Fujifilm', aliases: [] },
  { slug: 'gopro', name: 'GoPro', aliases: [] },

  // ============ AJOUTS — Browsers / Search ============
  { slug: 'yahoo', name: 'Yahoo', aliases: [] },
  { slug: 'baidu', name: 'Baidu', aliases: [] },
  { slug: 'yandex', name: 'Yandex', aliases: [] },
  { slug: 'arc', name: 'Arc', aliases: ['Arc Browser'] },
  { slug: 'vivaldi', name: 'Vivaldi', aliases: [] },

  // ============ AJOUTS — Apprentissage / MOOCs ============
  { slug: 'coursera', name: 'Coursera', aliases: [] },
  { slug: 'udemy', name: 'Udemy', aliases: [] },
  { slug: 'skillshare', name: 'Skillshare', aliases: [] },
  { slug: 'codecademy', name: 'Codecademy', aliases: [] },
  { slug: 'freecodecamp', name: 'freeCodeCamp', aliases: [] },
  { slug: 'edx', name: 'edX', aliases: [] },
  { slug: 'khanacademy', name: 'Khan Academy', aliases: [] },
  { slug: 'babbel', name: 'Babbel', aliases: [] },

  // ============ AJOUTS — Webdev / Frameworks ============
  { slug: 'tailwindcss', name: 'Tailwind CSS', aliases: ['Tailwind'] },
  { slug: 'bootstrap', name: 'Bootstrap', aliases: [] },
  { slug: 'mui', name: 'Material UI', aliases: ['MUI'] },
  { slug: 'antdesign', name: 'Ant Design', aliases: [] },
  { slug: 'astro', name: 'Astro', aliases: [] },
  { slug: 'remix', name: 'Remix', aliases: [] },
  { slug: 'nuxtdotjs', name: 'Nuxt', aliases: ['Nuxt.js'] },
  { slug: 'svelte', name: 'Svelte', aliases: [] },
  { slug: 'sveltekit', name: 'SvelteKit', aliases: [] },
  { slug: 'qwik', name: 'Qwik', aliases: [] },
  { slug: 'solid', name: 'SolidJS', aliases: [] },
  { slug: 'webpack', name: 'webpack', aliases: [] },
  { slug: 'vite', name: 'Vite', aliases: [] },
  { slug: 'esbuild', name: 'esbuild', aliases: [] },
  { slug: 'prettier', name: 'Prettier', aliases: [] },
  { slug: 'eslint', name: 'ESLint', aliases: [] },
  { slug: 'prisma', name: 'Prisma', aliases: [] },
  { slug: 'graphql', name: 'GraphQL', aliases: [] },
  { slug: 'jest', name: 'Jest', aliases: [] },
  { slug: 'cypress', name: 'Cypress', aliases: [] },
  { slug: 'playwright', name: 'Playwright', aliases: [] },
  { slug: 'storybook', name: 'Storybook', aliases: [] },
  { slug: 'threedotjs', name: 'Three.js', aliases: [] },

  // ============ AJOUTS — Outils créatifs / SaaS designers ============
  { slug: 'framer', name: 'Framer', aliases: [] },
  { slug: 'webflow', name: 'Webflow', aliases: [] },
  { slug: 'wix', name: 'Wix', aliases: [] },
  { slug: 'squarespace', name: 'Squarespace', aliases: [] },
  { slug: 'godaddy', name: 'GoDaddy', aliases: [] },
  { slug: 'inkscape', name: 'Inkscape', aliases: [] },
  { slug: 'gimp', name: 'GIMP', aliases: [] },
  { slug: 'krita', name: 'Krita', aliases: [] },
  { slug: 'audacity', name: 'Audacity', aliases: [] },
  { slug: 'libreoffice', name: 'LibreOffice', aliases: [] },
  { slug: 'vlcmediaplayer', name: 'VLC', aliases: ['VLC media player'] },
  { slug: 'thunderbird', name: 'Thunderbird', aliases: [] },

  // ============ AJOUTS — Éditeurs de code ============
  { slug: 'visualstudiocode', name: 'VS Code', aliases: ['Visual Studio Code'] },
  { slug: 'visualstudio', name: 'Visual Studio', aliases: [] },
  { slug: 'intellijidea', name: 'IntelliJ IDEA', aliases: [] },
  { slug: 'pycharm', name: 'PyCharm', aliases: [] },
  { slug: 'webstorm', name: 'WebStorm', aliases: [] },
  { slug: 'sublimetext', name: 'Sublime Text', aliases: [] },
  { slug: 'vim', name: 'Vim', aliases: [] },
  { slug: 'neovim', name: 'Neovim', aliases: [] },
  { slug: 'emacs', name: 'Emacs', aliases: [] },

  // ============ AJOUTS — Audio / Visio ============
  { slug: 'pandora', name: 'Pandora', aliases: [] },

  // ============ AJOUTS — Sports / Fédérations ============
  { slug: 'uefa', name: 'UEFA', aliases: [] },
  { slug: 'fifa', name: 'FIFA', aliases: [] },
  { slug: 'olympics', name: 'Jeux Olympiques', aliases: ['Olympics'] },
  { slug: 'nba', name: 'NBA', aliases: [] },
  { slug: 'nfl', name: 'NFL', aliases: [] },
  { slug: 'mlb', name: 'MLB', aliases: [] },
  { slug: 'formula1', name: 'Formule 1', aliases: ['F1', 'Formula 1'] },
  { slug: 'tourdefrance', name: 'Tour de France', aliases: [] },
  { slug: 'wimbledon', name: 'Wimbledon', aliases: [] },

  // ============ AJOUTS — Misc consumer ============
  { slug: 'nintendoswitch', name: 'Nintendo Switch', aliases: [] },
  { slug: 'lego', name: 'Lego', aliases: ['LEGO'] },

  // ============ AJOUTS Vague 2 — Non-tech consumer (compense les wordmarks bloqués) ============
  // Sportswear / Fashion (logos iconiques)
  { slug: 'jordan', name: 'Air Jordan', aliases: ['Jordan'] },
  { slug: 'crocs', name: 'Crocs', aliases: [] },
  { slug: 'skechers', name: 'Skechers', aliases: [] },
  { slug: 'timberland', name: 'Timberland', aliases: [] },
  { slug: 'umbro', name: 'Umbro', aliases: [] },
  { slug: 'mizuno', name: 'Mizuno', aliases: [] },
  // Cosmétique / Hygiène
  { slug: 'nivea', name: 'Nivea', aliases: [] },
  { slug: 'dove', name: 'Dove', aliases: [] },
  { slug: 'olay', name: 'Olay', aliases: [] },
  { slug: 'neutrogena', name: 'Neutrogena', aliases: [] },
  { slug: 'gillette', name: 'Gillette', aliases: [] },
  { slug: 'oralb', name: 'Oral-B', aliases: [] },
  { slug: 'colgate', name: 'Colgate', aliases: [] },
  { slug: 'sensodyne', name: 'Sensodyne', aliases: [] },
  { slug: 'listerine', name: 'Listerine', aliases: [] },
  { slug: 'pampers', name: 'Pampers', aliases: [] },
  { slug: 'duracell', name: 'Duracell', aliases: [] },
  { slug: 'energizer', name: 'Energizer', aliases: [] },
  // Alimentation / Boissons
  { slug: 'drpepper', name: 'Dr Pepper', aliases: [] },
  { slug: 'mountaindew', name: 'Mountain Dew', aliases: [] },
  { slug: 'gatorade', name: 'Gatorade', aliases: [] },
  { slug: 'powerade', name: 'Powerade', aliases: [] },
  { slug: 'tropicana', name: 'Tropicana', aliases: [] },
  { slug: 'campbells', name: "Campbell's", aliases: ['Campbell'] },
  { slug: 'mcvities', name: "McVitie's", aliases: [] },
  { slug: 'tictac', name: 'Tic Tac', aliases: [] },
  { slug: 'mars', name: 'Mars', aliases: [] },
  { slug: 'kelloggs', name: "Kellogg's", aliases: ['Kellogg'] },
  // Café / Thé
  { slug: 'nespresso', name: 'Nespresso', aliases: [] },
  { slug: 'illycaffe', name: 'illy', aliases: [] },
  { slug: 'lavazza', name: 'Lavazza', aliases: [] },
  { slug: 'twinings', name: 'Twinings', aliases: [] },
  // Bière / Spiritueux
  { slug: 'tuborg', name: 'Tuborg', aliases: [] },
  { slug: 'asahi', name: 'Asahi', aliases: [] },
  { slug: 'sapporo', name: 'Sapporo', aliases: [] },
  { slug: 'tigerbeer', name: 'Tiger Beer', aliases: [] },
  { slug: 'paulaner', name: 'Paulaner', aliases: [] },
  // Restauration
  { slug: 'fiveguys', name: 'Five Guys', aliases: [] },
  { slug: 'panerabread', name: 'Panera', aliases: ['Panera Bread'] },
  { slug: 'shakeshack', name: 'Shake Shack', aliases: [] },
  { slug: 'innout', name: 'In-N-Out', aliases: ['In-N-Out Burger'] },
  { slug: 'popeyes', name: 'Popeyes', aliases: [] },
  // Hôtellerie
  { slug: 'hyatt', name: 'Hyatt', aliases: [] },
  { slug: 'wyndham', name: 'Wyndham', aliases: [] },
  { slug: 'choicehotels', name: 'Choice Hotels', aliases: [] },
  { slug: 'holidayinn', name: 'Holiday Inn', aliases: [] },
  { slug: 'radissonhotels', name: 'Radisson', aliases: [] },
  // Voyage / Compagnies aériennes
  { slug: 'koreanair', name: 'Korean Air', aliases: [] },
  { slug: 'cathaypacific', name: 'Cathay Pacific', aliases: [] },
  { slug: 'ana', name: 'ANA', aliases: ['All Nippon Airways'] },
  { slug: 'jal', name: 'Japan Airlines', aliases: ['JAL'] },
  { slug: 'etihadairways', name: 'Etihad Airways', aliases: [] },
  // Automobile (logos iconiques non-wordmark)
  { slug: 'rivian', name: 'Rivian', aliases: [] },
  { slug: 'pagani', name: 'Pagani', aliases: [] },
  { slug: 'koenigsegg', name: 'Koenigsegg', aliases: [] },
  { slug: 'mercedesamg', name: 'Mercedes AMG', aliases: ['AMG'] },
  // Pneumatiques (en plus de Michelin)
  { slug: 'continental', name: 'Continental', aliases: [] },
  // Énergie
  { slug: 'aramco', name: 'Aramco', aliases: ['Saudi Aramco'] },
  { slug: 'gazprom', name: 'Gazprom', aliases: [] },
  // Médias / Cinéma
  { slug: 'pixar', name: 'Pixar', aliases: [] },
  { slug: 'sonypictures', name: 'Sony Pictures', aliases: [] },
  { slug: 'universal', name: 'Universal Pictures', aliases: ['Universal Studios'] },
  { slug: 'lionsgate', name: 'Lionsgate', aliases: [] },
  { slug: 'a24', name: 'A24', aliases: [] },
  // Stylos / Papeterie
  { slug: 'bic', name: 'Bic', aliases: ['BIC'] },
  { slug: 'zippo', name: 'Zippo', aliases: [] },
  { slug: 'parker', name: 'Parker', aliases: [] },
  { slug: 'montblanc', name: 'Montblanc', aliases: [] },
  // Loisirs / Jouets
  { slug: 'mattel', name: 'Mattel', aliases: [] },
  { slug: 'hasbro', name: 'Hasbro', aliases: [] },
  { slug: 'rubikscube', name: "Rubik's Cube", aliases: [] },
  { slug: 'monopoly', name: 'Monopoly', aliases: [] },
  // Sport / Fédérations (essais)
  { slug: 'nbaesports', name: 'NBA Esports', aliases: ['NBA'] },
  { slug: 'wwe', name: 'WWE', aliases: [] },
  { slug: 'rolandgarros', name: 'Roland-Garros', aliases: ['Roland Garros'] },
  // Outdoor / Camping
  { slug: 'columbiabank', name: 'Columbia', aliases: [] },
  { slug: 'rei', name: 'REI', aliases: [] },
  // Photo
  { slug: 'polaroid', name: 'Polaroid', aliases: [] },
  // Banque / Carte
  { slug: 'discover', name: 'Discover', aliases: [] },
  { slug: 'unionpay', name: 'UnionPay', aliases: [] },
  // Marques d'horlogerie
  { slug: 'seiko', name: 'Seiko', aliases: [] },
  { slug: 'citizen', name: 'Citizen', aliases: [] },

  // ============ AJOUTS BIS — Logos iconiques (anti-wordmark) ============
  // Langages / runtimes — chacun a un logo iconique
  { slug: 'kotlin', name: 'Kotlin', aliases: [] },
  { slug: 'rust', name: 'Rust', aliases: [] },
  { slug: 'go', name: 'Go', aliases: ['Golang'] },
  { slug: 'haskell', name: 'Haskell', aliases: [] },
  { slug: 'elixir', name: 'Elixir', aliases: [] },
  { slug: 'ruby', name: 'Ruby', aliases: [] },
  { slug: 'rubyonrails', name: 'Ruby on Rails', aliases: ['Rails'] },
  { slug: 'swift', name: 'Swift', aliases: [] },
  { slug: 'scala', name: 'Scala', aliases: [] },
  { slug: 'dart', name: 'Dart', aliases: [] },
  { slug: 'flutter', name: 'Flutter', aliases: [] },
  { slug: 'php', name: 'PHP', aliases: [] },
  { slug: 'csharp', name: 'C#', aliases: [] },
  { slug: 'cplusplus', name: 'C++', aliases: [] },
  { slug: 'perl', name: 'Perl', aliases: [] },
  { slug: 'lua', name: 'Lua', aliases: [] },
  // Frameworks back-end
  { slug: 'django', name: 'Django', aliases: [] },
  { slug: 'flask', name: 'Flask', aliases: [] },
  { slug: 'fastapi', name: 'FastAPI', aliases: [] },
  { slug: 'nestjs', name: 'NestJS', aliases: [] },
  { slug: 'spring', name: 'Spring', aliases: [] },
  { slug: 'laravel', name: 'Laravel', aliases: [] },
  { slug: 'symfony', name: 'Symfony', aliases: [] },
  { slug: 'expressjs', name: 'Express.js', aliases: [] },
  // Bases de données / data
  { slug: 'sqlite', name: 'SQLite', aliases: [] },
  { slug: 'mariadb', name: 'MariaDB', aliases: [] },
  { slug: 'neo4j', name: 'Neo4j', aliases: [] },
  { slug: 'apachecassandra', name: 'Cassandra', aliases: [] },
  { slug: 'apachekafka', name: 'Kafka', aliases: [] },
  { slug: 'rabbitmq', name: 'RabbitMQ', aliases: [] },
  { slug: 'apachespark', name: 'Apache Spark', aliases: [] },
  { slug: 'apacheairflow', name: 'Airflow', aliases: [] },
  { slug: 'duckdb', name: 'DuckDB', aliases: [] },
  // DevOps / IaC
  { slug: 'terraform', name: 'Terraform', aliases: [] },
  { slug: 'ansible', name: 'Ansible', aliases: [] },
  { slug: 'circleci', name: 'CircleCI', aliases: [] },
  { slug: 'travisci', name: 'Travis CI', aliases: [] },
  { slug: 'jenkins', name: 'Jenkins', aliases: [] },
  { slug: 'gradle', name: 'Gradle', aliases: [] },
  { slug: 'prometheus', name: 'Prometheus', aliases: [] },
  { slug: 'grafana', name: 'Grafana', aliases: [] },
  { slug: 'splunk', name: 'Splunk', aliases: [] },
  { slug: 'pagerduty', name: 'PagerDuty', aliases: [] },
  // Observabilité / API
  { slug: 'postman', name: 'Postman', aliases: [] },
  { slug: 'swagger', name: 'Swagger', aliases: [] },
  { slug: 'apollographql', name: 'Apollo GraphQL', aliases: [] },
  { slug: 'graphql', name: 'GraphQL', aliases: [] },
  // ML / IA / Data
  { slug: 'pytorch', name: 'PyTorch', aliases: [] },
  { slug: 'tensorflow', name: 'TensorFlow', aliases: [] },
  { slug: 'keras', name: 'Keras', aliases: [] },
  { slug: 'scikitlearn', name: 'scikit-learn', aliases: [] },
  { slug: 'jupyter', name: 'Jupyter', aliases: [] },
  { slug: 'anaconda', name: 'Anaconda', aliases: [] },
  { slug: 'kaggle', name: 'Kaggle', aliases: [] },
  { slug: 'pandas', name: 'pandas', aliases: [] },
  { slug: 'numpy', name: 'NumPy', aliases: [] },
  { slug: 'matplotlib', name: 'Matplotlib', aliases: [] },
  // Crypto / blockchain — la plupart sont des icônes
  { slug: 'litecoin', name: 'Litecoin', aliases: [] },
  { slug: 'dogecoin', name: 'Dogecoin', aliases: [] },
  { slug: 'ripple', name: 'Ripple', aliases: ['XRP'] },
  { slug: 'monero', name: 'Monero', aliases: [] },
  { slug: 'cardano', name: 'Cardano', aliases: [] },
  { slug: 'polkadot', name: 'Polkadot', aliases: [] },
  { slug: 'solana', name: 'Solana', aliases: [] },
  { slug: 'chainlink', name: 'Chainlink', aliases: [] },
  { slug: 'tether', name: 'Tether', aliases: ['USDT'] },
  // Fintech / paiement
  { slug: 'klarna', name: 'Klarna', aliases: [] },
  { slug: 'afterpay', name: 'Afterpay', aliases: [] },
  { slug: 'robinhood', name: 'Robinhood', aliases: [] },
  { slug: 'etoro', name: 'eToro', aliases: [] },
  // Hardware gaming / ergonomie
  { slug: 'corsair', name: 'Corsair', aliases: [] },
  { slug: 'alienware', name: 'Alienware', aliases: [] },
  { slug: 'hyperx', name: 'HyperX', aliases: [] },
  { slug: 'steelseries', name: 'SteelSeries', aliases: [] },
  // Game studios
  { slug: 'godotengine', name: 'Godot', aliases: [] },
  { slug: 'mihoyo', name: 'miHoYo', aliases: [] },
  { slug: 'mojang', name: 'Mojang', aliases: [] },
  { slug: 'gog', name: 'GOG', aliases: [] },
  { slug: 'humblebundle', name: 'Humble Bundle', aliases: [] },
  { slug: 'itchdotio', name: 'itch.io', aliases: [] },
  // Apps / Marketplace
  { slug: 'gumroad', name: 'Gumroad', aliases: [] },
  { slug: 'producthunt', name: 'Product Hunt', aliases: [] },
  { slug: 'kickstarter', name: 'Kickstarter', aliases: [] },
  { slug: 'gofundme', name: 'GoFundMe', aliases: [] },
  { slug: 'indiegogo', name: 'Indiegogo', aliases: [] },
  { slug: 'opensea', name: 'OpenSea', aliases: [] },
  // FoodTech
  { slug: 'zomato', name: 'Zomato', aliases: [] },
  { slug: 'swiggy', name: 'Swiggy', aliases: [] },
  { slug: 'grubhub', name: 'Grubhub', aliases: [] },
  { slug: 'instacart', name: 'Instacart', aliases: [] },
  // Comms / Collab
  { slug: 'mattermost', name: 'Mattermost', aliases: [] },
  { slug: 'rocketdotchat', name: 'Rocket.Chat', aliases: [] },
  { slug: 'jitsi', name: 'Jitsi', aliases: [] },
  // Transport / Mobilité
  { slug: 'metro', name: 'Metro', aliases: [] },
  // Assurances / Banque
  { slug: 'monzo', name: 'Monzo', aliases: [] },
  { slug: 'starlingbank', name: 'Starling Bank', aliases: [] },
  // Misc
  { slug: 'vk', name: 'VK', aliases: ['VKontakte'] },
  { slug: 'flipboard', name: 'Flipboard', aliases: [] },
];
