/**
 * Helpers pour la question Quiz CEO `brand-logo`.
 *
 * Source de vérité : `lib/quizCeo/brands.ts` (catalogue de ~600 marques).
 * Les SVG sont sous `public/brand-logos/<slug>.svg` (téléchargés une fois
 * via `npm run download:brand-logos`). Toutes les marques de `BRANDS` ne
 * sont PAS forcément présentes en physique : simple-icons ne couvre pas
 * tout (luxe, presse FR…). On filtre donc côté serveur via `existsSync`
 * pour ne piocher que des marques dont le SVG existe.
 *
 * On filtre AUSSI les **wordmarks** (logos = nom de la marque écrit en
 * lettres stylisées) qui rendent le quiz trivial : voir `WORDMARK_BLOCKLIST`.
 */

import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { BRANDS, type BrandEntry } from './brands';

/**
 * Slugs simple-icons dont le logo se confond avec le nom de la marque
 * (= juste « ACER » écrit, juste « FedEx » écrit, etc.). Ces logos rendent
 * la question triviale donc on les exclut du tirage. Liste curatée à la
 * main — à étendre quand on tombe sur d'autres cas en jeu.
 */
const WORDMARK_BLOCKLIST = new Set<string>([
  'acer',
  'activision',
  'amd',
  'asus',
  'att',
  'audible',
  'baidu',
  'bandainamco',
  'bandcamp',
  'beatport',
  'behance',
  'bose',
  'canon',
  'capcom',
  'casio',
  'cnn',
  'dell',
  'doordash',
  'doritos',
  'dunkin',
  'ea',
  'ebay',
  'edx',
  'emirates',
  'etsy',
  'evernote',
  'expedia',
  'exxon',
  'fanta',
  'fedex',
  'fila',
  'forbes',
  'foursquare',
  'foxnews',
  'fujifilm',
  'gopro',
  'hbo',
  'hbomax',
  'hp',
  'huawei',
  'hubspot',
  'ibm',
  'intel',
  'jpmorgan',
  'kfc',
  'kia',
  'lego',
  'lenovo',
  'lg',
  'lidl',
  'lipton',
  'mango',
  'marvel',
  'maybelline',
  'msi',
  'nationalgeographic',
  'nestle',
  'netflix',
  'nokia',
  'nvidia',
  'oracle',
  'panasonic',
  'paramountplus',
  'paypal',
  'perplexity',
  'philips',
  'pirelli',
  'reebok',
  'reuters',
  'rolex',
  'samsung',
  'sap',
  'sega',
  'sephora',
  'shein',
  'siemens',
  'sony',
  'subway',
  'temu',
  'theguardian',
  'thenewyorktimes',
  'tmobile',
  'tommyhilfiger',
  'toshiba',
  'udemy',
  'uefa',
  'uniqlo',
  'ups',
  'verizon',
  'vimeo',
  'visa',
  'vodafone',
  'walmart',
  'wattpad',
  'wikipedia',
  'yahoo',
  'yelp',
  'zalando',
  'zara',
  'zendesk',
  // Compagnies aériennes / transport — texte uniquement
  'airfrance',
  'britishairways',
  'klm',
  'lufthansa',
  'easyjet',
  'ryanair',
  'iberia',
  'wizzair',
  'transavia',
  'jetblue',
  'eurostar',
  'thalys',
  'sncf',
  // Banques FR — texte
  'bnpparibas',
  'lcl',
  'banquepopulaire',
  'caissedepargne',
  // Téléphonie — texte
  'sfr',
  'bouyguestelecom',
  'free',
  // Distribution FR — texte uniquement
  'auchan',
  'leclerc',
  'monoprix',
  'casino',
  'fnac',
  'darty',
  'boulanger',
  'castorama',
  // E-commerce — texte uniquement
  'aliexpress',
  'alibaba',
  'cdiscount',
  'leboncoin',
  'backmarket',
  'asos',
  // Voyage — texte
  'bookingdotcom',
  'trivago',
  'skyscanner',
  'lastminute',
  // Médias FR — texte
  'lemonde',
  'lefigaro',
  'liberation',
  'lequipe',
  'mediapart',
  'leparisien',
  // Énergie — texte
  'totalenergies',
  'engie',
  'edf',
  // Restauration — texte
  'krispykreme',
  'pizzahut',
  'subway',
  'chickfila',
  'corona',
  'budweiser',
  'kronenbourg',
  'jameson',
  'absolutvodka',
  'baileys',
  // Mode — texte uniquement
  'kappa',
  'asics',
  'hugoboss',
  'tommyhilfiger',
  'diesel',
  'dyson',
  'bosch',
  'dewalt',
  'makita',
  'stanley',
  // Alimentaire — texte
  'kelloggs',
  'heinz',
  'haribo',
  'kitkat',
  'snickers',
  'twix',
  'lindt',
  'milka',
  'ferrero',
  'cadbury',
  'mars',
  'orangina',
  'schweppes',
  'innocent',
  'nesquik',
  'lipton',
  'evian',
  'volvic',
  'perrier',
  'sanpellegrino',
  'badoit',
  'lays',
  // SaaS / autres — wordmark texte
  'stripe',
  // ============ Vague 2 (vérification visuelle utilisateur) ============
  'adobeaftereffects',
  'adobeillustrator',
  'adobelightroom',
  'aldinord',
  'alfaromeo',
  'amazonprime',
  'amazonwebservices',
  'americanexpress',
  'arm',
  'astonmartin',
  'bbc',
  'bereal',
  'bmw',
  'burgerking',
  'canva',
  'cocacola',
  'coinbase',
  'dhl',
  'dior',
  'ducati',
  'epicgames',
  'fiat',
  'fifa',
  'ford',
  'go',
  'goldmansachs',
  'grubhub',
  'hilton',
  'hulu',
  'ikea',
  'imdb',
  'intermarche',
  'ios',
  'jaguar',
  'jbl',
  'kaggle',
  'kakaotalk',
  'konami',
  'ktm',
  'landrover',
  'leica',
  'leroymerlin',
  'line',
  'lua',
  'lyft',
  'mihoyo',
  'minecraft',
  'mini',
  'mysql',
  'n26',
  'nikon',
  'nintendo',
  'nissan',
  'nodedotjs',
  'oppo',
  'peugeot',
  'php',
  'pokemon',
  'porsche',
  'primevideo',
  'scikitlearn',
  'skillshare',
  'splunk',
  'tesco',
  'thenorthface',
  'uber',
  'ubereats',
  'vespa',
  'vim',
  'volvo',
  'wix',
  'yandex',
  'zoho',
  'zomato',
  'zoom',
  // ============ Vague 3 (vérification visuelle utilisateur) ============
  'ana',
  'discover',
  'dji',
  'etihadairways',
  'jeep',
]);

/** URL publique servie par Next.js depuis `public/brand-logos/`. */
export function getBrandLogoPath(slug: string): string {
  return `/brand-logos/${slug}.svg`;
}

/**
 * Liste des marques dont le SVG existe réellement sur le disque ET dont le
 * logo n'est pas un wordmark. À appeler uniquement côté serveur (utilise `fs`).
 */
export function getAvailableBrands(): BrandEntry[] {
  const dir = join(process.cwd(), 'public', 'brand-logos');
  return BRANDS.filter(
    (b) =>
      !WORDMARK_BLOCKLIST.has(b.slug) &&
      existsSync(join(dir, `${b.slug}.svg`)),
  );
}

export { BRANDS, WORDMARK_BLOCKLIST };
export type { BrandEntry };
