/**
 * Catalogue de devises nationales pour la question Quiz CEO `country-motto`.
 *
 *   - `motto`     : texte de la devise (langue d'origine + traduction française si exotique)
 *   - `countryId` : code ISO 3166-1 alpha-2 (résolu via `lib/quizCeo/allCountries.ts`
 *                   pour récupérer le nom canonique + aliases)
 *
 * 200 entrées : 75 EASY (pays + devises iconiques en France) + 75 MEDIUM
 * (pays connus mais devises moins évidentes) + 50 HARD (pays moins connus,
 * devises latines/exotiques).
 *
 * Source de vérité runtime = la DB. Hotfix possible par UPDATE direct.
 */

export interface CountryMottoEntry {
  motto: string;
  countryId: string; // ISO2 minuscule, doit exister dans allCountries.ts
}

export const COUNTRY_MOTTOS_EASY: CountryMottoEntry[] = [
  { motto: 'Liberté, Égalité, Fraternité', countryId: 'fr' },
  { motto: 'In God We Trust', countryId: 'us' },
  { motto: 'E Pluribus Unum', countryId: 'us' },
  { motto: 'Dieu et mon droit', countryId: 'gb' },
  { motto: 'Einigkeit und Recht und Freiheit', countryId: 'de' },
  { motto: 'Unité, Justice et Liberté', countryId: 'de' },
  { motto: 'L\'union fait la force', countryId: 'be' },
  { motto: 'Eendracht maakt macht', countryId: 'be' },
  { motto: 'Plus Ultra', countryId: 'es' },
  { motto: 'Ordem e Progresso', countryId: 'br' },
  { motto: 'Ordre et Progrès', countryId: 'br' },
  { motto: 'A Mari Usque Ad Mare', countryId: 'ca' },
  { motto: 'D\'un océan à l\'autre', countryId: 'ca' },
  { motto: 'Je maintiendrai', countryId: 'nl' },
  { motto: 'Unus pro omnibus, omnes pro uno', countryId: 'ch' },
  { motto: 'Un pour tous, tous pour un', countryId: 'ch' },
  { motto: 'Bhinneka Tunggal Ika', countryId: 'id' },
  { motto: 'Unité dans la diversité', countryId: 'id' },
  { motto: 'Satyameva Jayate', countryId: 'in' },
  { motto: 'Seule la vérité triomphe', countryId: 'in' },
  { motto: 'En unión y libertad', countryId: 'ar' },
  { motto: 'En union et liberté', countryId: 'ar' },
  { motto: 'Por la razón o la fuerza', countryId: 'cl' },
  { motto: 'Par la raison ou par la force', countryId: 'cl' },
  { motto: 'Patria o Muerte', countryId: 'cu' },
  { motto: 'Patrie ou mort', countryId: 'cu' },
  { motto: 'Libertad y Orden', countryId: 'co' },
  { motto: 'Liberté et Ordre', countryId: 'co' },
  { motto: 'Bóg, Honor, Ojczyzna', countryId: 'pl' },
  { motto: 'Dieu, Honneur, Patrie', countryId: 'pl' },
  { motto: 'Độc lập – Tự do – Hạnh phúc', countryId: 'vn' },
  { motto: 'Indépendance, Liberté, Bonheur', countryId: 'vn' },
  { motto: 'Pravda vítězí', countryId: 'cz' },
  { motto: 'La vérité l\'emporte', countryId: 'cz' },
  { motto: 'Nihil sine Deo', countryId: 'ro' },
  { motto: 'Rien sans Dieu', countryId: 'ro' },
  { motto: 'الله، الوطن، الملك', countryId: 'ma' },
  { motto: 'Dieu, la Patrie, le Roi', countryId: 'ma' },
  { motto: 'Out of Many, One People', countryId: 'jm' },
  { motto: 'D\'un grand nombre, un seul peuple', countryId: 'jm' },
  { motto: 'Libertas', countryId: 'sm' },
  { motto: 'Deo Juvante', countryId: 'mc' },
  { motto: 'Avec l\'aide de Dieu', countryId: 'mc' },
  { motto: 'Mir wëlle bleiwe wat mir sinn', countryId: 'lu' },
  { motto: 'Nous voulons rester ce que nous sommes', countryId: 'lu' },
  { motto: 'Majulah Singapura', countryId: 'sg' },
  { motto: 'En avant, Singapour', countryId: 'sg' },
  { motto: 'For God and My Country', countryId: 'ug' },
  { motto: 'Pour Dieu et mon pays', countryId: 'ug' },
  { motto: 'Unity and Faith, Peace and Progress', countryId: 'ng' },
  { motto: 'Un peuple, un but, une foi', countryId: 'sn' },
  { motto: 'Un peuple, un but, une foi', countryId: 'ml' },
  { motto: 'Travail, Liberté, Patrie', countryId: 'tg' },
  { motto: 'Unité, Travail, Progrès', countryId: 'td' },
  { motto: 'Unité, Progrès, Justice', countryId: 'bf' },
  { motto: 'Fraternité, Travail, Progrès', countryId: 'ne' },
  { motto: 'Honneur, Fraternité, Justice', countryId: 'mr' },
  { motto: 'Travail, Justice, Solidarité', countryId: 'gn' },
  { motto: 'Union, Discipline, Travail', countryId: 'ci' },
  { motto: 'Union, Travail, Justice', countryId: 'ga' },
  { motto: 'Justice, Paix, Travail', countryId: 'cd' },
  { motto: 'Unité, Travail, Progrès', countryId: 'cg' },
  { motto: 'Unité, Dignité, Travail', countryId: 'cf' },
  { motto: 'Uhuru na Umoja', countryId: 'tz' },
  { motto: 'Liberté et Unité', countryId: 'tz' },
  { motto: 'Harambee', countryId: 'ke' },
  { motto: 'Pula!', countryId: 'bw' },
  { motto: 'One Zambia, One Nation', countryId: 'zm' },
  { motto: 'Unity, Freedom, Justice', countryId: 'sl' },
  { motto: 'Unity, Liberty, Justice', countryId: 'na' },
  { motto: 'Freedom and Justice', countryId: 'gh' },
  { motto: 'The Love of Liberty Brought Us Here', countryId: 'lr' },
  { motto: 'Unity, Freedom, Work', countryId: 'zw' },
  { motto: 'Liberté ou la mort', countryId: 'gr' },
  { motto: 'Ελευθερία ή θάνατος', countryId: 'gr' },
  { motto: 'Unidade, Disciplina, Trabalho', countryId: 'st' },
];

export const COUNTRY_MOTTOS_MEDIUM: CountryMottoEntry[] = [
  { motto: 'Pro Mundi Beneficio', countryId: 'pa' },
  { motto: 'Pour le bénéfice du monde', countryId: 'pa' },
  { motto: 'Justitia, Pietas, Fides', countryId: 'sr' },
  { motto: 'Justice, Piété, Foi', countryId: 'sr' },
  { motto: 'Pax et Justitia', countryId: 'vc' },
  { motto: 'Paix et Justice', countryId: 'vc' },
  { motto: 'Stella Clavisque Maris Indici', countryId: 'mu' },
  { motto: 'Étoile et clé de l\'océan Indien', countryId: 'mu' },
  { motto: 'Finis Coronat Opus', countryId: 'sc' },
  { motto: 'La fin couronne l\'œuvre', countryId: 'sc' },
  { motto: 'Virtute et Constantia', countryId: 'mt' },
  { motto: 'Avec courage et constance', countryId: 'mt' },
  { motto: 'Vienybė težydi', countryId: 'lt' },
  { motto: 'Que l\'unité s\'épanouisse', countryId: 'lt' },
  { motto: 'Limba Noastră-i o Comoară', countryId: 'md' },
  { motto: 'Notre langue est un trésor', countryId: 'md' },
  { motto: 'Für Gott, Fürst und Vaterland', countryId: 'li' },
  { motto: 'Pour Dieu, le Prince et la Patrie', countryId: 'li' },
  { motto: 'Tanindrazana, Fahafahana, Fandrosoana', countryId: 'mg' },
  { motto: 'Patrie, Liberté, Progrès', countryId: 'mg' },
  { motto: 'Khotso, Pula, Nala', countryId: 'ls' },
  { motto: 'Paix, Pluie, Prospérité', countryId: 'ls' },
  { motto: 'Siyinqaba', countryId: 'sz' },
  { motto: 'Nous sommes le rocher', countryId: 'sz' },
  { motto: 'Long God Yumi Stanap', countryId: 'vu' },
  { motto: 'Tuvalu mo te Atua', countryId: 'tv' },
  { motto: 'Tuvalu pour le Tout-Puissant', countryId: 'tv' },
  { motto: 'Faavae i le Atua Samoa', countryId: 'ws' },
  { motto: 'Samoa est fondé sur Dieu', countryId: 'ws' },
  { motto: 'Bersekutu Bertambah Mutu', countryId: 'my' },
  { motto: 'L\'unité est la force', countryId: 'my' },
  { motto: 'En Dios Confiamos', countryId: 'ni' },
  { motto: 'En Dieu nous croyons', countryId: 'ni' },
  { motto: 'Dios, Patria, Libertad', countryId: 'do' },
  { motto: 'Dieu, Patrie, Liberté', countryId: 'do' },
  { motto: 'Paz y Justicia', countryId: 'py' },
  { motto: 'Paix et Justice', countryId: 'py' },
  { motto: 'Libertad o Muerte', countryId: 'uy' },
  { motto: 'Liberté ou Mort', countryId: 'uy' },
  { motto: 'Dios y Federación', countryId: 've' },
  { motto: 'Dieu et Fédération', countryId: 've' },
  { motto: 'Firme y feliz por la unión', countryId: 'pe' },
  { motto: 'Ferme et heureux par l\'union', countryId: 'pe' },
  { motto: 'Libre Crezca Fecundo', countryId: 'gt' },
  { motto: 'Que croissent libres et féconds', countryId: 'gt' },
  { motto: 'Libre, Soberana, Independiente', countryId: 'hn' },
  { motto: 'Libre, Souveraine, Indépendante', countryId: 'hn' },
  { motto: 'La unión es la fuerza', countryId: 'bo' },
  { motto: 'L\'union est la force', countryId: 'bo' },
  { motto: 'Libre crezca fecundo', countryId: 'gt' },
  { motto: 'Justice, Liberty, Prosperity', countryId: 'ss' },
  { motto: 'Peace, Unity, Liberty', countryId: 'fm' },
  { motto: 'Together we aspire, together we achieve', countryId: 'tt' },
  { motto: 'Unity in Diversity', countryId: 'pg' },
  { motto: 'One People, One Nation, One Destiny', countryId: 'gy' },
  { motto: 'L\'union fait la force', countryId: 'ht' },
  { motto: 'Saamen mestaan ja taatin', countryId: 'fi' },
  { motto: 'Ko e ʻOtua mo Tonga ko hoku tofiʻa', countryId: 'to' },
  { motto: 'Dieu et Tonga sont mon héritage', countryId: 'to' },
  { motto: 'Само слога Србина спасава', countryId: 'rs' },
  { motto: 'Seule l\'unité sauve les Serbes', countryId: 'rs' },
  { motto: 'Съединението прави силата', countryId: 'bg' },
  { motto: 'L\'union fait la force', countryId: 'bg' },
  { motto: 'ძალა ერთობაშია', countryId: 'ge' },
  { motto: 'La force est dans l\'unité', countryId: 'ge' },
  { motto: 'Միացյալ Հայաստան', countryId: 'am' },
  { motto: 'Une Arménie unie', countryId: 'am' },
  { motto: 'For Sverige - I Tiden', countryId: 'se' },
  { motto: 'Pour la Suède - dans son temps', countryId: 'se' },
  { motto: 'Alt for Norge', countryId: 'no' },
  { motto: 'Tout pour la Norvège', countryId: 'no' },
  { motto: 'Guds hjælp, folkets kærlighed, Danmarks styrke', countryId: 'dk' },
  { motto: 'Aide de Dieu, amour du peuple, force du Danemark', countryId: 'dk' },
  { motto: 'Yurtta sulh, cihanda sulh', countryId: 'tr' },
  { motto: 'Paix au pays, paix dans le monde', countryId: 'tr' },
  { motto: 'Maka-Diyos, Maka-Tao, Makakalikasan at Makabansa', countryId: 'ph' },
  { motto: 'Pour Dieu, le Peuple, la Nature et le Pays', countryId: 'ph' },
];

export const COUNTRY_MOTTOS_HARD: CountryMottoEntry[] = [
  { motto: 'Ubumwe, Umurimo, Gukunda Igihugu', countryId: 'rw' },
  { motto: 'Unité, Travail, Patriotisme', countryId: 'rw' },
  { motto: 'Te Mauri, Te Raoi, Te Tabomoa', countryId: 'ki' },
  { motto: 'Santé, Paix et Prospérité', countryId: 'ki' },
  { motto: 'God\'s Will First', countryId: 'nr' },
  { motto: 'La volonté de Dieu d\'abord', countryId: 'nr' },
  { motto: 'Honra, Pátria e Povo', countryId: 'tl' },
  { motto: 'Honneur, Patrie, Peuple', countryId: 'tl' },
  { motto: 'ایمان، اتحاد، نظم', countryId: 'pk' },
  { motto: 'Foi, Unité, Discipline', countryId: 'pk' },
  { motto: 'استقلال، آزادی، جمهوری اسلامی', countryId: 'ir' },
  { motto: 'Indépendance, Liberté, République islamique', countryId: 'ir' },
  { motto: 'الله، الوطن، الملك', countryId: 'jo' },
  { motto: 'Dieu, Patrie, Roi', countryId: 'jo' },
  { motto: 'لخدمة الوطن', countryId: 'bh' },
  { motto: 'Au service de la patrie', countryId: 'bh' },
  { motto: 'بالشّعب وللشّعب', countryId: 'dz' },
  { motto: 'Par le peuple et pour le peuple', countryId: 'dz' },
  { motto: 'حرية، نظام، عدالة', countryId: 'tn' },
  { motto: 'Liberté, Ordre, Justice', countryId: 'tn' },
  { motto: 'النصر لنا', countryId: 'sd' },
  { motto: 'La victoire est à nous', countryId: 'sd' },
  { motto: 'لا إله إلا الله محمد رسول الله', countryId: 'af' },
  { motto: 'Il n\'y a pas d\'autre dieu qu\'Allah', countryId: 'af' },
  { motto: 'ជាតិ សាសនា ព្រះមហាក្សត្រ', countryId: 'kh' },
  { motto: 'Nation, Religion, Roi', countryId: 'kh' },
  { motto: 'ສັນຕິພາບ ເອກະລາດ ປະຊາທິປະໄຕ ເອກະພາບ ວັດທະນາຖາວອນ', countryId: 'la' },
  { motto: 'Paix, Indépendance, Démocratie, Unité, Prospérité', countryId: 'la' },
  { motto: 'जननी जन्मभूमिश्च स्वर्गादपि गरीयसी', countryId: 'np' },
  { motto: 'Mère et Patrie sont plus grandes que le paradis', countryId: 'np' },
  { motto: 'Comoros - Unité, Justice, Progrès', countryId: 'km' },
  { motto: 'Quwwah – Imkaaniyaat – Wahdaad', countryId: 'so' },
  { motto: 'Force, Solidarité, Unité', countryId: 'so' },
  { motto: 'Ever Conscious of God We Aspire, Build and Advance as One People', countryId: 'gd' },
  { motto: 'The Land, The People, The Light', countryId: 'lc' },
  { motto: 'La Terre, le Peuple, la Lumière', countryId: 'lc' },
  { motto: 'Progress, Peace, Prosperity', countryId: 'gm' },
  { motto: 'Progrès, Paix, Prospérité', countryId: 'gm' },
  { motto: 'Unity and Freedom', countryId: 'mw' },
  { motto: 'Virtus Unita Fortior', countryId: 'ad' },
  { motto: 'La vertu unie est plus forte', countryId: 'ad' },
  { motto: 'Honour, Pride, Industriousness', countryId: 'bb' },
  { motto: 'Honneur, Fierté, Industrie', countryId: 'bb' },
  { motto: 'Sub umbra floreo', countryId: 'bz' },
  { motto: 'Je fleuris à l\'ombre', countryId: 'bz' },
  { motto: 'Forward, upward, onward, together', countryId: 'bs' },
  { motto: 'En avant, en haut, plus loin, ensemble', countryId: 'bs' },
];
