/**
 * Catalogue d'expressions pour la question Quiz CEO `expression`.
 *
 *   - `text`    : phrase avec `___` marquant le mot manquant
 *   - `answer`  : mot canonique attendu (source de vérité affichée au créateur)
 *   - `aliases` : variantes acceptées (sans accents, pluriels naturels…)
 *
 * 3 niveaux : EASY (proverbes ultra-connus), MEDIUM (idiomes courants),
 * HARD (proverbes anciens / mot manquant non-iconique).
 *
 * Doublons risqués (même prefix, variantes proches) supprimés à la curation.
 */

export interface ExpressionEntry {
  text: string;
  answer: string;
  aliases?: string[];
}

export const EXPRESSIONS_EASY: ExpressionEntry[] = [
  { text: 'Qui vole un ___ vole un bœuf.', answer: 'œuf', aliases: ['oeuf'] },
  { text: 'Mieux vaut tard que ___.', answer: 'jamais' },
  { text: 'Tel père, tel ___.', answer: 'fils' },
  { text: 'L\'habit ne fait pas le ___.', answer: 'moine' },
  { text: 'Loin des yeux, loin du ___.', answer: 'cœur', aliases: ['coeur'] },
  { text: 'C\'est la goutte d\'eau qui fait déborder le ___.', answer: 'vase' },
  { text: 'Aux grands maux les grands ___.', answer: 'remèdes', aliases: ['remedes'] },
  { text: 'Qui sème le vent récolte la ___.', answer: 'tempête', aliases: ['tempete'] },
  { text: 'Petit à petit, l\'oiseau fait son ___.', answer: 'nid' },
  { text: 'À chaque jour suffit sa ___.', answer: 'peine' },
  { text: 'La nuit porte ___.', answer: 'conseil' },
  { text: 'La parole est d\'argent, le silence est d\'___.', answer: 'or' },
  { text: 'Qui dort ___.', answer: 'dîne', aliases: ['dine'] },
  { text: 'Tous les chemins mènent à ___.', answer: 'Rome' },
  { text: 'Rome ne s\'est pas faite en un ___.', answer: 'jour' },
  { text: 'Mieux vaut prévenir que ___.', answer: 'guérir', aliases: ['guerir'] },
  { text: 'Il n\'y a pas de fumée sans ___.', answer: 'feu' },
  { text: 'L\'argent ne fait pas le ___.', answer: 'bonheur' },
  { text: 'Qui se ressemble s\'___.', answer: 'assemble' },
  { text: 'On ne fait pas d\'omelette sans casser des ___.', answer: 'œufs', aliases: ['oeufs'] },
  { text: 'Les bons comptes font les bons ___.', answer: 'amis' },
  { text: 'Plus on est de fous, plus on ___.', answer: 'rit' },
  { text: 'Faute avouée à moitié ___.', answer: 'pardonnée', aliases: ['pardonnee'] },
  { text: 'Vouloir, c\'est ___.', answer: 'pouvoir' },
  { text: 'Les murs ont des ___.', answer: 'oreilles' },
  { text: 'Pas de nouvelles, bonnes ___.', answer: 'nouvelles' },
  { text: 'Quand le chat n\'est pas là, les souris ___.', answer: 'dansent' },
  { text: 'À bon chat, bon ___.', answer: 'rat' },
  { text: 'L\'occasion fait le ___.', answer: 'larron' },
  { text: 'Une hirondelle ne fait pas le ___.', answer: 'printemps' },
  { text: 'Après la pluie, le beau ___.', answer: 'temps' },
  { text: 'L\'union fait la ___.', answer: 'force' },
  { text: 'Qui vivra ___.', answer: 'verra' },
  { text: 'Aide-toi, le ciel t\'___.', answer: 'aidera' },
  { text: 'L\'appétit vient en ___.', answer: 'mangeant' },
  { text: 'C\'est en forgeant qu\'on devient ___.', answer: 'forgeron' },
  { text: 'La fin justifie les ___.', answer: 'moyens' },
  { text: 'Tout est bien qui finit ___.', answer: 'bien' },
  { text: 'Il faut battre le fer tant qu\'il est ___.', answer: 'chaud' },
  { text: 'C\'est l\'arbre qui cache la ___.', answer: 'forêt', aliases: ['foret'] },
  { text: 'Les voyages forment la ___.', answer: 'jeunesse' },
  { text: 'Une chaîne est aussi solide que son maillon le plus ___.', answer: 'faible' },
  { text: 'Les chats ont neuf ___.', answer: 'vies' },
  { text: 'Un homme averti en vaut ___.', answer: 'deux' },
  { text: 'Ventre affamé n\'a pas d\'___.', answer: 'oreilles' },
  { text: 'Le mieux est l\'ennemi du ___.', answer: 'bien' },
  { text: 'Au royaume des aveugles, les borgnes sont ___.', answer: 'rois' },
  { text: 'Tout vient à point à qui sait ___.', answer: 'attendre' },
  { text: 'Une fois n\'est pas ___.', answer: 'coutume' },
  { text: 'Mieux vaut être seul que mal ___.', answer: 'accompagné', aliases: ['accompagne'] },
  { text: 'Bien mal acquis ne profite ___.', answer: 'jamais' },
  { text: 'Qui ne risque rien n\'a ___.', answer: 'rien' },
  { text: 'Pierre qui roule n\'amasse pas ___.', answer: 'mousse' },
  { text: 'À cheval donné, on ne regarde pas les ___.', answer: 'dents' },
  { text: 'Ce n\'est pas la mer à ___.', answer: 'boire' },
  { text: 'Un tiens vaut mieux que deux tu l\'___.', answer: 'auras' },
  { text: 'Heureux au jeu, malheureux en ___.', answer: 'amour' },
  { text: 'À l\'impossible, nul n\'est ___.', answer: 'tenu' },
  { text: 'Tout ce qui brille n\'est pas ___.', answer: 'or' },
  { text: 'Le temps c\'est de l\'___.', answer: 'argent' },
  { text: 'Pas vu, pas ___.', answer: 'pris' },
  { text: 'Avec des si, on mettrait Paris en ___.', answer: 'bouteille' },
  { text: 'Faire d\'une pierre deux ___.', answer: 'coups' },
  { text: 'Mettre la charrue avant les ___.', answer: 'bœufs', aliases: ['boeufs'] },
  { text: 'Avoir le cœur sur la ___.', answer: 'main' },
  { text: 'Avoir un cœur d\'___.', answer: 'artichaut' },
  { text: 'Faire un froid de ___.', answer: 'canard' },
  { text: 'Avoir une faim de ___.', answer: 'loup' },
  { text: 'Donner sa langue au ___.', answer: 'chat' },
  { text: 'Couper l\'herbe sous le ___.', answer: 'pied' },
  { text: 'Tomber dans le ___.', answer: 'panneau' },
  { text: 'La moutarde lui monte au ___.', answer: 'nez' },
  { text: 'Avoir la tête dans les ___.', answer: 'nuages' },
  { text: 'Quand on parle du loup, on en voit la ___.', answer: 'queue' },
  { text: 'Tirer les vers du ___.', answer: 'nez' },
  { text: 'Avoir le bras ___.', answer: 'long' },
  { text: 'C\'est la cerise sur le ___.', answer: 'gâteau', aliases: ['gateau'] },
  { text: 'Casser sa ___.', answer: 'pipe' },
  { text: 'Avoir l\'estomac dans les ___.', answer: 'talons' },
  { text: 'Couper les cheveux en ___.', answer: 'quatre' },
  { text: 'Faire la pluie et le beau ___.', answer: 'temps' },
  { text: 'Mettre du beurre dans les ___.', answer: 'épinards', aliases: ['epinards'] },
  { text: 'N\'y voir que du ___.', answer: 'feu' },
  { text: 'Mettre les pieds dans le ___.', answer: 'plat' },
  { text: 'C\'est cousu de fil ___.', answer: 'blanc' },
  { text: 'Avoir un poil dans la ___.', answer: 'main' },
  { text: 'Marcher sur des ___.', answer: 'œufs', aliases: ['oeufs'] },
  { text: 'Pleuvoir des ___.', answer: 'cordes' },
  { text: 'Filer à l\'___.', answer: 'anglaise' },
  { text: 'Sauter du coq à l\'___.', answer: 'âne', aliases: ['ane'] },
  { text: 'Riche comme ___.', answer: 'Crésus', aliases: ['Cresus'] },
  { text: 'Bête comme ses ___.', answer: 'pieds' },
  { text: 'Sourd comme un ___.', answer: 'pot' },
  { text: 'Long comme un jour sans ___.', answer: 'pain' },
  { text: 'Têtu comme une ___.', answer: 'mule' },
  { text: 'Maigre comme un ___.', answer: 'clou' },
  { text: 'Rouge comme une ___.', answer: 'tomate' },
  { text: 'Blanc comme ___.', answer: 'neige' },
  { text: 'Doux comme un ___.', answer: 'agneau' },
];

export const EXPRESSIONS_MEDIUM: ExpressionEntry[] = [
  { text: 'Bon sang ne saurait ___.', answer: 'mentir' },
  { text: 'Œil pour œil, dent pour ___.', answer: 'dent' },
  { text: 'Toute peine mérite ___.', answer: 'salaire' },
  { text: 'Charité bien ordonnée commence par ___.', answer: 'soi-même', aliases: ['soi meme', 'soi'] },
  { text: 'Mieux vaut faire envie que ___.', answer: 'pitié', aliases: ['pitie'] },
  { text: 'Petite pluie abat grand ___.', answer: 'vent' },
  { text: 'Qui peut le plus peut le ___.', answer: 'moins' },
  { text: 'Toute médaille a son ___.', answer: 'revers', aliases: ['medaille'] },
  { text: 'Le poisson pourrit par la ___.', answer: 'tête', aliases: ['tete'] },
  { text: 'Faute de grives, on mange des ___.', answer: 'merles' },
  { text: 'Rira bien qui rira le ___.', answer: 'dernier' },
  { text: 'Quand le vin est tiré, il faut le ___.', answer: 'boire' },
  { text: 'Il faut hurler avec les ___.', answer: 'loups' },
  { text: 'Petit poisson deviendra ___.', answer: 'grand' },
  { text: 'Vivre d\'amour et d\'eau ___.', answer: 'fraîche', aliases: ['fraiche'] },
  { text: 'Tirer le diable par la ___.', answer: 'queue' },
  { text: 'Avoir le cul entre deux ___.', answer: 'chaises' },
  { text: 'Tomber dans les bras de ___.', answer: 'Morphée', aliases: ['Morphee'] },
  { text: 'La fortune sourit aux ___.', answer: 'audacieux' },
  { text: 'Manger les pissenlits par la ___.', answer: 'racine' },
  { text: 'Ne pas être dans son ___.', answer: 'assiette' },
  { text: 'Mettre le doigt sur la ___.', answer: 'plaie' },
  { text: 'Avoir d\'autres chats à ___.', answer: 'fouetter' },
  { text: 'Avoir la tête sur les ___.', answer: 'épaules', aliases: ['epaules'] },
  { text: 'Avoir un mal de ___.', answer: 'chien' },
  { text: 'Tomber des ___.', answer: 'nues' },
  { text: 'Vendre la peau de l\'ours avant de l\'avoir ___.', answer: 'tué', aliases: ['tue'] },
  { text: 'Reprendre du poil de la ___.', answer: 'bête', aliases: ['bete'] },
  { text: 'Avoir le moral dans les ___.', answer: 'chaussettes' },
  { text: 'Voir le bout du ___.', answer: 'tunnel' },
  { text: 'Avoir un fil à la ___.', answer: 'patte' },
  { text: 'Avoir une mémoire d\'___.', answer: 'éléphant', aliases: ['elephant'] },
  { text: 'Tomber de Charybde en ___.', answer: 'Scylla' },
  { text: 'C\'est la croix et la ___.', answer: 'bannière', aliases: ['banniere'] },
  { text: 'Être sur son trente et ___.', answer: 'un' },
  { text: 'Ne pas y aller par quatre ___.', answer: 'chemins' },
  { text: 'C\'est une autre paire de ___.', answer: 'manches' },
  { text: 'Découvrir le ___ aux roses.', answer: 'pot' },
  { text: 'Filer un mauvais ___.', answer: 'coton' },
  { text: 'Boire la ___.', answer: 'tasse' },
  { text: 'Sauter aux ___.', answer: 'yeux' },
  { text: 'Avoir les yeux plus gros que le ___.', answer: 'ventre' },
  { text: 'Casser du ___ sur le dos de quelqu\'un.', answer: 'sucre' },
  { text: 'Trouver chaussure à son ___.', answer: 'pied' },
  { text: 'Mettre les bouchées ___.', answer: 'doubles' },
  { text: 'Se mettre au ___.', answer: 'vert' },
  { text: 'Être au septième ___.', answer: 'ciel' },
  { text: 'Courir deux lièvres à la ___.', answer: 'fois' },
  { text: 'Mettre la dernière ___.', answer: 'main' },
  { text: 'Faire chou ___.', answer: 'blanc' },
  { text: 'Donner du fil à ___.', answer: 'retordre' },
  { text: 'Jeter de la poudre aux ___.', answer: 'yeux' },
  { text: 'Crier sur tous les ___.', answer: 'toits' },
  { text: 'Promettre monts et ___.', answer: 'merveilles' },
  { text: 'Crier au ___.', answer: 'loup' },
  { text: 'Voir la vie en ___.', answer: 'rose' },
  { text: 'Mettre la main à la ___.', answer: 'pâte', aliases: ['pate'] },
  { text: 'Il y a anguille sous ___.', answer: 'roche' },
  { text: 'Tirer la couverture à ___.', answer: 'soi' },
  { text: 'Faire la sourde ___.', answer: 'oreille' },
  { text: 'Tirer son ___ du jeu.', answer: 'épingle', aliases: ['epingle'] },
  { text: 'Avoir un mot sur le bout de la ___.', answer: 'langue' },
  { text: 'Couler de ___.', answer: 'source' },
  { text: 'Avoir des fourmis dans les ___.', answer: 'jambes' },
  { text: 'Tirer à boulets ___.', answer: 'rouges' },
  { text: 'Mettre cartes sur ___.', answer: 'table' },
  { text: 'Mettre des bâtons dans les ___.', answer: 'roues', aliases: ['batons'] },
  { text: 'À tort et à ___.', answer: 'travers' },
  { text: 'Couper la poire en ___.', answer: 'deux' },
  { text: 'Promettre la ___ et la terre.', answer: 'lune' },
  { text: 'Prendre les choses du bon ___.', answer: 'côté', aliases: ['cote'] },
  { text: 'Avoir un nœud dans la ___.', answer: 'gorge', aliases: ['noeud'] },
  { text: 'Donner du grain à ___.', answer: 'moudre' },
  { text: 'Faire la fine ___.', answer: 'bouche' },
  { text: 'Faire son mea ___.', answer: 'culpa' },
  { text: 'Chercher midi à quatorze ___.', answer: 'heures' },
  { text: 'Plier ___.', answer: 'bagage' },
  { text: 'Ronger son ___.', answer: 'frein' },
  { text: 'Avoir maille à ___.', answer: 'partir' },
  { text: 'Ne pas en mener ___.', answer: 'large' },
  { text: 'Couper l\'eau au ___.', answer: 'moulin' },
  { text: 'Battre en ___.', answer: 'retraite' },
  { text: 'Il y a péril en la ___.', answer: 'demeure', aliases: ['peril'] },
  { text: 'Faire amende ___.', answer: 'honorable' },
  { text: 'Avoir voix au ___.', answer: 'chapitre' },
  { text: 'Faire les yeux ___.', answer: 'doux' },
  { text: 'Pendre la ___.', answer: 'crémaillère', aliases: ['cremaillere'] },
  { text: 'Savoir sur le bout des ___.', answer: 'doigts' },
  { text: 'Mettre la main sur le ___.', answer: 'cœur', aliases: ['coeur'] },
  { text: 'Couler à ___.', answer: 'pic' },
  { text: 'Tomber dans les ___.', answer: 'pommes' },
  { text: 'Avoir le couteau sous la ___.', answer: 'gorge' },
  { text: 'Avoir l\'eau à la ___.', answer: 'bouche' },
];

export const EXPRESSIONS_HARD: ExpressionEntry[] = [
  { text: 'Belle promesse, fol ___.', answer: 'espoir' },
  { text: 'Plaie d\'argent n\'est pas ___.', answer: 'mortelle' },
  { text: 'Les conseilleurs ne sont pas les ___.', answer: 'payeurs' },
  { text: 'Qui se sent morveux se ___.', answer: 'mouche' },
  { text: 'Qui se couche avec les chiens se relève avec des ___.', answer: 'puces' },
  { text: 'Qui veut voyager loin ménage sa ___.', answer: 'monture' },
  { text: 'Trop gratter cuit, trop parler ___.', answer: 'nuit' },
  { text: 'Aux innocents les mains ___.', answer: 'pleines' },
  { text: 'À tout péché ___.', answer: 'miséricorde', aliases: ['misericorde', 'peche'] },
  { text: 'Bien faire et laisser ___.', answer: 'dire' },
  { text: 'Ce qui est fait n\'est plus à ___.', answer: 'faire' },
  { text: 'Qui se loue, s\'___.', answer: 'emboue' },
  { text: 'Faire et défaire, c\'est toujours ___.', answer: 'travailler', aliases: ['defaire'] },
  { text: 'Il n\'est jamais trop tard pour bien ___.', answer: 'faire' },
  { text: 'Chassez le naturel, il revient au ___.', answer: 'galop' },
  { text: 'La caque sent toujours le ___.', answer: 'hareng' },
  { text: 'Bon chien chasse de ___.', answer: 'race' },
  { text: 'Comme on fait son lit, on se ___.', answer: 'couche' },
  { text: 'À tout seigneur, tout ___.', answer: 'honneur' },
  { text: 'Charbonnier est maître chez ___.', answer: 'soi', aliases: ['maitre'] },
  { text: 'Tel est pris qui croyait ___.', answer: 'prendre' },
  { text: 'Le ridicule ne tue ___.', answer: 'personne' },
  { text: 'Qui aime bien châtie ___.', answer: 'bien', aliases: ['chatie'] },
  { text: 'Qui paie ses dettes s\'___.', answer: 'enrichit' },
  { text: 'Comparaison n\'est pas ___.', answer: 'raison' },
  { text: 'Vingt fois sur le métier, remettez votre ___.', answer: 'ouvrage', aliases: ['metier'] },
  { text: 'Tout flatteur vit aux dépens de celui qui ___.', answer: 'l\'écoute', aliases: ['lecoute', 'l ecoute', 'écoute', 'ecoute', 'depens'] },
  { text: 'À cœur vaillant, rien d\'___.', answer: 'impossible', aliases: ['coeur'] },
  { text: 'Bonne renommée vaut mieux que ceinture ___.', answer: 'dorée', aliases: ['doree', 'renommee'] },
  { text: 'Tant va la cruche à l\'eau qu\'à la fin elle se ___.', answer: 'casse' },
  { text: 'Quand l\'arbre est tombé, tout le monde court aux ___.', answer: 'branches' },
  { text: 'Bois tordu fait feu ___.', answer: 'droit' },
  { text: 'À chaque pot son ___.', answer: 'couvercle' },
  { text: 'Prudence est mère de ___.', answer: 'sûreté', aliases: ['surete', 'mere'] },
  { text: 'Qui terre a, guerre ___.', answer: 'a' },
  { text: 'Quand le sage montre la lune, l\'imbécile regarde le ___.', answer: 'doigt', aliases: ['imbecile'] },
  { text: 'Plus fait douceur que ___.', answer: 'violence' },
  { text: 'Ce que femme veut, Dieu le ___.', answer: 'veut' },
  { text: 'La fortune vient en ___.', answer: 'dormant' },
  { text: 'Qui vit content de ___, est riche.', answer: 'peu' },
  { text: 'Qui veut faire l\'ange fait la ___.', answer: 'bête', aliases: ['bete'] },
  { text: 'C\'est le pot de terre contre le pot de ___.', answer: 'fer' },
  { text: 'Qui n\'entend qu\'une cloche n\'entend qu\'un ___.', answer: 'son' },
  { text: 'À petite cause, grands ___.', answer: 'effets' },
  { text: 'Quand on n\'a pas de tête, il faut avoir des ___.', answer: 'jambes', aliases: ['tete'] },
  { text: 'Bon vin, mauvaise ___.', answer: 'tête', aliases: ['tete'] },
  { text: 'Qui craint le danger ne doit pas aller en ___.', answer: 'mer' },
  { text: 'Donner un œuf pour avoir un ___.', answer: 'bœuf', aliases: ['boeuf', 'oeuf'] },
  { text: 'Ce que l\'œil ne voit pas, le cœur ne ___.', answer: 'sent', aliases: ['oeil', 'coeur'] },
  { text: 'Œuvres de jeunesse, regrets de ___.', answer: 'vieillesse', aliases: ['oeuvres'] },
  { text: 'Qui veut noyer son chien l\'accuse de la ___.', answer: 'rage' },
  { text: 'Petit homme abat grand ___.', answer: 'chêne', aliases: ['chene'] },
  { text: 'Cordonnier mal ___.', answer: 'chaussé', aliases: ['chausse'] },
  { text: 'La meilleure défense, c\'est l\'___.', answer: 'attaque', aliases: ['defense'] },
  { text: 'Pour vivre heureux, vivons ___.', answer: 'cachés', aliases: ['caches'] },
  { text: 'Qui ne sait dissimuler ne sait ___.', answer: 'régner', aliases: ['regner'] },
  { text: 'Aussitôt dit, aussitôt ___.', answer: 'fait', aliases: ['aussitot'] },
  { text: 'Le mort saisit le ___.', answer: 'vif' },
  { text: 'Qui s\'y frotte s\'y ___.', answer: 'pique' },
  { text: 'À chaque chose son ___.', answer: 'temps' },
  { text: 'C\'est la poule qui chante qui a fait l\'___.', answer: 'œuf', aliases: ['oeuf'] },
  { text: 'À jeune chasseur il faut un vieux ___.', answer: 'chien' },
  { text: 'Le sage entend à demi-___.', answer: 'mot' },
  { text: 'Ne réveillez pas le chat qui ___.', answer: 'dort', aliases: ['reveillez'] },
  { text: 'Trop d\'amis, point d\'___.', answer: 'ami' },
  { text: 'Qui veut la paix prépare la ___.', answer: 'guerre', aliases: ['prepare'] },
  { text: 'À vaincre sans péril, on triomphe sans ___.', answer: 'gloire', aliases: ['peril'] },
  { text: 'Faute de pain, on mange de la ___.', answer: 'galette' },
  { text: 'Donnant, ___.', answer: 'donnant' },
  { text: 'Toute vérité n\'est pas bonne à ___.', answer: 'dire', aliases: ['verite'] },
  { text: 'Tant qu\'il y a de la vie, il y a de l\'___.', answer: 'espoir' },
  { text: 'Pas de roses sans ___.', answer: 'épines', aliases: ['epines'] },
  { text: 'Tel maître, tel ___.', answer: 'valet', aliases: ['maitre'] },
  { text: 'À l\'ennemi qui s\'enfuit, faire un pont d\'___.', answer: 'or' },
  { text: 'À quelque chose malheur est ___.', answer: 'bon' },
  { text: 'À chacun son ___.', answer: 'métier', aliases: ['metier'] },
  { text: 'La nuit, tous les chats sont ___.', answer: 'gris' },
  { text: 'Selon ta bourse gouverne ta ___.', answer: 'bouche' },
  { text: 'À chaque oiseau son nid ___.', answer: 'paraît beau', aliases: ['parait beau', 'paraît', 'parait'] },
  { text: 'Qui sème en pleurs récolte en ___.', answer: 'chants', aliases: ['seme'] },
  { text: 'Le doute est le commencement de la ___.', answer: 'sagesse' },
  { text: 'À mauvais jeu, bonne ___.', answer: 'mine' },
  { text: 'Au plus malade, la ___.', answer: 'bouillie' },
  { text: 'Loin du roi, loin de la ___.', answer: 'cour' },
  { text: 'Qui mange du pape en ___.', answer: 'meurt' },
  { text: 'Une fois n\'est pas coutume, deux fois est ___.', answer: 'habitude' },
];
