/**
 * Catalogue de slogans publicitaires français pour le Quiz CEO type
 * `slogan-pub`. QCM 4 choix de marques.
 *
 * Mécanique : on affiche un slogan FR culte → le joueur choisit la marque
 * parmi 4 propositions. Les distractors (3 mauvaises marques) sont tirés
 * au runtime à `start/route.ts` parmi le pool `FRENCH_AD_BRANDS_POOL` (les
 * marques connues qui figurent dans le catalogue + quelques extras), comme
 * pour `zodiac-mbti`. Les choix changent donc à chaque partie.
 *
 * Source : recall personnel + corpus pub française des 30 dernières années.
 * Toutes en difficulty `medium` (2 pts) sauf indication contraire.
 */

export interface FrenchAdEntry {
  slogan: string;
  brand: string;
  /** Difficulté : easy = ultra-mainstream, medium = identifiable, hard = pour vrais connaisseurs. */
  difficulty: 'easy' | 'medium' | 'hard';
}

/**
 * Pool de marques utilisé pour tirer les distractors au runtime. Doit
 * contenir tous les `brand` du catalogue + quelques extras pour brouiller
 * les pistes (ex. concurrents directs).
 */
export const FRENCH_AD_BRANDS_POOL: string[] = [
  'McDonald\'s',
  'Carrefour',
  'Leclerc',
  'Auchan',
  'Intermarché',
  'Casino',
  'Monoprix',
  'Lidl',
  'Decathlon',
  'Fnac',
  'Darty',
  'Boulanger',
  'Conforama',
  'But',
  'Ikea',
  'Castorama',
  'Leroy Merlin',
  'Brico Dépôt',
  'L\'Oréal',
  'Garnier',
  'Dior',
  'Chanel',
  'Yves Saint Laurent',
  'Hermès',
  'Citroën',
  'Peugeot',
  'Renault',
  'BMW',
  'Audi',
  'Volkswagen',
  'Nissan',
  'Toyota',
  'Renault',
  'Bouygues Telecom',
  'Orange',
  'SFR',
  'Free',
  'La Poste',
  'EDF',
  'GDF',
  'Engie',
  'Total',
  'BNP Paribas',
  'Crédit Agricole',
  'LCL',
  'Société Générale',
  'Banque Populaire',
  'Crédit Mutuel',
  'AXA',
  'MAIF',
  'MAAF',
  'Macif',
  'Groupama',
  'Allianz',
  'Lustucru',
  'Panzani',
  'Barilla',
  'Buitoni',
  'Findus',
  'Picard',
  'Bonduelle',
  'Yoplait',
  'Danone',
  'Activia',
  'Actimel',
  'Ferrero',
  'Nutella',
  'Kinder',
  'Milka',
  'Kit Kat',
  'Mars',
  'Twix',
  'Lindt',
  'Côte d\'Or',
  'Haribo',
  'Carambar',
  'Malabar',
  'Coca-Cola',
  'Pepsi',
  'Orangina',
  'Schweppes',
  'Perrier',
  'Evian',
  'Vittel',
  'Volvic',
  'Cristaline',
  'Pastis 51',
  'Ricard',
  'Heineken',
  'Kronenbourg',
  '1664',
  'Leffe',
  'Desperados',
  'Petit Bateau',
  'Petit Navire',
  'Tipiak',
  'Lustucru',
  'Mamie Nova',
  'Yop',
  'Banania',
  'Nesquik',
  'Nescafé',
  'Tassimo',
  'Senseo',
  'Lavazza',
  'L\'Or',
  'Carte Noire',
  'Maxwell House',
  'Mont Blanc',
  'La Vache qui rit',
  'Babybel',
  'Kiri',
  'Boursin',
  'Caprice des Dieux',
  'Président',
  'Lactalis',
  'Yoplait',
  'Bel',
  'Activia',
  'Loto',
  'EuroMillions',
  'PMU',
  'FDJ',
  'Citroën',
  'EDF',
  'SNCF',
  'TGV',
  'Air France',
  'Veolia',
  'Suez',
];

export const FRENCH_ADS: FrenchAdEntry[] = [
  // ───── EASY (ultra-mainstream) ─────
  { slogan: 'Venez comme vous êtes.', brand: 'McDonald\'s', difficulty: 'easy' },
  { slogan: 'Parce que vous le valez bien.', brand: 'L\'Oréal', difficulty: 'easy' },
  { slogan: 'Un café nommé désir.', brand: 'Carte Noire', difficulty: 'easy' },
  { slogan: 'Lu, le plaisir partagé.', brand: 'Lu', difficulty: 'easy' },
  { slogan: 'Ce qui est petit est mignon.', brand: 'Babybel', difficulty: 'easy' },
  { slogan: 'C\'est si bon !', brand: 'Carrefour', difficulty: 'easy' },
  { slogan: 'On se lève tous pour Danette.', brand: 'Danone', difficulty: 'easy' },
  { slogan: 'Bouge avec un Yop.', brand: 'Yoplait', difficulty: 'easy' },
  { slogan: 'Y\'a bon Banania.', brand: 'Banania', difficulty: 'easy' },
  { slogan: 'Tu peux pas tester… Malabar.', brand: 'Malabar', difficulty: 'easy' },
  { slogan: 'À fond la forme.', brand: 'Decathlon', difficulty: 'easy' },
  { slogan: 'Le contrat de confiance.', brand: 'Darty', difficulty: 'easy' },
  { slogan: 'Bouygues Telecom — la vie en mieux.', brand: 'Bouygues Telecom', difficulty: 'easy' },
  { slogan: 'Free, l\'opérateur qui change tout.', brand: 'Free', difficulty: 'easy' },
  { slogan: 'Prenez la vie côté Casino.', brand: 'Casino', difficulty: 'easy' },
  { slogan: 'Avec Carrefour, je positive.', brand: 'Carrefour', difficulty: 'easy' },
  { slogan: 'Lustucru… c\'est lustucru.', brand: 'Lustucru', difficulty: 'easy' },
  { slogan: 'Des pâtes, des pâtes oui mais Panzani.', brand: 'Panzani', difficulty: 'easy' },
  { slogan: 'Quand c\'est trop, c\'est Tropico.', brand: 'Tropico', difficulty: 'easy' },
  { slogan: 'Et toc !', brand: 'Bic', difficulty: 'easy' },
  { slogan: 'Just do it… euh non, " À donf ! "', brand: 'Decathlon', difficulty: 'easy' },
  { slogan: 'La banque d\'un monde qui change.', brand: 'BNP Paribas', difficulty: 'easy' },
  { slogan: 'Le bon sens près de chez vous.', brand: 'Leclerc', difficulty: 'easy' },
  { slogan: 'Auchan, la vie, la vraie.', brand: 'Auchan', difficulty: 'easy' },
  { slogan: 'Tous unis contre la vie chère.', brand: 'Intermarché', difficulty: 'easy' },
  { slogan: 'L\'autre prix du « pas cher ».', brand: 'Lidl', difficulty: 'easy' },
  { slogan: 'Ouvrez ouvrez la cage aux oiseaux.', brand: 'Ferrero', difficulty: 'easy' },
  { slogan: 'Get the London look.', brand: 'Rimmel', difficulty: 'easy' },
  { slogan: 'Découvrez Free, la liberté n\'a pas de prix.', brand: 'Free', difficulty: 'easy' },
  { slogan: 'Quand y\'en a marre, y\'a Malabar.', brand: 'Malabar', difficulty: 'easy' },

  // ───── MEDIUM (slogans connus mais pas universels) ─────
  { slogan: 'Le bonheur, si je veux.', brand: 'Saint-Gobain', difficulty: 'medium' },
  { slogan: 'Les hommes savent pourquoi.', brand: 'Volkswagen', difficulty: 'medium' },
  { slogan: 'Quand on aime la vie, on aime BNP.', brand: 'BNP Paribas', difficulty: 'medium' },
  { slogan: 'Du pain, du vin, du Boursin.', brand: 'Boursin', difficulty: 'medium' },
  { slogan: 'Mettez du fruit dans votre vie.', brand: 'Andros', difficulty: 'medium' },
  { slogan: 'Buvez, éliminez.', brand: 'Vittel', difficulty: 'medium' },
  { slogan: 'Vittel, pour ceux qui se sentent bien dans leur corps.', brand: 'Vittel', difficulty: 'medium' },
  { slogan: 'L\'eau, la vie, la santé.', brand: 'Évian', difficulty: 'medium' },
  { slogan: 'Volvic, force de la nature.', brand: 'Volvic', difficulty: 'medium' },
  { slogan: 'C\'est fou ce qu\'on a fait pour le rendre fou.', brand: 'Saupiquet', difficulty: 'medium' },
  { slogan: 'Le rouge à lèvres rouge.', brand: 'Bourjois', difficulty: 'medium' },
  { slogan: 'Pour ceux qui aiment vivre.', brand: 'Renault', difficulty: 'medium' },
  { slogan: 'Le plus court chemin entre vous et vous.', brand: 'Air France', difficulty: 'medium' },
  { slogan: 'Faire du ciel le plus bel endroit de la Terre.', brand: 'Air France', difficulty: 'medium' },
  { slogan: 'Quand on a fini, c\'est qu\'on a commencé.', brand: 'Findus', difficulty: 'medium' },
  { slogan: 'Findus, c\'est dingue ce qu\'on aime ça.', brand: 'Findus', difficulty: 'medium' },
  { slogan: 'Sois belle et tais-toi.', brand: 'Garnier', difficulty: 'medium' },
  { slogan: 'Du goût, du goût, du goût.', brand: 'Maille', difficulty: 'medium' },
  { slogan: 'Ça va mieux en le disant.', brand: 'Wonder', difficulty: 'medium' },
  { slogan: 'La pile Wonder s\'use seulement si l\'on s\'en sert.', brand: 'Wonder', difficulty: 'medium' },
  { slogan: 'Pas de prix sans Conforama.', brand: 'Conforama', difficulty: 'medium' },
  { slogan: 'Le moins cher des grands magasins.', brand: 'BHV', difficulty: 'medium' },
  { slogan: 'Cofidis, il vous donne envie d\'y croire.', brand: 'Cofidis', difficulty: 'medium' },
  { slogan: 'BNP, votre argent m\'intéresse.', brand: 'BNP Paribas', difficulty: 'medium' },
  { slogan: 'Cetelem, c\'est facile.', brand: 'Cetelem', difficulty: 'medium' },
  { slogan: 'À vous la côte d\'Azur, à nous Brittany Ferries.', brand: 'Brittany Ferries', difficulty: 'medium' },
  { slogan: 'L\'abus d\'alcool est dangereux pour la santé… mais pas chez Heineken.', brand: 'Heineken', difficulty: 'medium' },
  { slogan: 'À votre santé !', brand: 'Heineken', difficulty: 'medium' },
  { slogan: 'Vois ce qu\'il y a dans ton verre.', brand: 'Coca-Cola', difficulty: 'medium' },
  { slogan: 'Ouvrez du bonheur.', brand: 'Coca-Cola', difficulty: 'medium' },
  { slogan: 'Un Orangina ?', brand: 'Orangina', difficulty: 'medium' },
  { slogan: 'Secouez-moi, secouez-moi.', brand: 'Orangina', difficulty: 'medium' },
  { slogan: 'Schweppes ou rien.', brand: 'Schweppes', difficulty: 'medium' },
  { slogan: 'Pernod Ricard, l\'esprit du Sud.', brand: 'Ricard', difficulty: 'medium' },
  { slogan: 'Un Ricard sinon rien.', brand: 'Ricard', difficulty: 'medium' },
  { slogan: 'Du nerf, prenez du Banania.', brand: 'Banania', difficulty: 'medium' },
  { slogan: 'Délivrez-vous des supermarchés.', brand: 'Picard', difficulty: 'medium' },
  { slogan: 'Picard, mettre du bon dans son frigo.', brand: 'Picard', difficulty: 'medium' },
  { slogan: 'On a tous besoin de petits Plus.', brand: 'Casino', difficulty: 'medium' },
  { slogan: 'Bonne maman, c\'est tout naturellement.', brand: 'Bonne Maman', difficulty: 'medium' },
  { slogan: 'On dort mieux dans un lit Treca.', brand: 'Treca', difficulty: 'medium' },
  { slogan: 'Maille, qui m\'aime me suive.', brand: 'Maille', difficulty: 'medium' },
  { slogan: 'Volkswagen, das Auto.', brand: 'Volkswagen', difficulty: 'medium' },
  { slogan: 'Nissan, the power of dreams.', brand: 'Honda', difficulty: 'medium' },
  { slogan: 'Toyota, today, tomorrow, Toyota.', brand: 'Toyota', difficulty: 'medium' },
  { slogan: 'Le toujours plus que jamais.', brand: 'Renault', difficulty: 'medium' },
  { slogan: 'Renault, des voitures à vivre.', brand: 'Renault', difficulty: 'medium' },
  { slogan: 'Citroën, créative technologie.', brand: 'Citroën', difficulty: 'medium' },
  { slogan: 'Peugeot, motion & emotion.', brand: 'Peugeot', difficulty: 'medium' },
  { slogan: 'Devenez sociétaire.', brand: 'MAIF', difficulty: 'medium' },
  { slogan: 'L\'assureur militant.', brand: 'MAIF', difficulty: 'medium' },
  { slogan: 'Plus belle la vie avec la MAAF.', brand: 'MAAF', difficulty: 'medium' },
  { slogan: 'Macif, parce qu\'on est tous concernés.', brand: 'Macif', difficulty: 'medium' },

  // ───── HARD (slogans plus anciens ou de niche) ─────
  { slogan: 'Quand c\'est non, c\'est non.', brand: 'Loto', difficulty: 'hard' },
  { slogan: '100 % des gagnants ont tenté leur chance.', brand: 'Loto', difficulty: 'hard' },
  { slogan: 'EuroMillions, qui ne tente rien n\'a rien.', brand: 'EuroMillions', difficulty: 'hard' },
  { slogan: 'Eram, on n\'est pas obligé d\'être pieds nus pour faire du bruit.', brand: 'Eram', difficulty: 'hard' },
  { slogan: 'Mes premières chaussures, c\'est André.', brand: 'André', difficulty: 'hard' },
  { slogan: 'Pour les hommes qui n\'ont pas peur de plaire.', brand: 'Yves Saint Laurent', difficulty: 'hard' },
  { slogan: 'Il y a quelque chose de Citroën dans tout grand voyage.', brand: 'Citroën', difficulty: 'hard' },
  { slogan: 'Renault, vivez l\'expérience.', brand: 'Renault', difficulty: 'hard' },
  { slogan: 'Avec EDF, vous avez tout pour être bien.', brand: 'EDF', difficulty: 'hard' },
  { slogan: 'L\'énergie est notre avenir, économisons-la !', brand: 'EDF', difficulty: 'hard' },
  { slogan: 'Vous ne viendrez plus chez nous par hasard.', brand: 'Galeries Lafayette', difficulty: 'hard' },
  { slogan: 'Il se passe toujours quelque chose aux Galeries Lafayette.', brand: 'Galeries Lafayette', difficulty: 'hard' },
  { slogan: 'Le vrai goût des bonnes choses.', brand: 'Lipton', difficulty: 'hard' },
  { slogan: 'Le moins cher des sandwichs au monde.', brand: 'La Vache qui rit', difficulty: 'hard' },
  { slogan: 'Le fromage qui sourit.', brand: 'La Vache qui rit', difficulty: 'hard' },
  { slogan: 'À l\'eau, c\'est l\'eau Évian.', brand: 'Évian', difficulty: 'hard' },
  { slogan: 'Un parfum d\'aventure.', brand: 'Old Spice', difficulty: 'hard' },
  { slogan: 'Lipton Ice Tea, drink positive.', brand: 'Lipton', difficulty: 'hard' },
  { slogan: 'L\'Italie en moi.', brand: 'Buitoni', difficulty: 'hard' },
  { slogan: 'Quand y\'a du Buitoni, y\'a du génie.', brand: 'Buitoni', difficulty: 'hard' },
  { slogan: 'C\'est gonflé !', brand: 'Pampers', difficulty: 'hard' },
  { slogan: 'Le bonheur, c\'est simple comme un coup de fil.', brand: 'France Télécom', difficulty: 'hard' },
  { slogan: 'Avec Orange, ça change tout.', brand: 'Orange', difficulty: 'hard' },
  { slogan: 'Vous êtes au cœur de notre univers.', brand: 'SFR', difficulty: 'hard' },
  { slogan: 'Ariel, votre nouvelle référence en lessive.', brand: 'Ariel', difficulty: 'hard' },
  { slogan: 'Skip lave plus blanc.', brand: 'Skip', difficulty: 'hard' },
  { slogan: 'Mir adoucit les mains.', brand: 'Mir', difficulty: 'hard' },
  { slogan: 'Petit Bateau, mes premières vraies fringues.', brand: 'Petit Bateau', difficulty: 'hard' },
  { slogan: 'Le poil c\'est cool.', brand: 'Veet', difficulty: 'hard' },
  { slogan: 'Le café qui réveille.', brand: 'Carte Noire', difficulty: 'hard' },
  { slogan: 'Ariel, tu peux faire confiance à Ariel.', brand: 'Ariel', difficulty: 'hard' },
  { slogan: 'Du pétrole, mais pas seulement.', brand: 'Total', difficulty: 'hard' },
  { slogan: 'Vous ne regarderez plus jamais la télé comme avant.', brand: 'Canal+', difficulty: 'hard' },
  { slogan: 'Canal, c\'est plus.', brand: 'Canal+', difficulty: 'hard' },
  { slogan: 'Le confort, c\'est notre métier.', brand: 'But', difficulty: 'hard' },
  { slogan: 'But arrange tout ça.', brand: 'But', difficulty: 'hard' },
  { slogan: 'Les routiers sont sympas.', brand: 'Routiers', difficulty: 'hard' },
  { slogan: 'Tassimo, et toute la magie du café opère.', brand: 'Tassimo', difficulty: 'hard' },
  { slogan: 'Senseo, le plaisir d\'un vrai café.', brand: 'Senseo', difficulty: 'hard' },
  { slogan: 'Nespresso, what else ?', brand: 'Nespresso', difficulty: 'hard' },
  { slogan: 'Saint-Yorre, ça va fort !', brand: 'Saint-Yorre', difficulty: 'hard' },
  { slogan: 'Badoit, plus pétillante on n\'a pas trouvé.', brand: 'Badoit', difficulty: 'hard' },
  { slogan: 'Ne dites plus jamais merci.', brand: 'Société Générale', difficulty: 'hard' },
  { slogan: 'Conjuguer vos intérêts au quotidien.', brand: 'Société Générale', difficulty: 'hard' },
  { slogan: 'Une banque qui appartient à ses clients, ça change tout.', brand: 'Crédit Mutuel', difficulty: 'hard' },
  { slogan: 'La banque à qui parler.', brand: 'LCL', difficulty: 'hard' },
  { slogan: 'Crédit Agricole, le bon sens a de l\'avenir.', brand: 'Crédit Agricole', difficulty: 'hard' },
  { slogan: 'AXA, redéfinissons les standards.', brand: 'AXA', difficulty: 'hard' },
  { slogan: 'Allianz, vous êtes plus que rassuré.', brand: 'Allianz', difficulty: 'hard' },
];
