/**
 * Catalogue des champions LoL pour le Quiz du CEO.
 * Généré par `scripts/download-lol-champions.ts` — ne pas éditer à la main.
 *
 * Source : Riot Data Dragon (champion.json fr_FR) + Community Dragon (splash arts).
 * Les images sont sous `public/lol-champions/<id>.jpg` (1280x720 JPEG).
 */

export interface LolChampion {
  /** Slug minuscule = nom de fichier sans extension. ex: "aatrox" */
  id: string;
  /** Nom officiel FR. ex: "Aatrox" */
  name: string;
  /** Titre du champion. ex: "Épée des Darkin" */
  title: string;
}

export const LOL_CHAMPIONS: readonly LolChampion[] = [
  { id: "aatrox", name: "Aatrox", title: "Épée des Darkin" },
  { id: "ahri", name: "Ahri", title: "Renarde à neuf queues" },
  { id: "akali", name: "Akali", title: "Assassine rebelle" },
  { id: "akshan", name: "Akshan", title: "Sentinelle rebelle" },
  { id: "alistar", name: "Alistar", title: "Minotaure" },
  { id: "ambessa", name: "Ambessa", title: "Matriarche de guerre" },
  { id: "amumu", name: "Amumu", title: "Momie mélancolique" },
  { id: "anivia", name: "Anivia", title: "Cryophénix" },
  { id: "annie", name: "Annie", title: "Enfant des ténèbres" },
  { id: "aphelios", name: "Aphelios", title: "Arme des Lunaris" },
  { id: "ashe", name: "Ashe", title: "Archère de givre" },
  { id: "aurelionsol", name: "Aurelion Sol", title: "Forgeur d'étoiles" },
  { id: "aurora", name: "Aurora", title: "Sorcière d'entre les mondes" },
  { id: "azir", name: "Azir", title: "Empereur des sables" },
  { id: "bard", name: "Bard", title: "Gardien errant" },
  { id: "belveth", name: "Bel'Veth", title: "Impératrice du Néant" },
  { id: "blitzcrank", name: "Blitzcrank", title: "Golem de vapeur" },
  { id: "brand", name: "Brand", title: "Vengeur flamboyant" },
  { id: "braum", name: "Braum", title: "Cœur de Freljord" },
  { id: "briar", name: "Briar", title: "Faim insatiable" },
  { id: "caitlyn", name: "Caitlyn", title: "Shérif de Piltover" },
  { id: "camille", name: "Camille", title: "Ombre d'acier" },
  { id: "cassiopeia", name: "Cassiopeia", title: "Étreinte du serpent" },
  { id: "chogath", name: "Cho'Gath", title: "Terreur noire" },
  { id: "corki", name: "Corki", title: "Artilleur téméraire" },
  { id: "darius", name: "Darius", title: "Main de Noxus" },
  { id: "diana", name: "Diana", title: "Mépris de la lune" },
  { id: "draven", name: "Draven", title: "Glorieux exécuteur" },
  { id: "drmundo", name: "Dr. Mundo", title: "Dément de Zaun" },
  { id: "ekko", name: "Ekko", title: "Fractureur du temps" },
  { id: "elise", name: "Elise", title: "Reine araignée" },
  { id: "evelynn", name: "Evelynn", title: "Démon sadique" },
  { id: "ezreal", name: "Ezreal", title: "Explorateur prodigue" },
  { id: "fiddlesticks", name: "Fiddlesticks", title: "Effroi nocturne" },
  { id: "fiora", name: "Fiora", title: "Sublime bretteuse" },
  { id: "fizz", name: "Fizz", title: "Filou des mers" },
  { id: "galio", name: "Galio", title: "Colosse" },
  { id: "gangplank", name: "Gangplank", title: "Fléau des mers" },
  { id: "garen", name: "Garen", title: "Force de Demacia" },
  { id: "gnar", name: "Gnar", title: "Chaînon manquant" },
  { id: "gragas", name: "Gragas", title: "Agitateur" },
  { id: "graves", name: "Graves", title: "Hors-la-loi" },
  { id: "gwen", name: "Gwen", title: "Couturière sacrée" },
  { id: "hecarim", name: "Hecarim", title: "Ombre de la guerre" },
  { id: "heimerdinger", name: "Heimerdinger", title: "Inventeur réputé" },
  { id: "hwei", name: "Hwei", title: "Visionnaire" },
  { id: "illaoi", name: "Illaoi", title: "Prêtresse du kraken" },
  { id: "irelia", name: "Irelia", title: "Danseuse des lames" },
  { id: "ivern", name: "Ivern", title: "Aîné de la forêt" },
  { id: "janna", name: "Janna", title: "Avatar de l'air" },
  { id: "jarvaniv", name: "Jarvan IV", title: "Exemple demacien" },
  { id: "jax", name: "Jax", title: "Maître d'armes" },
  { id: "jayce", name: "Jayce", title: "Protecteur du futur" },
  { id: "jhin", name: "Jhin", title: "Virtuose" },
  { id: "jinx", name: "Jinx", title: "Gâchette folle" },
  { id: "kaisa", name: "Kai'Sa", title: "Fille du Néant" },
  { id: "kalista", name: "Kalista", title: "Lance de la vengeance" },
  { id: "karma", name: "Karma", title: "Sagesse incarnée" },
  { id: "karthus", name: "Karthus", title: "Liche" },
  { id: "kassadin", name: "Kassadin", title: "Chasseur du Néant" },
  { id: "katarina", name: "Katarina", title: "Lame sinistre" },
  { id: "kayle", name: "Kayle", title: "Vertueuse" },
  { id: "kayn", name: "Kayn", title: "Faucheur de l'ombre" },
  { id: "kennen", name: "Kennen", title: "Cœur de la tempête" },
  { id: "khazix", name: "Kha'Zix", title: "Faucheur du Néant" },
  { id: "kindred", name: "Kindred", title: "Chasseurs éternels" },
  { id: "kled", name: "Kled", title: "Cavalier colérique" },
  { id: "kogmaw", name: "Kog'Maw", title: "Gueule des abysses" },
  { id: "ksante", name: "K'Santé", title: "Fierté de Nazumah" },
  { id: "leblanc", name: "LeBlanc", title: "Manipulatrice" },
  { id: "leesin", name: "Lee Sin", title: "Moine aveugle" },
  { id: "leona", name: "Leona", title: "Aube radieuse" },
  { id: "lillia", name: "Lillia", title: "Fleur timide" },
  { id: "lissandra", name: "Lissandra", title: "Sorcière de glace" },
  { id: "lucian", name: "Lucian", title: "Purificateur" },
  { id: "lulu", name: "Lulu", title: "Sorcière féérique" },
  { id: "lux", name: "Lux", title: "Dame de lumière" },
  { id: "malphite", name: "Malphite", title: "Éclat du monolithe" },
  { id: "malzahar", name: "Malzahar", title: "Prophète du Néant" },
  { id: "maokai", name: "Maokai", title: "Tréant torturé" },
  { id: "masteryi", name: "Maître Yi", title: "Fine lame Wuju" },
  { id: "mel", name: "Mel", title: "Reflet de l'âme" },
  { id: "milio", name: "Milio", title: "Douce flamme" },
  { id: "missfortune", name: "Miss Fortune", title: "Chasseuse de primes" },
  { id: "monkeyking", name: "Wukong", title: "Roi des singes" },
  { id: "mordekaiser", name: "Mordekaiser", title: "Revenant de fer" },
  { id: "morgana", name: "Morgana", title: "Déchue" },
  { id: "naafiri", name: "Naafiri", title: "la meute de fer" },
  { id: "nami", name: "Nami", title: "Aquamancienne" },
  { id: "nasus", name: "Nasus", title: "Gardien des sables" },
  { id: "nautilus", name: "Nautilus", title: "Titan des profondeurs" },
  { id: "neeko", name: "Neeko", title: "Caméléon curieux" },
  { id: "nidalee", name: "Nidalee", title: "Chasseresse bestiale" },
  { id: "nilah", name: "Nilah", title: "Joie incarnée" },
  { id: "nocturne", name: "Nocturne", title: "Éternel cauchemar" },
  { id: "nunu", name: "Nunu et Willump", title: "Le Garçon et son yéti" },
  { id: "olaf", name: "Olaf", title: "Berzerker" },
  { id: "orianna", name: "Orianna", title: "Demoiselle mécanique" },
  { id: "ornn", name: "Ornn", title: "Dieu de la forge volcanique" },
  { id: "pantheon", name: "Pantheon", title: "Lance éternelle" },
  { id: "poppy", name: "Poppy", title: "Gardienne du marteau" },
  { id: "pyke", name: "Pyke", title: "Éventreur des abysses" },
  { id: "qiyana", name: "Qiyana", title: "Impératrice des éléments" },
  { id: "quinn", name: "Quinn", title: "Ailes de Demacia" },
  { id: "rakan", name: "Rakan", title: "Charmeur" },
  { id: "rammus", name: "Rammus", title: "Tatou blindé" },
  { id: "reksai", name: "Rek'Sai", title: "Traqueuse du Néant" },
  { id: "rell", name: "Rell", title: "Vierge de fer" },
  { id: "renata", name: "Renata Glasc", title: "Baronne de la chimie" },
  { id: "renekton", name: "Renekton", title: "Dévoreur des sables" },
  { id: "rengar", name: "Rengar", title: "Fier traqueur" },
  { id: "riven", name: "Riven", title: "Exilée brisée" },
  { id: "rumble", name: "Rumble", title: "Menace mécanisée" },
  { id: "ryze", name: "Ryze", title: "Mage runique" },
  { id: "samira", name: "Samira", title: "Rose du désert" },
  { id: "sejuani", name: "Sejuani", title: "Fureur du nord" },
  { id: "senna", name: "Senna", title: "Rédemptrice" },
  { id: "seraphine", name: "Séraphine", title: "Chanteuse rêveuse" },
  { id: "sett", name: "Sett", title: "Patron" },
  { id: "shaco", name: "Shaco", title: "Bouffon des ténèbres" },
  { id: "shen", name: "Shen", title: "Œil du crépuscule" },
  { id: "shyvana", name: "Shyvana", title: "Demi-dragon" },
  { id: "singed", name: "Singed", title: "Chimiste fou" },
  { id: "sion", name: "Sion", title: "Colosse mort-vivant" },
  { id: "sivir", name: "Sivir", title: "Mercenaire du désert" },
  { id: "skarner", name: "Skarner", title: "Souverain originel" },
  { id: "smolder", name: "Smolder", title: "Dragonnet flamboyant" },
  { id: "sona", name: "Sona", title: "Virtuose de la harpe" },
  { id: "soraka", name: "Soraka", title: "Enfant des étoiles" },
  { id: "swain", name: "Swain", title: "Grand général noxien" },
  { id: "sylas", name: "Sylas", title: "Révolutionnaire déchaîné" },
  { id: "syndra", name: "Syndra", title: "Souveraine obscure" },
  { id: "tahmkench", name: "Tahm Kench", title: "Roi des rivières" },
  { id: "taliyah", name: "Taliyah", title: "Tisseuse de pierres" },
  { id: "talon", name: "Talon", title: "Lame des ténèbres" },
  { id: "taric", name: "Taric", title: "Bouclier de Valoran" },
  { id: "teemo", name: "Teemo", title: "Éclaireur de Bandle" },
  { id: "thresh", name: "Thresh", title: "Garde aux chaînes" },
  { id: "tristana", name: "Tristana", title: "Canonnière yordle" },
  { id: "trundle", name: "Trundle", title: "Roi des trolls" },
  { id: "tryndamere", name: "Tryndamere", title: "Roi barbare" },
  { id: "twistedfate", name: "Twisted Fate", title: "Maître des cartes" },
  { id: "twitch", name: "Twitch", title: "Semeur de peste" },
  { id: "udyr", name: "Udyr", title: "Gardien des esprits" },
  { id: "urgot", name: "Urgot", title: "Broyeur" },
  { id: "varus", name: "Varus", title: "Flèche de la vengeance" },
  { id: "vayne", name: "Vayne", title: "Chasseresse nocturne" },
  { id: "veigar", name: "Veigar", title: "Seigneur des maléfices" },
  { id: "velkoz", name: "Vel'Koz", title: "Œil du Néant" },
  { id: "vex", name: "Vex", title: "Ombre du désespoir" },
  { id: "vi", name: "Vi", title: "Pacifieuse de Piltover" },
  { id: "viego", name: "Viego", title: "Roi déchu" },
  { id: "viktor", name: "Viktor", title: "Héraut de l'arcane" },
  { id: "vladimir", name: "Vladimir", title: "Saigneur pourpre" },
  { id: "volibear", name: "Volibear", title: "Tempête impitoyable" },
  { id: "warwick", name: "Warwick", title: "Fureur déchaînée de Zaun" },
  { id: "xayah", name: "Xayah", title: "Rebelle" },
  { id: "xerath", name: "Xerath", title: "Mage suprême" },
  { id: "xinzhao", name: "Xin Zhao", title: "Sénéchal de Demacia" },
  { id: "yasuo", name: "Yasuo", title: "Disgracié" },
  { id: "yone", name: "Yone", title: "Inoublié" },
  { id: "yorick", name: "Yorick", title: "Berger des âmes" },
  { id: "yunara", name: "Yunara", title: "Foi inébranlable" },
  { id: "yuumi", name: "Yuumi", title: "Gardienne du Grimoire" },
  { id: "zaahen", name: "Zaahen", title: "Incorruptible" },
  { id: "zac", name: "Zac", title: "Arme secrète" },
  { id: "zed", name: "Zed", title: "Maître des ombres" },
  { id: "zeri", name: "Zeri", title: "Étincelle de Zaun" },
  { id: "ziggs", name: "Ziggs", title: "Expert des Hexplosifs" },
  { id: "zilean", name: "Zilean", title: "Gardien du Temps" },
  { id: "zoe", name: "Zoé", title: "Manifestation du Crépuscule" },
  { id: "zyra", name: "Zyra", title: "Dame aux ronces" },
];

export const LOL_CHAMPION_BY_ID: Readonly<Record<string, LolChampion>> =
  Object.fromEntries(LOL_CHAMPIONS.map((c) => [c.id, c]));
