/**
 * Catalogue des icônes de sorts (Q/W/E/R + passif) des champions LoL pour
 * le Quiz du CEO — catégorie « devine le champion à partir de ses sorts ».
 * Généré par `scripts/download-lol-champion-spells.ts` — ne pas éditer.
 *
 * Source : Riot Data Dragon (champion/<Id>.json fr_FR + img/spell + img/passive).
 * Les icônes sont sous `public/lol-champion-spells/<championId>/{q,w,e,r,p}.png`
 * (PNG 64×64 transparent, ~3-5 KB chacune).
 */

export interface LolChampionSpells {
  /** Slug minuscule = nom de dossier. ex: "aatrox" */
  championId: string;
  /** Nom officiel FR. ex: "Aatrox" */
  championName: string;
  /** Titre du champion. ex: "Épée des Darkin" */
  championTitle: string;
  /** Nom du passif. */
  passiveName: string;
  /** Noms des 4 sorts dans l'ordre Q/W/E/R. */
  spellNames: { q: string; w: string; e: string; r: string };
}

export const LOL_CHAMPION_SPELLS: readonly LolChampionSpells[] = [
  {
    championId: "aatrox",
    championName: "Aatrox",
    championTitle: "Épée des Darkin",
    passiveName: "Posture du massacreur",
    spellNames: {
      q: "Épée des Darkin",
      w: "Chaînes infernales",
      e: "Ruée obscure",
      r: "Fossoyeur des mondes",
    },
  },
  {
    championId: "ahri",
    championName: "Ahri",
    championTitle: "Renarde à neuf queues",
    passiveName: "Vol essentiel",
    spellNames: {
      q: "Orbe d'illusion",
      w: "Lucioles",
      e: "Charme",
      r: "Assaut spirituel",
    },
  },
  {
    championId: "akali",
    championName: "Akali",
    championTitle: "Assassine rebelle",
    passiveName: "Marque d'assassin",
    spellNames: {
      q: "Vague de kunais",
      w: "Linceul nébuleux",
      e: "Lancer acrobatique",
      r: "Maîtrise absolue",
    },
  },
  {
    championId: "akshan",
    championName: "Akshan",
    championTitle: "Sentinelle rebelle",
    passiveName: "Fourberie",
    spellNames: {
      q: "Vengerang",
      w: "Cavalier seul",
      e: "Envolée héroïque",
      r: "Bien mérité !",
    },
  },
  {
    championId: "alistar",
    championName: "Alistar",
    championTitle: "Minotaure",
    passiveName: "Cri triomphant",
    spellNames: {
      q: "Atomisation",
      w: "Coup de tête",
      e: "Piétinement",
      r: "Volonté de fer",
    },
  },
  {
    championId: "ambessa",
    championName: "Ambessa",
    championTitle: "Matriarche de guerre",
    passiveName: "Ruée des chiens-dragons",
    spellNames: {
      q: "Frappe fourbe / Frappe fracassante",
      w: "Égide dévastatrice",
      e: "Lacération",
      r: "Exécution publique",
    },
  },
  {
    championId: "amumu",
    championName: "Amumu",
    championTitle: "Momie mélancolique",
    passiveName: "Toucher maudit",
    spellNames: {
      q: "Jet de bandelette",
      w: "Désespoir",
      e: "Colère",
      r: "Malédiction d'Amumu",
    },
  },
  {
    championId: "anivia",
    championName: "Anivia",
    championTitle: "Cryophénix",
    passiveName: "Renaissance",
    spellNames: {
      q: "Lance de glace",
      w: "Cristallisation",
      e: "Gelure",
      r: "Tempête glaciale",
    },
  },
  {
    championId: "annie",
    championName: "Annie",
    championTitle: "Enfant des ténèbres",
    passiveName: "Pyromanie",
    spellNames: {
      q: "Désintégration",
      w: "Incinération",
      e: "Bouclier en fusion",
      r: "Invocation : Tibbers",
    },
  },
  {
    championId: "aphelios",
    championName: "Aphelios",
    championTitle: "Arme des Lunaris",
    passiveName: "Le Tueur et l'Oracle",
    spellNames: {
      q: "Compétences d'arme",
      w: "Phase",
      e: "Système de file d'armes",
      r: "Veille au clair de lune",
    },
  },
  {
    championId: "ashe",
    championName: "Ashe",
    championTitle: "Archère de givre",
    passiveName: "Tir givrant",
    spellNames: {
      q: "Concentration du ranger",
      w: "Salve",
      e: "Rapace",
      r: "Flèche de cristal enchantée",
    },
  },
  {
    championId: "aurelionsol",
    championName: "Aurelion Sol",
    championTitle: "Forgeur d'étoiles",
    passiveName: "Créateur cosmique",
    spellNames: {
      q: "Souffle de lumière",
      w: "Vol astral",
      e: "Trou noir",
      r: "Étoile finale/Apocalypse",
    },
  },
  {
    championId: "aurora",
    championName: "Aurora",
    championTitle: "Sorcière d'entre les mondes",
    passiveName: "Abjuration spirituelle",
    spellNames: {
      q: "Maléfice",
      w: "Derrière le voile",
      e: "Sortilège",
      r: "Entre les mondes",
    },
  },
  {
    championId: "azir",
    championName: "Azir",
    championTitle: "Empereur des sables",
    passiveName: "Héritage de Shurima",
    spellNames: {
      q: "Sables conquérants",
      w: "Dresse-toi !",
      e: "Sables mouvants",
      r: "Partition impériale",
    },
  },
  {
    championId: "bard",
    championName: "Bard",
    championTitle: "Gardien errant",
    passiveName: "Instinct du voyageur",
    spellNames: {
      q: "Lien cosmique",
      w: "Don du gardien",
      e: "Route magique",
      r: "Destin tempéré",
    },
  },
  {
    championId: "belveth",
    championName: "Bel'Veth",
    championTitle: "Impératrice du Néant",
    passiveName: "Mer de lavande ",
    spellNames: {
      q: "Charge du Néant",
      w: "Projection cinglante",
      e: "Maelström impérial",
      r: "Banquet infini",
    },
  },
  {
    championId: "blitzcrank",
    championName: "Blitzcrank",
    championTitle: "Golem de vapeur",
    passiveName: "Barrière de mana",
    spellNames: {
      q: "Grappin propulsé",
      w: "Surcharge",
      e: "Poing d'acier",
      r: "Champ de stase",
    },
  },
  {
    championId: "brand",
    championName: "Brand",
    championTitle: "Vengeur flamboyant",
    passiveName: "Flammes",
    spellNames: {
      q: "Brûlure",
      w: "Colonne de flammes",
      e: "Conflagration",
      r: "Pyrolyse",
    },
  },
  {
    championId: "braum",
    championName: "Braum",
    championTitle: "Cœur de Freljord",
    passiveName: "Coups étourdissants",
    spellNames: {
      q: "Morsure de l'hiver",
      w: "Bouclier humain",
      e: "Incassable",
      r: "Fissure glaciale",
    },
  },
  {
    championId: "briar",
    championName: "Briar",
    championTitle: "Faim insatiable",
    passiveName: "Malédiction écarlate",
    spellNames: {
      q: "À table !",
      w: "Folie sanguinaire / Juste un croc",
      e: "Cri sanglant",
      r: "Vol mortel",
    },
  },
  {
    championId: "caitlyn",
    championName: "Caitlyn",
    championTitle: "Shérif de Piltover",
    passiveName: "Tir dans la tête",
    spellNames: {
      q: "Pacificateur de Piltover",
      w: "Piège-yordle",
      e: "Filet de calibre 90",
      r: "Tir chirurgical",
    },
  },
  {
    championId: "camille",
    championName: "Camille",
    championTitle: "Ombre d'acier",
    passiveName: "Protection modulable",
    spellNames: {
      q: "Protocole de précision",
      w: "Balayage tactique",
      e: "Grappin",
      r: "Ultimatum Hextech",
    },
  },
  {
    championId: "cassiopeia",
    championName: "Cassiopeia",
    championTitle: "Étreinte du serpent",
    passiveName: "Grâce serpentine",
    spellNames: {
      q: "Bombe nocive",
      w: "Miasmes",
      e: "Morsure fatale",
      r: "Regard de la Méduse",
    },
  },
  {
    championId: "chogath",
    championName: "Cho'Gath",
    championTitle: "Terreur noire",
    passiveName: "Carnivore",
    spellNames: {
      q: "Rupture",
      w: "Cri sauvage",
      e: "Piques vorpales",
      r: "Festin",
    },
  },
  {
    championId: "corki",
    championName: "Corki",
    championTitle: "Artilleur téméraire",
    passiveName: "Munitions Hextech",
    spellNames: {
      q: "Bombe au phosphore",
      w: "Valkyrie",
      e: "Gatling",
      r: "Barrage de projectiles",
    },
  },
  {
    championId: "darius",
    championName: "Darius",
    championTitle: "Main de Noxus",
    passiveName: "Plaie béante",
    spellNames: {
      q: "Décimation",
      w: "Estropiaison",
      e: "Crampon",
      r: "Guillotine noxienne",
    },
  },
  {
    championId: "diana",
    championName: "Diana",
    championTitle: "Mépris de la lune",
    passiveName: "Lame sélène",
    spellNames: {
      q: "Croissant lunaire",
      w: "Corps célestes",
      e: "Rush lunaire",
      r: "Attraction lunaire",
    },
  },
  {
    championId: "draven",
    championName: "Draven",
    championTitle: "Glorieux exécuteur",
    passiveName: "League of Draven",
    spellNames: {
      q: "Hache tournoyante",
      w: "Pulsion sanguinaire",
      e: "Division",
      r: "Volée mortelle",
    },
  },
  {
    championId: "drmundo",
    championName: "Dr. Mundo",
    championTitle: "Dément de Zaun",
    passiveName: "Il va où il veut",
    spellNames: {
      q: "Scie souillée",
      w: "Défibrillateur",
      e: "Contusion",
      r: "Dosage maximal",
    },
  },
  {
    championId: "ekko",
    championName: "Ekko",
    championTitle: "Fractureur du temps",
    passiveName: "RéZonance",
    spellNames: {
      q: "Rétrobang",
      w: "Convergence parallèle",
      e: "Rush déphasé",
      r: "Chronofracture",
    },
  },
  {
    championId: "elise",
    championName: "Elise",
    championTitle: "Reine araignée",
    passiveName: "Reine araignée",
    spellNames: {
      q: "Neurotoxine/Morsure venimeuse",
      w: "Araignée explosive/Frénésie symbiotique",
      e: "Cocon/Suspension",
      r: "Forme arachnéenne",
    },
  },
  {
    championId: "evelynn",
    championName: "Evelynn",
    championTitle: "Démon sadique",
    passiveName: "Ombre démoniaque",
    spellNames: {
      q: "Piques de haine",
      w: "Séduction",
      e: "Coup de fouet",
      r: "Faiseuse de veuves",
    },
  },
  {
    championId: "ezreal",
    championName: "Ezreal",
    championTitle: "Explorateur prodigue",
    passiveName: "Force grandissante",
    spellNames: {
      q: "Tir mystique",
      w: "Flux essentiel",
      e: "Transfert arcanique",
      r: "Arc térébrant",
    },
  },
  {
    championId: "fiddlesticks",
    championName: "Fiddlesticks",
    championTitle: "Effroi nocturne",
    passiveName: "Épouvantable épouvantail",
    spellNames: {
      q: "Terreur",
      w: "Moisson fructueuse",
      e: "Fauchaison",
      r: "Rafale de corbeaux",
    },
  },
  {
    championId: "fiora",
    championName: "Fiora",
    championTitle: "Sublime bretteuse",
    passiveName: "Danse de la duelliste",
    spellNames: {
      q: "Fente",
      w: "Riposte",
      e: "Botte secrète",
      r: "Défi suprême",
    },
  },
  {
    championId: "fizz",
    championName: "Fizz",
    championTitle: "Filou des mers",
    passiveName: "Combattant agile",
    spellNames: {
      q: "Frappe de l'oursin",
      w: "Trident marin",
      e: "Joueur/Filou",
      r: "Pêche au gros",
    },
  },
  {
    championId: "galio",
    championName: "Galio",
    championTitle: "Colosse",
    passiveName: "Frappe colossale",
    spellNames: {
      q: "Vents de guerre",
      w: "Bouclier de Durand",
      e: "Horion de la justice",
      r: "Entrée héroïque",
    },
  },
  {
    championId: "gangplank",
    championName: "Gangplank",
    championTitle: "Fléau des mers",
    passiveName: "Épreuve du feu",
    spellNames: {
      q: "Pourparlers",
      w: "Guérison du scorbut",
      e: "Baril de poudre",
      r: "Tir de barrage",
    },
  },
  {
    championId: "garen",
    championName: "Garen",
    championTitle: "Force de Demacia",
    passiveName: "Persévérance",
    spellNames: {
      q: "Coup décisif",
      w: "Courage",
      e: "Jugement",
      r: "Justice de Demacia",
    },
  },
  {
    championId: "gnar",
    championName: "Gnar",
    championTitle: "Chaînon manquant",
    passiveName: "Rage génique",
    spellNames: {
      q: "Jet de boomerang/Jet de rocher",
      w: "Agitation/Beigne",
      e: "Rebond/Aplatissement",
      r: "GNAR !",
    },
  },
  {
    championId: "gragas",
    championName: "Gragas",
    championTitle: "Agitateur",
    passiveName: "Tournée",
    spellNames: {
      q: "Fût roulant",
      w: "Rage d'ivrogne",
      e: "Coup de bidon",
      r: "Fût explosif",
    },
  },
  {
    championId: "graves",
    championName: "Graves",
    championTitle: "Hors-la-loi",
    passiveName: "Nouvelle destinée",
    spellNames: {
      q: "Terminus",
      w: "Écran de fumée",
      e: "Ruée vers l'or",
      r: "Dégâts collatéraux",
    },
  },
  {
    championId: "gwen",
    championName: "Gwen",
    championTitle: "Couturière sacrée",
    passiveName: "Mille coupures",
    spellNames: {
      q: "Tchac, tchac !",
      w: "Brume sacrée",
      e: "Élan incisif",
      r: "Piqûre",
    },
  },
  {
    championId: "hecarim",
    championName: "Hecarim",
    championTitle: "Ombre de la guerre",
    passiveName: "Galop",
    spellNames: {
      q: "Carnage",
      w: "Essence de la peur",
      e: "Charge dévastatrice",
      r: "Légion des ombres",
    },
  },
  {
    championId: "heimerdinger",
    championName: "Heimerdinger",
    championTitle: "Inventeur réputé",
    passiveName: "Affinité Hextech",
    spellNames: {
      q: "Tourelle H-28G Évolution",
      w: "Micro-roquettes Hextech",
      e: "Grenade électro-tempête CH-2",
      r: "AMÉLIORATION !",
    },
  },
  {
    championId: "hwei",
    championName: "Hwei",
    championTitle: "Visionnaire",
    passiveName: "Signature du Visionnaire",
    spellNames: {
      q: "Sujet : Désastres",
      w: "Sujet : Sérénités",
      e: "Sujet : Tourments",
      r: "Vision de désespoir",
    },
  },
  {
    championId: "illaoi",
    championName: "Illaoi",
    championTitle: "Prêtresse du kraken",
    passiveName: "Prophétesse d'un dieu ancestral",
    spellNames: {
      q: "Coup de tentacule",
      w: "Âpre leçon",
      e: "Épreuve de l'esprit",
      r: "Acte de foi",
    },
  },
  {
    championId: "irelia",
    championName: "Irelia",
    championTitle: "Danseuse des lames",
    passiveName: "Ferveur ionienne",
    spellNames: {
      q: "Rush fatal",
      w: "Danse de défi",
      e: "Duo parfait",
      r: "Pointe de l'avant-garde",
    },
  },
  {
    championId: "ivern",
    championName: "Ivern",
    championTitle: "Aîné de la forêt",
    passiveName: "Ami de la forêt",
    spellNames: {
      q: "Enracinement",
      w: "Main verte",
      e: "Graine à retardement",
      r: "Marguerite !",
    },
  },
  {
    championId: "janna",
    championName: "Janna",
    championTitle: "Avatar de l'air",
    passiveName: "Zéphyr",
    spellNames: {
      q: "Vent hurlant",
      w: "Alizé",
      e: "Œil du cyclone",
      r: "Mousson",
    },
  },
  {
    championId: "jarvaniv",
    championName: "Jarvan IV",
    championTitle: "Exemple demacien",
    passiveName: "Cadence martiale",
    spellNames: {
      q: "Frappe du dragon",
      w: "Égide dorée",
      e: "Étendard demacien",
      r: "Cataclysme",
    },
  },
  {
    championId: "jax",
    championName: "Jax",
    championTitle: "Maître d'armes",
    passiveName: "Acharnement",
    spellNames: {
      q: "Frappe bondissante",
      w: "Élargissement",
      e: "Contre-attaque",
      r: "Maître d'armes",
    },
  },
  {
    championId: "jayce",
    championName: "Jayce",
    championTitle: "Protecteur du futur",
    passiveName: "Capaciteur Hextech",
    spellNames: {
      q: "Direction le ciel ! / Orbe électrique",
      w: "Champ électrique / Hypercharge",
      e: "Coup foudroyant / Portail d'accélération",
      r: "Canon Mercury / Marteau Mercury",
    },
  },
  {
    championId: "jhin",
    championName: "Jhin",
    championTitle: "Virtuose",
    passiveName: "Murmure",
    spellNames: {
      q: "Grenade dansante",
      w: "Floraison mortelle",
      e: "Public captif",
      r: "Rappel de rideau",
    },
  },
  {
    championId: "jinx",
    championName: "Jinx",
    championTitle: "Gâchette folle",
    passiveName: "Enthousiasme !",
    spellNames: {
      q: "Flip flap !",
      w: "Zap !",
      e: "Pyromâcheurs !",
      r: "Super roquette de la mort !",
    },
  },
  {
    championId: "kaisa",
    championName: "Kai'Sa",
    championTitle: "Fille du Néant",
    passiveName: "Seconde peau",
    spellNames: {
      q: "Pluie d'Icathia",
      w: "Rayon du Néant",
      e: "Surpresseur",
      r: "Instinct meurtrier",
    },
  },
  {
    championId: "kalista",
    championName: "Kalista",
    championTitle: "Lance de la vengeance",
    passiveName: "Maintien martial",
    spellNames: {
      q: "Perforation",
      w: "Sentinelle",
      e: "Extirpation",
      r: "Appel du destin",
    },
  },
  {
    championId: "karma",
    championName: "Karma",
    championTitle: "Sagesse incarnée",
    passiveName: "Concentration ardente",
    spellNames: {
      q: "Flamme intérieure",
      w: "Volonté concentrée",
      e: "Exaltation",
      r: "Mantra",
    },
  },
  {
    championId: "karthus",
    championName: "Karthus",
    championTitle: "Liche",
    passiveName: "Déni de mort",
    spellNames: {
      q: "Dévastation",
      w: "Mur de douleur",
      e: "Souillure",
      r: "Requiem",
    },
  },
  {
    championId: "kassadin",
    championName: "Kassadin",
    championTitle: "Chasseur du Néant",
    passiveName: "Pierre du Néant",
    spellNames: {
      q: "Orbe du Néant",
      w: "Lame éthérée",
      e: "Pulsation",
      r: "Fissure",
    },
  },
  {
    championId: "katarina",
    championName: "Katarina",
    championTitle: "Lame sinistre",
    passiveName: "Voracité",
    spellNames: {
      q: "Lame rebondissante",
      w: "Préparation",
      e: "Shunpo",
      r: "Lotus mortel",
    },
  },
  {
    championId: "kayle",
    championName: "Kayle",
    championTitle: "Vertueuse",
    passiveName: "Ascension divine",
    spellNames: {
      q: "Incandescence",
      w: "Bénédiction céleste",
      e: "Lame de feu stellaire",
      r: "Jugement divin",
    },
  },
  {
    championId: "kayn",
    championName: "Kayn",
    championTitle: "Faucheur de l'ombre",
    passiveName: "Faux des Darkin",
    spellNames: {
      q: "Moisson cruelle",
      w: "Entaille sombre",
      e: "Passe-muraille",
      r: "Intrusion obscure",
    },
  },
  {
    championId: "kennen",
    championName: "Kennen",
    championTitle: "Cœur de la tempête",
    passiveName: "Marque de tempête",
    spellNames: {
      q: "Shuriken foudroyant",
      w: "Surtension",
      e: "Rush foudroyant",
      r: "Maelström",
    },
  },
  {
    championId: "khazix",
    championName: "Kha'Zix",
    championTitle: "Faucheur du Néant",
    passiveName: "Menace invisible",
    spellNames: {
      q: "Goût de la peur",
      w: "Pique du Néant",
      e: "Bond",
      r: "Assaut du Néant",
    },
  },
  {
    championId: "kindred",
    championName: "Kindred",
    championTitle: "Chasseurs éternels",
    passiveName: "Marque de Kindred",
    spellNames: {
      q: "Danse des flèches",
      w: "Frénésie de Loup",
      e: "Terreur mortelle",
      r: "Repos d'Agneau",
    },
  },
  {
    championId: "kled",
    championName: "Kled",
    championTitle: "Cavalier colérique",
    passiveName: "Skaarl, le Lézard froussard",
    spellNames: {
      q: "Piège à ours en laisse",
      w: "Penchant pour la violence",
      e: "Joute",
      r: "Chaaaaaaaargez !!!",
    },
  },
  {
    championId: "kogmaw",
    championName: "Kog'Maw",
    championTitle: "Gueule des abysses",
    passiveName: "Surprise d'Icathia",
    spellNames: {
      q: "Bave caustique",
      w: "Barrage bio-arcanique",
      e: "Limon du Néant",
      r: "Artillerie vivante",
    },
  },
  {
    championId: "ksante",
    championName: "K'Santé",
    championTitle: "Fierté de Nazumah",
    passiveName: "Instinct intrépide",
    spellNames: {
      q: "Coups de ntofo",
      w: "Pour Nazumah !",
      e: "Jeu de jambes",
      r: "Grand jeu",
    },
  },
  {
    championId: "leblanc",
    championName: "LeBlanc",
    championTitle: "Manipulatrice",
    passiveName: "Image miroir",
    spellNames: {
      q: "Sceau de malveillance",
      w: "Distorsion",
      e: "Chaînes éthérées",
      r: "Imitation",
    },
  },
  {
    championId: "leesin",
    championName: "Lee Sin",
    championTitle: "Moine aveugle",
    passiveName: "Rafale",
    spellNames: {
      q: "Onde sonore/Coup résonant",
      w: "Rempart/Force d'âme",
      e: "Trombe/Fracture",
      r: "Rage du dragon",
    },
  },
  {
    championId: "leona",
    championName: "Leona",
    championTitle: "Aube radieuse",
    passiveName: "Rayon de soleil",
    spellNames: {
      q: "Bouclier de l'aube",
      w: "Éclipse",
      e: "Lame du zénith",
      r: "Éruption solaire",
    },
  },
  {
    championId: "lillia",
    championName: "Lillia",
    championTitle: "Fleur timide",
    passiveName: "Bâton chargé de rêves",
    spellNames: {
      q: "Frappe fleurie",
      w: "Attention, désolée !",
      e: "Graine tournoyante",
      r: "Douce berceuse",
    },
  },
  {
    championId: "lissandra",
    championName: "Lissandra",
    championTitle: "Sorcière de glace",
    passiveName: "Emprise de la Sublimée",
    spellNames: {
      q: "Éclat de glace",
      w: "Cercle de givre",
      e: "Chemin glacial",
      r: "Tombeau polaire",
    },
  },
  {
    championId: "lucian",
    championName: "Lucian",
    championTitle: "Purificateur",
    passiveName: "Pistolero",
    spellNames: {
      q: "Lumière perforante",
      w: "Flamboiement",
      e: "Poursuite inlassable",
      r: "Déluge de balles",
    },
  },
  {
    championId: "lulu",
    championName: "Lulu",
    championTitle: "Sorcière féérique",
    passiveName: "Pix, le Compagnon féérique",
    spellNames: {
      q: "Duo éclatant",
      w: "Fantaisie",
      e: "Pix à la rescousse !",
      r: "Croissance prodigieuse",
    },
  },
  {
    championId: "lux",
    championName: "Lux",
    championTitle: "Dame de lumière",
    passiveName: "Illumination",
    spellNames: {
      q: "Entrave de lumière",
      w: "Barrière prismatique",
      e: "Anomalie radieuse",
      r: "Éclat final",
    },
  },
  {
    championId: "malphite",
    championName: "Malphite",
    championTitle: "Éclat du monolithe",
    passiveName: "Bouclier de granit",
    spellNames: {
      q: "Éclat sismique",
      w: "Coup de tonnerre",
      e: "Choc au sol",
      r: "Force indomptable",
    },
  },
  {
    championId: "malzahar",
    championName: "Malzahar",
    championTitle: "Prophète du Néant",
    passiveName: "Plan du Néant",
    spellNames: {
      q: "Appel du Néant",
      w: "Nuée du Néant",
      e: "Visions maléfiques",
      r: "Poigne du Néant",
    },
  },
  {
    championId: "maokai",
    championName: "Maokai",
    championTitle: "Tréant torturé",
    passiveName: "Sève magique",
    spellNames: {
      q: "Coup de ronces",
      w: "Croissance torturée",
      e: "Jet d'arbrisseau",
      r: "Emprise de la nature",
    },
  },
  {
    championId: "masteryi",
    championName: "Maître Yi",
    championTitle: "Fine lame Wuju",
    passiveName: "Coup double",
    spellNames: {
      q: "Assaut éclair",
      w: "Méditation",
      e: "Style Wuju",
      r: "Highlander",
    },
  },
  {
    championId: "mel",
    championName: "Mel",
    championTitle: "Reflet de l'âme",
    passiveName: "Luminescence incandescente",
    spellNames: {
      q: "Salve radieuse",
      w: "Réfutation",
      e: "Piège solaire",
      r: "Éclipse dorée",
    },
  },
  {
    championId: "milio",
    championName: "Milio",
    championTitle: "Douce flamme",
    passiveName: "Tout feu tout flamme",
    spellNames: {
      q: "Ultra méga boule de feu",
      w: "Feu de camp",
      e: "Chaud devant !",
      r: "Flammes vitales",
    },
  },
  {
    championId: "missfortune",
    championName: "Miss Fortune",
    championTitle: "Chasseuse de primes",
    passiveName: "Cœur volage",
    spellNames: {
      q: "Doublé",
      w: "Fanfaronne",
      e: "Pluie de balles",
      r: "Barrage de plomb",
    },
  },
  {
    championId: "monkeyking",
    championName: "Wukong",
    championTitle: "Roi des singes",
    passiveName: "Peau de pierre",
    spellNames: {
      q: "Écrasement",
      w: "Guerrier espiègle",
      e: "Nimbus",
      r: "Cyclone",
    },
  },
  {
    championId: "mordekaiser",
    championName: "Mordekaiser",
    championTitle: "Revenant de fer",
    passiveName: "Vortex de ténèbres",
    spellNames: {
      q: "Oblitération",
      w: "Indestructible",
      e: "Emprise funeste",
      r: "Royaume des morts",
    },
  },
  {
    championId: "morgana",
    championName: "Morgana",
    championTitle: "Déchue",
    passiveName: "Siphon d'âme",
    spellNames: {
      q: "Entrave sombre",
      w: "Tourment ténébreux",
      e: "Bouclier noir",
      r: "Chaînes spirituelles",
    },
  },
  {
    championId: "naafiri",
    championName: "Naafiri",
    championTitle: "la meute de fer",
    passiveName: "La meute s'agrandit",
    spellNames: {
      q: "Dagues des Darkin",
      w: "Appel de la meute",
      e: "Éviscération",
      r: "Hallali",
    },
  },
  {
    championId: "nami",
    championName: "Nami",
    championTitle: "Aquamancienne",
    passiveName: "Déferlantes",
    spellNames: {
      q: "Prison aqueuse",
      w: "Flux et reflux",
      e: "Bénédiction de l'Aquamancienne",
      r: "Raz-de-marée",
    },
  },
  {
    championId: "nasus",
    championName: "Nasus",
    championTitle: "Gardien des sables",
    passiveName: "Mangeur d'âmes",
    spellNames: {
      q: "Buveuse d'âmes",
      w: "Flétrissement",
      e: "Esprit enflammé",
      r: "Fureur des sables",
    },
  },
  {
    championId: "nautilus",
    championName: "Nautilus",
    championTitle: "Titan des profondeurs",
    passiveName: "Coup écrasant",
    spellNames: {
      q: "Abordage",
      w: "Colère du titan",
      e: "Répliques",
      r: "Grenade ASM",
    },
  },
  {
    championId: "neeko",
    championName: "Neeko",
    championTitle: "Caméléon curieux",
    passiveName: "Mirage inné",
    spellNames: {
      q: "Explosion florale",
      w: "Métaclonage",
      e: "Spirale épineuse",
      r: "Floraison renversante",
    },
  },
  {
    championId: "nidalee",
    championName: "Nidalee",
    championTitle: "Chasseresse bestiale",
    passiveName: "Prédateur",
    spellNames: {
      q: "Javelot / Mise à terre",
      w: "Guérilla / Bond",
      e: "Charge primale / Taillade",
      r: "Aspect du Couguar",
    },
  },
  {
    championId: "nilah",
    championName: "Nilah",
    championTitle: "Joie incarnée",
    passiveName: "Joie éternelle",
    spellNames: {
      q: "Lame fluide",
      w: "Voile de liesse",
      e: "Torrent",
      r: "Apothéose",
    },
  },
  {
    championId: "nocturne",
    championName: "Nocturne",
    championTitle: "Éternel cauchemar",
    passiveName: "Lames d'ombre",
    spellNames: {
      q: "Crépuscule",
      w: "Linceul des ténèbres",
      e: "Horreur indicible",
      r: "Paranoïa",
    },
  },
  {
    championId: "nunu",
    championName: "Nunu et Willump",
    championTitle: "Le Garçon et son yéti",
    passiveName: "Appel de Freljord",
    spellNames: {
      q: "Voracité",
      w: "Boule de neige géante !",
      e: "Rafale de boules de neige",
      r: "Zéro absolu",
    },
  },
  {
    championId: "olaf",
    championName: "Olaf",
    championTitle: "Berzerker",
    passiveName: "Rage du berzerker",
    spellNames: {
      q: "Déchireuse",
      w: "Force décuplée",
      e: "Frappe sauvage",
      r: "Ragnarok",
    },
  },
  {
    championId: "orianna",
    championName: "Orianna",
    championTitle: "Demoiselle mécanique",
    passiveName: "Remontoir",
    spellNames: {
      q: "Ordre : Attaque",
      w: "Ordre : Dissonance",
      e: "Ordre : Protection",
      r: "Ordre : Onde de choc",
    },
  },
  {
    championId: "ornn",
    championName: "Ornn",
    championTitle: "Dieu de la forge volcanique",
    passiveName: "Forgeron ambulant",
    spellNames: {
      q: "Fracture magmatique",
      w: "Fournaise",
      e: "Ruée ardente",
      r: "Appel du dieu de la forge",
    },
  },
  {
    championId: "pantheon",
    championName: "Pantheon",
    championTitle: "Lance éternelle",
    passiveName: "Ardeur mortelle",
    spellNames: {
      q: "Lance astrale",
      w: "Assaut martial",
      e: "Égide impénétrable",
      r: "Météore",
    },
  },
  {
    championId: "poppy",
    championName: "Poppy",
    championTitle: "Gardienne du marteau",
    passiveName: "Ambassadrice de fer",
    spellNames: {
      q: "Commotion",
      w: "Présence immuable",
      e: "Charge héroïque",
      r: "Verdict de la gardienne",
    },
  },
  {
    championId: "pyke",
    championName: "Pyke",
    championTitle: "Éventreur des abysses",
    passiveName: "Don des noyés",
    spellNames: {
      q: "Harponnage",
      w: "Plongée spectrale",
      e: "Ressac fantôme",
      r: "Exécution abyssale",
    },
  },
  {
    championId: "qiyana",
    championName: "Qiyana",
    championTitle: "Impératrice des éléments",
    passiveName: "Privilège royal",
    spellNames: {
      q: "Courroux élémentaire/Lame d'Ixtal",
      w: "Terraforce",
      e: "Audace",
      r: "Tour de force suprême",
    },
  },
  {
    championId: "quinn",
    championName: "Quinn",
    championTitle: "Ailes de Demacia",
    passiveName: "Busard",
    spellNames: {
      q: "Assaut aveuglant",
      w: "Œil d'aigle",
      e: "Salto",
      r: "En territoire ennemi",
    },
  },
  {
    championId: "rakan",
    championName: "Rakan",
    championTitle: "Charmeur",
    passiveName: "Plumes enchantées",
    spellNames: {
      q: "Rémige rayonnante",
      w: "Entrée triomphale",
      e: "Valse guerrière",
      r: "Danse ultime",
    },
  },
  {
    championId: "rammus",
    championName: "Rammus",
    championTitle: "Tatou blindé",
    passiveName: "Carapace cloutée",
    spellNames: {
      q: "Démolisseur",
      w: "Boule défensive",
      e: "Provocation frénétique",
      r: "Frappe ascendante",
    },
  },
  {
    championId: "reksai",
    championName: "Rek'Sai",
    championTitle: "Traqueuse du Néant",
    passiveName: "Fureur des Xer'Sai",
    spellNames: {
      q: "Courroux de la reine/Sondeur explosif",
      w: "Enfouissement/Jaillissement",
      e: "Morsure féroce/Tunnel",
      r: "Rush du Néant",
    },
  },
  {
    championId: "rell",
    championName: "Rell",
    championTitle: "Vierge de fer",
    passiveName: "Mise en pièces",
    spellNames: {
      q: "Frappe dislocatrice",
      w: "Ferromancie : Descendre en piqué",
      e: "Joute endiablée",
      r: "Tempête magnétique",
    },
  },
  {
    championId: "renata",
    championName: "Renata Glasc",
    championTitle: "Baronne de la chimie",
    passiveName: "Pression",
    spellNames: {
      q: "Poignée de main",
      w: "Patronage",
      e: "Programme de fidélité",
      r: "Prise de contrôle hostile",
    },
  },
  {
    championId: "renekton",
    championName: "Renekton",
    championTitle: "Dévoreur des sables",
    passiveName: "Règne de la colère",
    spellNames: {
      q: "Destruction des faibles",
      w: "Prédateur impitoyable",
      e: "Tranche et coupe",
      r: "Dominus",
    },
  },
  {
    championId: "rengar",
    championName: "Rengar",
    championTitle: "Fier traqueur",
    passiveName: "Prédateur invisible",
    spellNames: {
      q: "Esprit sauvage",
      w: "Rugissement",
      e: "Bolas",
      r: "Chasseur-né",
    },
  },
  {
    championId: "riven",
    championName: "Riven",
    championTitle: "Exilée brisée",
    passiveName: "Lame runique",
    spellNames: {
      q: "Ailes brisées",
      w: "Décharge de ki",
      e: "Bravoure",
      r: "Lame de l'exilée",
    },
  },
  {
    championId: "rumble",
    championName: "Rumble",
    championTitle: "Menace mécanisée",
    passiveName: "Titan de bric-à-brac",
    spellNames: {
      q: "Lance-flammes",
      w: "Bouclier recyclé",
      e: "Harpon électrique",
      r: "Éradication",
    },
  },
  {
    championId: "ryze",
    championName: "Ryze",
    championTitle: "Mage runique",
    passiveName: "Maîtrise des arcanes",
    spellNames: {
      q: "Court-circuit",
      w: "Prison runique",
      e: "Flux envoûtant",
      r: "Portail transdimensionnel",
    },
  },
  {
    championId: "samira",
    championName: "Samira",
    championTitle: "Rose du désert",
    passiveName: "Élan téméraire",
    spellNames: {
      q: "Panache",
      w: "Tourbillon de lame",
      e: "Charge sauvage",
      r: "Gâchette infernale",
    },
  },
  {
    championId: "sejuani",
    championName: "Sejuani",
    championTitle: "Fureur du nord",
    passiveName: "Fureur du nord",
    spellNames: {
      q: "Assaut arctique",
      w: "Colère de l'hiver",
      e: "Permafrost",
      r: "Prison de glace",
    },
  },
  {
    championId: "senna",
    championName: "Senna",
    championTitle: "Rédemptrice",
    passiveName: "Absolution",
    spellNames: {
      q: "Ombre perforante",
      w: "Dernière étreinte",
      e: "Malédiction de la Brume noire",
      r: "Ténèbres aveuglantes",
    },
  },
  {
    championId: "seraphine",
    championName: "Séraphine",
    championTitle: "Chanteuse rêveuse",
    passiveName: "Présence sur scène",
    spellNames: {
      q: "Note aiguë",
      w: "Son ambiophonique",
      e: "Battement",
      r: "Bis",
    },
  },
  {
    championId: "sett",
    championName: "Sett",
    championTitle: "Patron",
    passiveName: "Roi de l'arène",
    spellNames: {
      q: "Rogne",
      w: "Coup cathartique",
      e: "Casse-tête",
      r: "Le Clou du spectacle",
    },
  },
  {
    championId: "shaco",
    championName: "Shaco",
    championTitle: "Bouffon des ténèbres",
    passiveName: "Traîtrise",
    spellNames: {
      q: "Tromperie",
      w: "Boîte surprise",
      e: "Poison double",
      r: "Hallucination",
    },
  },
  {
    championId: "shen",
    championName: "Shen",
    championTitle: "Œil du crépuscule",
    passiveName: "Barrière de ki",
    spellNames: {
      q: "Assaut crépusculaire",
      w: "Refuge spirituel",
      e: "Rush des ombres",
      r: "Soutien indéfectible",
    },
  },
  {
    championId: "shyvana",
    championName: "Shyvana",
    championTitle: "Demi-dragon",
    passiveName: "Armure d'écailles",
    spellNames: {
      q: "Frappe enflammée",
      w: "Égide de feu",
      e: "Éruption",
      r: "Vol du dragon",
    },
  },
  {
    championId: "singed",
    championName: "Singed",
    championTitle: "Chimiste fou",
    passiveName: "Sillage toxique",
    spellNames: {
      q: "Piste empoisonnée",
      w: "Attrape-mouche",
      e: "Projection",
      r: "Potion de démence",
    },
  },
  {
    championId: "sion",
    championName: "Sion",
    championTitle: "Colosse mort-vivant",
    passiveName: "Gloire posthume",
    spellNames: {
      q: "Fracas meurtrier",
      w: "Feu intérieur",
      e: "Cri du tueur",
      r: "Assaut inarrêtable",
    },
  },
  {
    championId: "sivir",
    championName: "Sivir",
    championTitle: "Mercenaire du désert",
    passiveName: "Mille-pattes",
    spellNames: {
      q: "Lame boomerang",
      w: "Ricochet",
      e: "Bouclier magique",
      r: "En chasse",
    },
  },
  {
    championId: "skarner",
    championName: "Skarner",
    championTitle: "Souverain originel",
    passiveName: "Échos des vibrations",
    spellNames: {
      q: "Terre brisée/Soulèvement",
      w: "Bastion sismique",
      e: "Impact d'Ixtal",
      r: "Empalement",
    },
  },
  {
    championId: "smolder",
    championName: "Smolder",
    championTitle: "Dragonnet flamboyant",
    passiveName: "Dragon en herbe",
    spellNames: {
      q: "Boule de feu draconique",
      w: "Atchoum !",
      e: "Flap, flap, flap !",
      r: "MAMAAAN !",
    },
  },
  {
    championId: "sona",
    championName: "Sona",
    championTitle: "Virtuose de la harpe",
    passiveName: "Accord de puissance",
    spellNames: {
      q: "Hymne à la bravoure",
      w: "Aria de persévérance",
      e: "Mélodie de vélocité",
      r: "Crescendo",
    },
  },
  {
    championId: "soraka",
    championName: "Soraka",
    championTitle: "Enfant des étoiles",
    passiveName: "Salut",
    spellNames: {
      q: "Appel de l'étoile",
      w: "Infusion astrale",
      e: "Équinoxe",
      r: "Souhait",
    },
  },
  {
    championId: "swain",
    championName: "Swain",
    championTitle: "Grand général noxien",
    passiveName: "Nuée de corbeaux",
    spellNames: {
      q: "Poigne mortifère",
      w: "Œil de l'empire",
      e: "Capture",
      r: "Incarnation démoniaque",
    },
  },
  {
    championId: "sylas",
    championName: "Sylas",
    championTitle: "Révolutionnaire déchaîné",
    passiveName: "Volée de pétricite",
    spellNames: {
      q: "Croix du forçat",
      w: "Régicide",
      e: "Évasion / Enlèvement",
      r: "Détournement",
    },
  },
  {
    championId: "syndra",
    championName: "Syndra",
    championTitle: "Souveraine obscure",
    passiveName: "Transcendance",
    spellNames: {
      q: "Sphère noire",
      w: "Force de la volonté",
      e: "Dispersion des faibles",
      r: "Déchaînement de puissance",
    },
  },
  {
    championId: "tahmkench",
    championName: "Tahm Kench",
    championTitle: "Roi des rivières",
    passiveName: "Goût acquis",
    spellNames: {
      q: "Coup de langue",
      w: "Plongée abyssale",
      e: "Peau épaisse",
      r: "Dévoration",
    },
  },
  {
    championId: "taliyah",
    championName: "Taliyah",
    championTitle: "Tisseuse de pierres",
    passiveName: "Surf tellurique",
    spellNames: {
      q: "Rafale filée",
      w: "Poussée sismique",
      e: "Défilage tellurique",
      r: "Mur de la tisseuse",
    },
  },
  {
    championId: "talon",
    championName: "Talon",
    championTitle: "Lame des ténèbres",
    passiveName: "Saignée fatale",
    spellNames: {
      q: "Diplomatie noxienne",
      w: "Ratissage",
      e: "Voie de l'assassin",
      r: "Assaut ténébreux",
    },
  },
  {
    championId: "taric",
    championName: "Taric",
    championTitle: "Bouclier de Valoran",
    passiveName: "Plastronneur",
    spellNames: {
      q: "Bénédiction stellaire",
      w: "Bastion",
      e: "Éblouissement",
      r: "Lumière cosmique",
    },
  },
  {
    championId: "teemo",
    championName: "Teemo",
    championTitle: "Éclaireur de Bandle",
    passiveName: "Guérilla",
    spellNames: {
      q: "Fléchette aveuglante",
      w: "Vélocité",
      e: "Tir toxique",
      r: "Piège nocif",
    },
  },
  {
    championId: "thresh",
    championName: "Thresh",
    championTitle: "Garde aux chaînes",
    passiveName: "Damnation",
    spellNames: {
      q: "Peine capitale",
      w: "Lien des ténèbres",
      e: "Fauchage",
      r: "La cage",
    },
  },
  {
    championId: "tristana",
    championName: "Tristana",
    championTitle: "Canonnière yordle",
    passiveName: "Tir de précision",
    spellNames: {
      q: "Tir rapide",
      w: "Saut roquette",
      e: "Charge explosive",
      r: "Tir à impact",
    },
  },
  {
    championId: "trundle",
    championName: "Trundle",
    championTitle: "Roi des trolls",
    passiveName: "Tribut du roi",
    spellNames: {
      q: "Morsure",
      w: "Royaume gelé",
      e: "Montagne de glace",
      r: "Soumission",
    },
  },
  {
    championId: "tryndamere",
    championName: "Tryndamere",
    championTitle: "Roi barbare",
    passiveName: "Vague de violence",
    spellNames: {
      q: "Soif de sang",
      w: "Moquerie",
      e: "Balafre",
      r: "Rage inépuisable",
    },
  },
  {
    championId: "twistedfate",
    championName: "Twisted Fate",
    championTitle: "Maître des cartes",
    passiveName: "Dé pipé",
    spellNames: {
      q: "Atouts",
      w: "Bonne pioche",
      e: "Paquet",
      r: "Destinée",
    },
  },
  {
    championId: "twitch",
    championName: "Twitch",
    championTitle: "Semeur de peste",
    passiveName: "Venin mortel",
    spellNames: {
      q: "Embuscade",
      w: "Dose de venin",
      e: "Contamination",
      r: "Panique",
    },
  },
  {
    championId: "udyr",
    championName: "Udyr",
    championTitle: "Gardien des esprits",
    passiveName: "Canalisation des esprits",
    spellNames: {
      q: "Griffe sauvage",
      w: "Cape de fer",
      e: "Piétinement flamboyant",
      r: "Tempête spirituelle",
    },
  },
  {
    championId: "urgot",
    championName: "Urgot",
    championTitle: "Broyeur",
    passiveName: "Flammes purificatrices",
    spellNames: {
      q: "Torpille corrosive",
      w: "Géhenne",
      e: "Mépris",
      r: "Règne de la terreur",
    },
  },
  {
    championId: "varus",
    championName: "Varus",
    championTitle: "Flèche de la vengeance",
    passiveName: "Vengeance incarnée",
    spellNames: {
      q: "Flèche perforante",
      w: "Carquois meurtri",
      e: "Pluie de flèches",
      r: "Chaîne corruptrice",
    },
  },
  {
    championId: "vayne",
    championName: "Vayne",
    championTitle: "Chasseresse nocturne",
    passiveName: "Chasseresse nocturne",
    spellNames: {
      q: "Roulade",
      w: "Carreaux d'argent",
      e: "Condamnation",
      r: "Combat ultime",
    },
  },
  {
    championId: "veigar",
    championName: "Veigar",
    championTitle: "Seigneur des maléfices",
    passiveName: "Pouvoir maléfique phénoménal",
    spellNames: {
      q: "Coup malin",
      w: "Matière noire",
      e: "Profanation",
      r: "Explosion primordiale",
    },
  },
  {
    championId: "velkoz",
    championName: "Vel'Koz",
    championTitle: "Œil du Néant",
    passiveName: "Décomposition organique",
    spellNames: {
      q: "Fission du plasma",
      w: "Ouverture de faille",
      e: "Dislocation tectonique",
      r: "Désintégrateur de formes de vie",
    },
  },
  {
    championId: "vex",
    championName: "Vex",
    championTitle: "Ombre du désespoir",
    passiveName: "Malheur et Désespoir",
    spellNames: {
      q: "Mistral perdant",
      w: "Lâchez-moi !",
      e: "Ténèbres imminentes",
      r: "Déferlement d'Ombre",
    },
  },
  {
    championId: "vi",
    championName: "Vi",
    championTitle: "Pacifieuse de Piltover",
    passiveName: "Bouclier antichoc",
    spellNames: {
      q: "Brise-coffre",
      w: "Coups fracassants",
      e: "Force implacable",
      r: "Mise en demeure",
    },
  },
  {
    championId: "viego",
    championName: "Viego",
    championTitle: "Roi déchu",
    passiveName: "Assujettissement",
    spellNames: {
      q: "Lame du roi déchu",
      w: "Gueule spectrale",
      e: "Chemin tourmenté",
      r: "Cœur brisé",
    },
  },
  {
    championId: "viktor",
    championName: "Viktor",
    championTitle: "Héraut de l'arcane",
    passiveName: "Glorieuse évolution",
    spellNames: {
      q: "Siphonnage",
      w: "Champ gravitationnel",
      e: "Rayon Hextech",
      r: "Tempête arcanique",
    },
  },
  {
    championId: "vladimir",
    championName: "Vladimir",
    championTitle: "Saigneur pourpre",
    passiveName: "Pacte de sang",
    spellNames: {
      q: "Transfusion",
      w: "Bain de sang",
      e: "Vagues de sang",
      r: "Peste sanguine",
    },
  },
  {
    championId: "volibear",
    championName: "Volibear",
    championTitle: "Tempête impitoyable",
    passiveName: "Tempête impitoyable",
    spellNames: {
      q: "Coup fulgurant",
      w: "Folie mutilatrice",
      e: "Foudroiement",
      r: "Tempête incarnée",
    },
  },
  {
    championId: "warwick",
    championName: "Warwick",
    championTitle: "Fureur déchaînée de Zaun",
    passiveName: "Soif inextinguible",
    spellNames: {
      q: "Dents de la bête",
      w: "Traque sanguinaire",
      e: "Hurlement bestial",
      r: "Contrainte infinie",
    },
  },
  {
    championId: "xayah",
    championName: "Xayah",
    championTitle: "Rebelle",
    passiveName: "Plumes perçantes",
    spellNames: {
      q: "Dagues jumelles",
      w: "Plumage mortel",
      e: "Appel des lames",
      r: "Rafale de plumes",
    },
  },
  {
    championId: "xerath",
    championName: "Xerath",
    championTitle: "Mage suprême",
    passiveName: "Afflux de mana",
    spellNames: {
      q: "Rayon arcanique",
      w: "Œil de la destruction",
      e: "Orbe d'électrocution",
      r: "Rite arcanique",
    },
  },
  {
    championId: "xinzhao",
    championName: "Xin Zhao",
    championTitle: "Sénéchal de Demacia",
    passiveName: "Détermination",
    spellNames: {
      q: "Frappe des trois serres",
      w: "Vent et foudre",
      e: "Charge audacieuse",
      r: "Garde circulaire",
    },
  },
  {
    championId: "yasuo",
    championName: "Yasuo",
    championTitle: "Disgracié",
    passiveName: "Voie du vagabond",
    spellNames: {
      q: "Tempête d'acier",
      w: "Mur de vent",
      e: "Cercle tranchant",
      r: "Dernier soupir",
    },
  },
  {
    championId: "yone",
    championName: "Yone",
    championTitle: "Inoublié",
    passiveName: "Voie du chasseur",
    spellNames: {
      q: "Acier mortel",
      w: "Fendoir spirituel",
      e: "Libération spirituelle",
      r: "Destin scellé",
    },
  },
  {
    championId: "yorick",
    championName: "Yorick",
    championTitle: "Berger des âmes",
    passiveName: "Berger des âmes",
    spellNames: {
      q: "Derniers sacrements",
      w: "Sombre cortège",
      e: "Brume endeuillée",
      r: "Élégie des Îles",
    },
  },
  {
    championId: "yunara",
    championName: "Yunara",
    championTitle: "Foi inébranlable",
    passiveName: "Serment aux Terres premières",
    spellNames: {
      q: "Déchaînement spirituel",
      w: "Arc du jugement | Arc de la ruine",
      e: "Célérité des kanmei | Ombres ineffables",
      r: "Transe",
    },
  },
  {
    championId: "yuumi",
    championName: "Yuumi",
    championTitle: "Gardienne du Grimoire",
    passiveName: "Chat-maraderie",
    spellNames: {
      q: "Tête chat-sseuse",
      w: "Félin pour l'autre !",
      e: "Zouuu !",
      r: "Chat-pitre final",
    },
  },
  {
    championId: "zaahen",
    championName: "Zaahen",
    championTitle: "Incorruptible",
    passiveName: "Guerrier immortel",
    spellNames: {
      q: "Glaive des Darkin",
      w: "Retour redoutable",
      e: "Incursion dorée",
      r: "Libération inexorable",
    },
  },
  {
    championId: "zac",
    championName: "Zac",
    championTitle: "Arme secrète",
    passiveName: "Division cellulaire",
    spellNames: {
      q: "Étirements",
      w: "Matière instable",
      e: "Fronde",
      r: "Boing !",
    },
  },
  {
    championId: "zed",
    championName: "Zed",
    championTitle: "Maître des ombres",
    passiveName: "Mépris des faibles",
    spellNames: {
      q: "Shuriken-rasoir",
      w: "Ombre vivante",
      e: "Taillade des ombres",
      r: "Marque de la mort",
    },
  },
  {
    championId: "zeri",
    championName: "Zeri",
    championTitle: "Étincelle de Zaun",
    passiveName: "Batterie vivante",
    spellNames: {
      q: "Rafale",
      w: "Laser électrocuteur",
      e: "Charge ionique",
      r: "Éruption électrique",
    },
  },
  {
    championId: "ziggs",
    championName: "Ziggs",
    championTitle: "Expert des Hexplosifs",
    passiveName: "Mèche courte",
    spellNames: {
      q: "Bombe rebondissante",
      w: "Charge explosive",
      e: "Mines Hexplosives",
      r: "Méga bombe infernale",
    },
  },
  {
    championId: "zilean",
    championName: "Zilean",
    championTitle: "Gardien du Temps",
    passiveName: "Temps dans une bouteille",
    spellNames: {
      q: "Bombe à retardement",
      w: "Retour rapide",
      e: "Distorsion temporelle",
      r: "Retour temporel",
    },
  },
  {
    championId: "zoe",
    championName: "Zoé",
    championTitle: "Manifestation du Crépuscule",
    passiveName: "Plus d'étincelles !",
    spellNames: {
      q: "Astro-pong !",
      w: "Voleuse de sorts",
      e: "Bulle soporifique",
      r: "Bond dimensionnel",
    },
  },
  {
    championId: "zyra",
    championName: "Zyra",
    championTitle: "Dame aux ronces",
    passiveName: "Jardin de ronces",
    spellNames: {
      q: "Épines funestes",
      w: "Croissance incontrôlée",
      e: "Racines fixatrices",
      r: "Ronces étrangleuses",
    },
  },
];

export const LOL_CHAMPION_SPELLS_BY_ID: Readonly<
  Record<string, LolChampionSpells>
> = Object.fromEntries(LOL_CHAMPION_SPELLS.map((c) => [c.championId, c]));
