/**
 * Catalogue de panneaux de signalisation français pour le Quiz CEO type
 * `panneau-signalisation`. QCM 4 choix : signification du panneau.
 *
 * Mécanique : image SVG du panneau + 4 propositions de signification.
 * Curation manuelle des 4 choix par panneau (1 correct + 3 distractors
 * plausibles, souvent dans la même catégorie A/B/AB pour rendre le piège
 * plus serré).
 *
 * Assets : SVG depuis Wikimedia Commons via `Special:FilePath`. Les
 * panneaux français suivent une convention de nommage stable
 * `France_road_sign_<code>.svg`. Le proxy `/asset/<index>` masque l'URL au
 * client (le filename révèle le code, mais pas la signification).
 *
 * Source officielle : signalisation routière française (Code de la route),
 * documentée sur fr.wikipedia.org « Liste des panneaux de signalisation… ».
 */

export interface RoadSignEntry {
  /** Code officiel français (ex. AB1, A14, B14, C107…) — non affiché. */
  code: string;
  /** URL Wikimedia Commons SVG du panneau. */
  imageUrl: string;
  /** Signification correcte (doit figurer dans `choices`). */
  meaning: string;
  /** 4 propositions affichées au joueur. */
  choices: [string, string, string, string];
}

export const ROAD_SIGNS: RoadSignEntry[] = [
  // ───── Panneaux de danger (A) ─────
  { code: 'A2a', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_A2a.svg?width=300', meaning: 'Cassis ou dos d\'âne', choices: ['Cassis ou dos d\'âne', 'Chaussée déformée', 'Pente dangereuse', 'Ralentisseur de type dos d\'âne'] },
  { code: 'A3', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_A3.svg?width=300', meaning: 'Virage à droite', choices: ['Virage à droite', 'Virage à gauche', 'Succession de virages', 'Tournant brusque'] },
  { code: 'A4', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_A4.svg?width=300', meaning: 'Succession de virages, le premier à droite', choices: ['Succession de virages, le premier à droite', 'Virage à droite', 'Route sinueuse', 'Double virage'] },
  { code: 'A7', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_A7.svg?width=300', meaning: 'Traversée de voies de tramway', choices: ['Traversée de voies de tramway', 'Passage à niveau', 'Voie ferrée', 'Croisement avec ligne de bus'] },
  { code: 'A8', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_A8.svg?width=300', meaning: 'Passage à niveau muni de barrières', choices: ['Passage à niveau muni de barrières', 'Passage à niveau sans barrières', 'Voie ferrée à proximité', 'Croisement de tramway'] },
  { code: 'A9', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_A9.svg?width=300', meaning: 'Passage à niveau sans barrières', choices: ['Passage à niveau sans barrières', 'Passage à niveau avec barrières', 'Tramway', 'Voie sans issue'] },
  { code: 'A13a', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_A13a.svg?width=300', meaning: 'Endroit fréquenté par les enfants', choices: ['Endroit fréquenté par les enfants', 'Passage piétons', 'Sortie d\'école', 'Zone résidentielle'] },
  { code: 'A13b', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_A13b.svg?width=300', meaning: 'Passage pour piétons', choices: ['Passage pour piétons', 'Endroit fréquenté par les enfants', 'Trottoir', 'Zone piétonne'] },
  { code: 'A14', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_A14.svg?width=300', meaning: 'Autres dangers', choices: ['Autres dangers', 'Travaux', 'Chaussée glissante', 'Vent latéral'] },
  { code: 'A15a1', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_A15a1.svg?width=300', meaning: 'Passage d\'animaux domestiques', choices: ['Passage d\'animaux domestiques', 'Passage d\'animaux sauvages', 'Élevage à proximité', 'Marché aux bestiaux'] },
  { code: 'A15a2', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_A15a2.svg?width=300', meaning: 'Passage d\'animaux sauvages', choices: ['Passage d\'animaux sauvages', 'Passage d\'animaux domestiques', 'Réserve naturelle', 'Forêt'] },
  { code: 'A16', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_A16.svg?width=300', meaning: 'Descente dangereuse', choices: ['Descente dangereuse', 'Montée à forte inclinaison', 'Chaussée déformée', 'Virage en descente'] },
  { code: 'A17', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_A17.svg?width=300', meaning: 'Annonce de feux tricolores', choices: ['Annonce de feux tricolores', 'Carrefour à sens giratoire', 'Stop à 150 m', 'Cédez le passage'] },
  { code: 'A18', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_A18.svg?width=300', meaning: 'Circulation dans les deux sens', choices: ['Circulation dans les deux sens', 'Sens interdit', 'Voie unique', 'Voie réservée'] },
  { code: 'A19', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_A19.svg?width=300', meaning: 'Risque de chutes de pierres', choices: ['Risque de chutes de pierres', 'Travaux en cours', 'Chaussée glissante', 'Eboulement'] },
  { code: 'A20', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_A20.svg?width=300', meaning: 'Débouché sur un quai ou une berge', choices: ['Débouché sur un quai ou une berge', 'Voie sans issue', 'Pont mobile', 'Bac fluvial'] },
  { code: 'A21', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_A21.svg?width=300', meaning: 'Pont mobile', choices: ['Pont mobile', 'Tunnel', 'Bac fluvial', 'Chaussée rétrécie'] },
  { code: 'A23', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_A23.svg?width=300', meaning: 'Traversée d\'une aire de danger aérien', choices: ['Traversée d\'une aire de danger aérien', 'Aéroport à proximité', 'Risque de vent latéral', 'Zone militaire'] },
  { code: 'A24', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_A24.svg?width=300', meaning: 'Vent latéral', choices: ['Vent latéral', 'Tempête', 'Risque de tempête', 'Brouillard'] },
  { code: 'A25', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_A25.svg?width=300', meaning: 'Traversée d\'une aire de cyclistes', choices: ['Traversée d\'une aire de cyclistes', 'Piste cyclable', 'Voie réservée aux vélos', 'Zone partagée'] },

  // ───── Panneaux d\'interdiction (B) ─────
  { code: 'B0', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_B0.svg?width=300', meaning: 'Circulation interdite à tout véhicule dans les deux sens', choices: ['Circulation interdite à tout véhicule dans les deux sens', 'Sens interdit', 'Route barrée', 'Accès interdit aux poids lourds'] },
  { code: 'B1', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_B1.svg?width=300', meaning: 'Sens interdit', choices: ['Sens interdit', 'Circulation interdite à tout véhicule', 'Stop', 'Voie sans issue'] },
  { code: 'B2a', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_B2a.svg?width=300', meaning: 'Interdiction de tourner à gauche', choices: ['Interdiction de tourner à gauche', 'Interdiction de tourner à droite', 'Interdiction de faire demi-tour', 'Sens unique vers la droite'] },
  { code: 'B2b', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_B2b.svg?width=300', meaning: 'Interdiction de tourner à droite', choices: ['Interdiction de tourner à droite', 'Interdiction de tourner à gauche', 'Sens unique vers la gauche', 'Demi-tour interdit'] },
  { code: 'B2c', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_B2c.svg?width=300', meaning: 'Interdiction de faire demi-tour', choices: ['Interdiction de faire demi-tour', 'Interdiction de tourner à gauche', 'Sens interdit', 'Stop'] },
  { code: 'B3', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_B3.svg?width=300', meaning: 'Interdiction de dépasser', choices: ['Interdiction de dépasser', 'Fin d\'interdiction de dépasser', 'Limitation à deux files', 'Circulation à droite'] },
  { code: 'B3a', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_B3a.svg?width=300', meaning: 'Interdiction aux véhicules de plus de 3,5 tonnes de dépasser', choices: ['Interdiction aux véhicules de plus de 3,5 tonnes de dépasser', 'Interdiction de dépasser', 'Limitation aux poids lourds', 'Voie réservée aux camions'] },
  { code: 'B6a1', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_B6a1.svg?width=300', meaning: 'Stationnement interdit', choices: ['Stationnement interdit', 'Arrêt et stationnement interdits', 'Zone de stationnement payant', 'Stationnement gênant'] },
  { code: 'B6d', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_B6d.svg?width=300', meaning: 'Arrêt et stationnement interdits', choices: ['Arrêt et stationnement interdits', 'Stationnement interdit', 'Stop', 'Sens interdit'] },
  { code: 'B7a', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_B7a.svg?width=300', meaning: 'Accès interdit aux véhicules à moteur', choices: ['Accès interdit aux véhicules à moteur', 'Accès interdit aux poids lourds', 'Voie réservée aux piétons', 'Interdit sauf riverains'] },
  { code: 'B7b', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_B7b.svg?width=300', meaning: 'Accès interdit aux véhicules de transport de marchandises', choices: ['Accès interdit aux véhicules de transport de marchandises', 'Interdiction aux poids lourds', 'Limitation de tonnage', 'Voie réservée aux voitures'] },
  { code: 'B8', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_B8.svg?width=300', meaning: 'Accès interdit aux véhicules transportant des marchandises dangereuses', choices: ['Accès interdit aux véhicules transportant des marchandises dangereuses', 'Interdit aux poids lourds', 'Tunnel interdit', 'Zone industrielle'] },
  { code: 'B9a', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_B9a.svg?width=300', meaning: 'Accès interdit aux piétons', choices: ['Accès interdit aux piétons', 'Trottoir interdit', 'Passage piétons supprimé', 'Voie réservée aux véhicules'] },
  { code: 'B9b', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_B9b.svg?width=300', meaning: 'Accès interdit aux cycles', choices: ['Accès interdit aux cycles', 'Fin de piste cyclable', 'Vélos interdits aux heures de pointe', 'Vélos en sens contraire interdits'] },
  { code: 'B12', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_B12.svg?width=300', meaning: 'Accès interdit aux véhicules de plus de 3,5 tonnes', choices: ['Accès interdit aux véhicules de plus de 3,5 tonnes', 'Limitation de poids', 'Tunnel interdit', 'Pont à charge limitée'] },
  { code: 'B14', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_B14.svg?width=300', meaning: 'Limitation de vitesse', choices: ['Limitation de vitesse', 'Vitesse minimale', 'Limitation de tonnage', 'Vitesse conseillée'] },
  { code: 'B15', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_B15.svg?width=300', meaning: 'Cédez le passage à la circulation venant en sens inverse', choices: ['Cédez le passage à la circulation venant en sens inverse', 'Stop', 'Cédez le passage', 'Sens interdit'] },
  { code: 'B17', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_B17.svg?width=300', meaning: 'Limitation à un poids par essieu', choices: ['Limitation à un poids par essieu', 'Limitation de tonnage total', 'Limitation aux poids lourds', 'Limitation de hauteur'] },
  { code: 'B18a', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_B18a.svg?width=300', meaning: 'Limitation de hauteur', choices: ['Limitation de hauteur', 'Limitation de largeur', 'Limitation de tonnage', 'Limitation de longueur'] },
  { code: 'B18b', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_B18b.svg?width=300', meaning: 'Limitation de largeur', choices: ['Limitation de largeur', 'Limitation de hauteur', 'Limitation de tonnage', 'Voie rétrécie'] },
  { code: 'B19', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_B19.svg?width=300', meaning: 'Limitation de longueur', choices: ['Limitation de longueur', 'Limitation de largeur', 'Limitation de hauteur', 'Limitation de poids'] },

  // ───── Panneaux d\'obligation (B21+) ─────
  { code: 'B21a1', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_B21a1.svg?width=300', meaning: 'Obligation de tourner à droite avant le panneau', choices: ['Obligation de tourner à droite avant le panneau', 'Tourner à gauche obligatoire', 'Direction obligatoire à droite', 'Sens unique à droite'] },
  { code: 'B21a2', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_B21a2.svg?width=300', meaning: 'Obligation de tourner à gauche avant le panneau', choices: ['Obligation de tourner à gauche avant le panneau', 'Tourner à droite obligatoire', 'Direction obligatoire à gauche', 'Sens unique à gauche'] },
  { code: 'B21b', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_B21b.svg?width=300', meaning: 'Obligation de tourner à droite ou à gauche', choices: ['Obligation de tourner à droite ou à gauche', 'Carrefour à sens giratoire', 'Demi-tour obligatoire', 'Tout droit interdit'] },
  { code: 'B21c1', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_B21c1.svg?width=300', meaning: 'Obligation de continuer tout droit', choices: ['Obligation de continuer tout droit', 'Sens interdit aux virages', 'Voie unique', 'Direction Nord obligatoire'] },
  { code: 'B21d1', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_B21d1.svg?width=300', meaning: 'Contournement obligatoire par la droite', choices: ['Contournement obligatoire par la droite', 'Voie unique à droite', 'Tourner à droite obligatoire', 'Cédez le passage à droite'] },
  { code: 'B22a', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_B22a.svg?width=300', meaning: 'Piste obligatoire pour cycles', choices: ['Piste obligatoire pour cycles', 'Voie partagée', 'Trottoir cyclable', 'Cyclistes admis'] },
  { code: 'B22b', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_B22b.svg?width=300', meaning: 'Chemin obligatoire pour piétons', choices: ['Chemin obligatoire pour piétons', 'Trottoir', 'Zone piétonne', 'Piste cyclable'] },
  { code: 'B22c', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_B22c.svg?width=300', meaning: 'Chemin obligatoire pour piétons et cycles', choices: ['Chemin obligatoire pour piétons et cycles', 'Voie partagée auto-vélo', 'Zone piétonne', 'Piste cyclable séparée'] },
  { code: 'B25', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_B25.svg?width=300', meaning: 'Vitesse minimale obligatoire', choices: ['Vitesse minimale obligatoire', 'Vitesse maximale', 'Vitesse conseillée', 'Limitation de vitesse'] },
  { code: 'B27a', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_B27a.svg?width=300', meaning: 'Voie réservée aux véhicules de transport en commun', choices: ['Voie réservée aux véhicules de transport en commun', 'Voie de bus à double sens', 'Voie de tramway', 'Couloir vélo + bus'] },

  // ───── Fin d\'interdiction / fin d\'obligation ─────
  { code: 'B31', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_B31.svg?width=300', meaning: 'Fin de toutes les interdictions précédemment signalées', choices: ['Fin de toutes les interdictions précédemment signalées', 'Fin de limitation de vitesse', 'Fin d\'interdiction de dépasser', 'Reprise de la circulation normale'] },
  { code: 'B33', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_B33.svg?width=300', meaning: 'Fin de limitation de vitesse', choices: ['Fin de limitation de vitesse', 'Fin de zone 30', 'Fin d\'interdiction de dépasser', 'Reprise vitesse normale'] },
  { code: 'B34', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_B34.svg?width=300', meaning: 'Fin d\'interdiction de dépasser', choices: ['Fin d\'interdiction de dépasser', 'Dépassement autorisé', 'Fin de limitation', 'Reprise circulation normale'] },

  // ───── Panneaux d\'intersection et de priorité (AB) ─────
  { code: 'AB1', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_AB1.svg?width=300', meaning: 'Intersection où le conducteur est tenu de céder le passage aux véhicules venant de droite', choices: ['Intersection où le conducteur est tenu de céder le passage aux véhicules venant de droite', 'Stop', 'Cédez le passage', 'Carrefour à sens giratoire'] },
  { code: 'AB2', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_AB2.svg?width=300', meaning: 'Carrefour avec une route où les véhicules circulant sur celle-ci doivent céder le passage', choices: ['Carrefour avec une route où les véhicules circulant sur celle-ci doivent céder le passage', 'Voie prioritaire', 'Cédez le passage', 'Carrefour avec voie de droite prioritaire'] },
  { code: 'AB3a', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_AB3a.svg?width=300', meaning: 'Cédez le passage à l\'intersection', choices: ['Cédez le passage à l\'intersection', 'Stop', 'Priorité à droite', 'Carrefour à sens giratoire'] },
  { code: 'AB4', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_AB4.svg?width=300', meaning: 'Arrêt à l\'intersection (Stop)', choices: ['Arrêt à l\'intersection (Stop)', 'Cédez le passage', 'Priorité à droite', 'Sens interdit'] },
  { code: 'AB5', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_AB5.svg?width=300', meaning: 'Annonce de feux tricolores', choices: ['Annonce de feux tricolores', 'Stop', 'Cédez le passage', 'Carrefour à sens giratoire'] },
  { code: 'AB6', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_AB6.svg?width=300', meaning: 'Indication d\'une route à caractère prioritaire', choices: ['Indication d\'une route à caractère prioritaire', 'Fin de route prioritaire', 'Route nationale', 'Voie réservée'] },
  { code: 'AB7', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_AB7.svg?width=300', meaning: 'Fin de route à caractère prioritaire', choices: ['Fin de route à caractère prioritaire', 'Route prioritaire', 'Cédez le passage', 'Fin d\'agglomération'] },
  { code: 'AB25', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_AB25.svg?width=300', meaning: 'Carrefour à sens giratoire', choices: ['Carrefour à sens giratoire', 'Cédez le passage', 'Demi-tour obligatoire', 'Trois directions'] },

  // ───── Panneaux d\'indication (C) ─────
  { code: 'C1a', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_C1a.svg?width=300', meaning: 'Lieu aménagé pour le stationnement', choices: ['Lieu aménagé pour le stationnement', 'Aire de repos', 'Parking surveillé', 'Arrêt minute'] },
  { code: 'C5', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_C5.svg?width=300', meaning: 'Station de taxis', choices: ['Station de taxis', 'Arrêt de bus', 'Aire de covoiturage', 'Voiture de location'] },
  { code: 'C6', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_C6.svg?width=300', meaning: 'Arrêt d\'autobus', choices: ['Arrêt d\'autobus', 'Station de taxis', 'Arrêt de tramway', 'Gare routière'] },
  { code: 'C7', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_C7.svg?width=300', meaning: 'Arrêt de tramway', choices: ['Arrêt de tramway', 'Arrêt d\'autobus', 'Passage à niveau', 'Voie ferrée'] },
  { code: 'C12', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_C12.svg?width=300', meaning: 'Circulation à sens unique', choices: ['Circulation à sens unique', 'Voie réservée', 'Direction obligatoire', 'Voie unique'] },
  { code: 'C13a', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_C13a.svg?width=300', meaning: 'Impasse', choices: ['Impasse', 'Voie sans issue piétonne', 'Voie privée', 'Cul-de-sac avec sortie piéton'] },
  { code: 'C18', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_C18.svg?width=300', meaning: 'Créneau de dépassement', choices: ['Créneau de dépassement', 'Élargissement de chaussée', 'Voie auxiliaire', 'Voie de dégagement'] },
  { code: 'C20a', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_C20a.svg?width=300', meaning: 'Passage pour piétons', choices: ['Passage pour piétons', 'Trottoir', 'Zone piétonne', 'Sortie d\'école'] },
  { code: 'C24a', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_C24a.svg?width=300', meaning: 'Conditions particulières de circulation par voie', choices: ['Conditions particulières de circulation par voie', 'Indication de direction par voie', 'Voies de signalisation', 'Voie réservée aux poids lourds'] },
  { code: 'C25a', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_C25a.svg?width=300', meaning: 'Réduction du nombre de voies', choices: ['Réduction du nombre de voies', 'Élargissement de chaussée', 'Fusion de voies', 'Voie de droite supprimée'] },
  { code: 'C27', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_C27.svg?width=300', meaning: 'Surélévation de chaussée', choices: ['Surélévation de chaussée', 'Cassis', 'Ralentisseur', 'Plateau surélevé'] },
  { code: 'C28', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_C28.svg?width=300', meaning: 'Section dont l\'accès est réglementé par feux d\'affectation de voies', choices: ['Section dont l\'accès est réglementé par feux d\'affectation de voies', 'Tunnel à feux', 'Voie réversible', 'Voie auxiliaire'] },
  { code: 'C29a', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_C29a.svg?width=300', meaning: 'Tunnel', choices: ['Tunnel', 'Pont', 'Souterrain piéton', 'Passage couvert'] },
  { code: 'C50', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_C50.svg?width=300', meaning: 'Indications diverses', choices: ['Indications diverses', 'Information touristique', 'Service public', 'Aire de repos'] },
  { code: 'C107', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_C107.svg?width=300', meaning: 'Section d\'autoroute', choices: ['Section d\'autoroute', 'Voie express', 'Route à 4 voies', 'Périphérique'] },
  { code: 'C108', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_C108.svg?width=300', meaning: 'Fin d\'autoroute', choices: ['Fin d\'autoroute', 'Sortie d\'autoroute', 'Fin de voie express', 'Fin de péage'] },
  { code: 'C109', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_C109.svg?width=300', meaning: 'Section de route à accès réglementé', choices: ['Section de route à accès réglementé', 'Voie express', 'Route nationale', 'Périphérique'] },
  { code: 'C111', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_C111.svg?width=300', meaning: 'Tunnel', choices: ['Tunnel', 'Pont', 'Voie souterraine', 'Passage couvert'] },
  { code: 'C113', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_C113.svg?width=300', meaning: 'Piste ou bande cyclable conseillée et réservée aux cycles', choices: ['Piste ou bande cyclable conseillée et réservée aux cycles', 'Voie partagée vélo-piéton', 'Trottoir cyclable', 'Voie réservée aux vélos électriques'] },
  { code: 'C114', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_C114.svg?width=300', meaning: 'Fin d\'une piste ou bande cyclable conseillée et réservée', choices: ['Fin d\'une piste ou bande cyclable conseillée et réservée', 'Fin de voie cyclable', 'Reprise circulation auto', 'Fin de zone partagée'] },
  { code: 'C115', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_C115.svg?width=300', meaning: 'Voie verte', choices: ['Voie verte', 'Piste cyclable', 'Sentier de randonnée', 'Zone piétonne'] },
  { code: 'C116', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_C116.svg?width=300', meaning: 'Fin d\'une voie verte', choices: ['Fin d\'une voie verte', 'Fin de piste cyclable', 'Reprise route', 'Fin de zone piétonne'] },
  { code: 'C118', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_C118.svg?width=300', meaning: 'Aire piétonne', choices: ['Aire piétonne', 'Zone 30', 'Zone partagée', 'Voie verte'] },
  { code: 'C119', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_C119.svg?width=300', meaning: 'Sortie d\'aire piétonne', choices: ['Sortie d\'aire piétonne', 'Fin de zone 30', 'Reprise circulation', 'Fin de voie verte'] },
  { code: 'C202a', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_C202a.svg?width=300', meaning: 'Aire de repos', choices: ['Aire de repos', 'Parking', 'Aire de service', 'Restaurant routier'] },
  { code: 'C203', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_C203.svg?width=300', meaning: 'Aire de service', choices: ['Aire de service', 'Aire de repos', 'Station-service', 'Péage'] },
  { code: 'C204', imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/France_road_sign_C204.svg?width=300', meaning: 'Stationnement réservé aux personnes handicapées', choices: ['Stationnement réservé aux personnes handicapées', 'Place réservée aux femmes enceintes', 'Place famille', 'Place réservée aux résidents'] },
];
