/**
 * Catalogue de panneaux de signalisation français pour le Quiz CEO type
 * `panneau-signalisation`. QCM 4 choix : signification du panneau.
 *
 * Mécanique : image SVG du panneau + 4 propositions de signification.
 * Curation manuelle des 4 choix par panneau (1 correct + 3 distractors
 * plausibles, souvent dans la même catégorie A/B/AB pour rendre le piège
 * plus serré).
 *
 * Assets : URLs `upload.wikimedia.org` directes (CDN, pas de rate-limit).
 * Résolution faite par `scripts/audit-quiz-ceo-roadsigns.ts` qui transforme
 * les URLs `Special:FilePath` (rate-limitées) en URLs CDN via l'API
 * `imageinfo`. Re-run le script si tu ajoutes des panneaux. Le proxy
 * `/asset/<index>` masque l'URL au client (le filename révèle le code,
 * mais pas la signification).
 *
 * Source officielle : signalisation routière française (Code de la route),
 * documentée sur fr.wikipedia.org « Liste des panneaux de signalisation… ».
 */

export interface RoadSignEntry {
  /** Code officiel français (ex. AB1, A14, B14, C107…) — non affiché. */
  code: string;
  /** URL Wikimedia Commons SVG du panneau. */
  imageUrl: string;
  /** Signification correcte (doit figurer dans `choices`). */
  meaning: string;
  /** 4 propositions affichées au joueur. */
  choices: [string, string, string, string];
}

export const ROAD_SIGNS: RoadSignEntry[] = [
  // ───── Panneaux de danger (A) ─────
  { code: 'A2a', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/France_road_sign_A2a.svg/330px-France_road_sign_A2a.svg.png', meaning: 'Cassis ou dos d\'âne', choices: ['Cassis ou dos d\'âne', 'Chaussée déformée', 'Pente dangereuse', 'Ralentisseur de type dos d\'âne'] },
  { code: 'A3', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/France_road_sign_A3.svg/330px-France_road_sign_A3.svg.png', meaning: 'Virage à droite', choices: ['Virage à droite', 'Virage à gauche', 'Succession de virages', 'Tournant brusque'] },
  { code: 'A4', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/France_road_sign_A4.svg/330px-France_road_sign_A4.svg.png', meaning: 'Succession de virages, le premier à droite', choices: ['Succession de virages, le premier à droite', 'Virage à droite', 'Route sinueuse', 'Double virage'] },
  { code: 'A7', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/France_road_sign_A7.svg/330px-France_road_sign_A7.svg.png', meaning: 'Traversée de voies de tramway', choices: ['Traversée de voies de tramway', 'Passage à niveau', 'Voie ferrée', 'Croisement avec ligne de bus'] },
  { code: 'A8', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/France_road_sign_A8.svg/330px-France_road_sign_A8.svg.png', meaning: 'Passage à niveau muni de barrières', choices: ['Passage à niveau muni de barrières', 'Passage à niveau sans barrières', 'Voie ferrée à proximité', 'Croisement de tramway'] },
  { code: 'A9', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/France_road_sign_A9.svg/330px-France_road_sign_A9.svg.png', meaning: 'Passage à niveau sans barrières', choices: ['Passage à niveau sans barrières', 'Passage à niveau avec barrières', 'Tramway', 'Voie sans issue'] },
  { code: 'A13a', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/France_road_sign_A13a.svg/330px-France_road_sign_A13a.svg.png', meaning: 'Endroit fréquenté par les enfants', choices: ['Endroit fréquenté par les enfants', 'Passage piétons', 'Sortie d\'école', 'Zone résidentielle'] },
  { code: 'A13b', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/France_road_sign_A13b.svg/330px-France_road_sign_A13b.svg.png', meaning: 'Passage pour piétons', choices: ['Passage pour piétons', 'Endroit fréquenté par les enfants', 'Trottoir', 'Zone piétonne'] },
  { code: 'A14', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/France_road_sign_A14.svg/330px-France_road_sign_A14.svg.png', meaning: 'Autres dangers', choices: ['Autres dangers', 'Travaux', 'Chaussée glissante', 'Vent latéral'] },
  { code: 'A15a1', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/France_road_sign_A15a1.svg/330px-France_road_sign_A15a1.svg.png', meaning: 'Passage d\'animaux domestiques', choices: ['Passage d\'animaux domestiques', 'Passage d\'animaux sauvages', 'Élevage à proximité', 'Marché aux bestiaux'] },
  { code: 'A15a2', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/France_road_sign_A15a2.svg/330px-France_road_sign_A15a2.svg.png', meaning: 'Passage d\'animaux sauvages', choices: ['Passage d\'animaux sauvages', 'Passage d\'animaux domestiques', 'Réserve naturelle', 'Forêt'] },
  { code: 'A16', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/France_road_sign_A16.svg/330px-France_road_sign_A16.svg.png', meaning: 'Descente dangereuse', choices: ['Descente dangereuse', 'Montée à forte inclinaison', 'Chaussée déformée', 'Virage en descente'] },
  { code: 'A17', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/France_road_sign_A17.svg/330px-France_road_sign_A17.svg.png', meaning: 'Annonce de feux tricolores', choices: ['Annonce de feux tricolores', 'Carrefour à sens giratoire', 'Stop à 150 m', 'Cédez le passage'] },
  { code: 'A18', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/France_road_sign_A18.svg/330px-France_road_sign_A18.svg.png', meaning: 'Circulation dans les deux sens', choices: ['Circulation dans les deux sens', 'Sens interdit', 'Voie unique', 'Voie réservée'] },
  { code: 'A19', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/France_road_sign_A19.svg/330px-France_road_sign_A19.svg.png', meaning: 'Risque de chutes de pierres', choices: ['Risque de chutes de pierres', 'Travaux en cours', 'Chaussée glissante', 'Eboulement'] },
  { code: 'A20', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/France_road_sign_A20.svg/330px-France_road_sign_A20.svg.png', meaning: 'Débouché sur un quai ou une berge', choices: ['Débouché sur un quai ou une berge', 'Voie sans issue', 'Pont mobile', 'Bac fluvial'] },
  { code: 'A21', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/France_road_sign_A21.svg/330px-France_road_sign_A21.svg.png', meaning: 'Pont mobile', choices: ['Pont mobile', 'Tunnel', 'Bac fluvial', 'Chaussée rétrécie'] },
  { code: 'A23', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/France_road_sign_A23.svg/330px-France_road_sign_A23.svg.png', meaning: 'Traversée d\'une aire de danger aérien', choices: ['Traversée d\'une aire de danger aérien', 'Aéroport à proximité', 'Risque de vent latéral', 'Zone militaire'] },
  { code: 'A24', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/France_road_sign_A24.svg/330px-France_road_sign_A24.svg.png', meaning: 'Vent latéral', choices: ['Vent latéral', 'Tempête', 'Risque de tempête', 'Brouillard'] },
  { code: 'A25', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/France_road_sign_AB25.svg/330px-France_road_sign_AB25.svg.png', meaning: 'Traversée d\'une aire de cyclistes', choices: ['Traversée d\'une aire de cyclistes', 'Piste cyclable', 'Voie réservée aux vélos', 'Zone partagée'] },

  // ───── Panneaux d\'interdiction (B) ─────
  { code: 'B0', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/France_road_sign_B0.svg/330px-France_road_sign_B0.svg.png', meaning: 'Circulation interdite à tout véhicule dans les deux sens', choices: ['Circulation interdite à tout véhicule dans les deux sens', 'Sens interdit', 'Route barrée', 'Accès interdit aux poids lourds'] },
  { code: 'B1', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/France_road_sign_B1.svg/330px-France_road_sign_B1.svg.png', meaning: 'Sens interdit', choices: ['Sens interdit', 'Circulation interdite à tout véhicule', 'Stop', 'Voie sans issue'] },
  { code: 'B2a', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/France_road_sign_B2a.svg/330px-France_road_sign_B2a.svg.png', meaning: 'Interdiction de tourner à gauche', choices: ['Interdiction de tourner à gauche', 'Interdiction de tourner à droite', 'Interdiction de faire demi-tour', 'Sens unique vers la droite'] },
  { code: 'B2b', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/France_road_sign_B2b.svg/330px-France_road_sign_B2b.svg.png', meaning: 'Interdiction de tourner à droite', choices: ['Interdiction de tourner à droite', 'Interdiction de tourner à gauche', 'Sens unique vers la gauche', 'Demi-tour interdit'] },
  { code: 'B2c', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/France_road_sign_B2c.svg/330px-France_road_sign_B2c.svg.png', meaning: 'Interdiction de faire demi-tour', choices: ['Interdiction de faire demi-tour', 'Interdiction de tourner à gauche', 'Sens interdit', 'Stop'] },
  { code: 'B3', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/France_road_sign_B3.svg/330px-France_road_sign_B3.svg.png', meaning: 'Interdiction de dépasser', choices: ['Interdiction de dépasser', 'Fin d\'interdiction de dépasser', 'Limitation à deux files', 'Circulation à droite'] },
  { code: 'B3a', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/France_road_sign_B3a.svg/330px-France_road_sign_B3a.svg.png', meaning: 'Interdiction aux véhicules de plus de 3,5 tonnes de dépasser', choices: ['Interdiction aux véhicules de plus de 3,5 tonnes de dépasser', 'Interdiction de dépasser', 'Limitation aux poids lourds', 'Voie réservée aux camions'] },
  { code: 'B6a1', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/France_road_sign_B6a1.svg/330px-France_road_sign_B6a1.svg.png', meaning: 'Stationnement interdit', choices: ['Stationnement interdit', 'Arrêt et stationnement interdits', 'Zone de stationnement payant', 'Stationnement gênant'] },
  { code: 'B6d', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/France_road_sign_B6d.svg/330px-France_road_sign_B6d.svg.png', meaning: 'Arrêt et stationnement interdits', choices: ['Arrêt et stationnement interdits', 'Stationnement interdit', 'Stop', 'Sens interdit'] },
  { code: 'B7a', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/France_road_sign_B7a.svg/330px-France_road_sign_B7a.svg.png', meaning: 'Accès interdit aux véhicules à moteur', choices: ['Accès interdit aux véhicules à moteur', 'Accès interdit aux poids lourds', 'Voie réservée aux piétons', 'Interdit sauf riverains'] },
  { code: 'B7b', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/France_road_sign_B7b.svg/330px-France_road_sign_B7b.svg.png', meaning: 'Accès interdit aux véhicules de transport de marchandises', choices: ['Accès interdit aux véhicules de transport de marchandises', 'Interdiction aux poids lourds', 'Limitation de tonnage', 'Voie réservée aux voitures'] },
  { code: 'B8', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/France_road_sign_B8.svg/330px-France_road_sign_B8.svg.png', meaning: 'Accès interdit aux véhicules transportant des marchandises dangereuses', choices: ['Accès interdit aux véhicules transportant des marchandises dangereuses', 'Interdit aux poids lourds', 'Tunnel interdit', 'Zone industrielle'] },
  { code: 'B9a', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/France_road_sign_B9a.svg/330px-France_road_sign_B9a.svg.png', meaning: 'Accès interdit aux piétons', choices: ['Accès interdit aux piétons', 'Trottoir interdit', 'Passage piétons supprimé', 'Voie réservée aux véhicules'] },
  { code: 'B9b', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/France_road_sign_B9b.svg/330px-France_road_sign_B9b.svg.png', meaning: 'Accès interdit aux cycles', choices: ['Accès interdit aux cycles', 'Fin de piste cyclable', 'Vélos interdits aux heures de pointe', 'Vélos en sens contraire interdits'] },
  { code: 'B12', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/France_road_sign_B12.svg/330px-France_road_sign_B12.svg.png', meaning: 'Accès interdit aux véhicules de plus de 3,5 tonnes', choices: ['Accès interdit aux véhicules de plus de 3,5 tonnes', 'Limitation de poids', 'Tunnel interdit', 'Pont à charge limitée'] },
  { code: 'B14', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/France_road_sign_B14_%2850%29.svg/330px-France_road_sign_B14_%2850%29.svg.png', meaning: 'Limitation de vitesse', choices: ['Limitation de vitesse', 'Vitesse minimale', 'Limitation de tonnage', 'Vitesse conseillée'] },
  { code: 'B15', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/France_road_sign_B15.svg/330px-France_road_sign_B15.svg.png', meaning: 'Cédez le passage à la circulation venant en sens inverse', choices: ['Cédez le passage à la circulation venant en sens inverse', 'Stop', 'Cédez le passage', 'Sens interdit'] },
  { code: 'B17', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/France_road_sign_B17.svg/330px-France_road_sign_B17.svg.png', meaning: 'Limitation à un poids par essieu', choices: ['Limitation à un poids par essieu', 'Limitation de tonnage total', 'Limitation aux poids lourds', 'Limitation de hauteur'] },
  { code: 'B18a', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/France_road_sign_B18a.svg/330px-France_road_sign_B18a.svg.png', meaning: 'Limitation de hauteur', choices: ['Limitation de hauteur', 'Limitation de largeur', 'Limitation de tonnage', 'Limitation de longueur'] },
  { code: 'B18b', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/France_road_sign_B18b.svg/330px-France_road_sign_B18b.svg.png', meaning: 'Limitation de largeur', choices: ['Limitation de largeur', 'Limitation de hauteur', 'Limitation de tonnage', 'Voie rétrécie'] },
  { code: 'B19', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/France_road_sign_B19.svg/330px-France_road_sign_B19.svg.png', meaning: 'Limitation de longueur', choices: ['Limitation de longueur', 'Limitation de largeur', 'Limitation de hauteur', 'Limitation de poids'] },

  // ───── Panneaux d\'obligation (B21+) ─────
  { code: 'B21a1', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/France_road_sign_B21a1.svg/330px-France_road_sign_B21a1.svg.png', meaning: 'Obligation de tourner à droite avant le panneau', choices: ['Obligation de tourner à droite avant le panneau', 'Tourner à gauche obligatoire', 'Direction obligatoire à droite', 'Sens unique à droite'] },
  { code: 'B21a2', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/France_road_sign_B21a2.svg/330px-France_road_sign_B21a2.svg.png', meaning: 'Obligation de tourner à gauche avant le panneau', choices: ['Obligation de tourner à gauche avant le panneau', 'Tourner à droite obligatoire', 'Direction obligatoire à gauche', 'Sens unique à gauche'] },
  { code: 'B21b', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/France_road_sign_B21b.svg/330px-France_road_sign_B21b.svg.png', meaning: 'Obligation de tourner à droite ou à gauche', choices: ['Obligation de tourner à droite ou à gauche', 'Carrefour à sens giratoire', 'Demi-tour obligatoire', 'Tout droit interdit'] },
  { code: 'B21c1', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/France_road_sign_B21c1.svg/330px-France_road_sign_B21c1.svg.png', meaning: 'Obligation de continuer tout droit', choices: ['Obligation de continuer tout droit', 'Sens interdit aux virages', 'Voie unique', 'Direction Nord obligatoire'] },
  { code: 'B21d1', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/France_road_sign_B21d1.svg/330px-France_road_sign_B21d1.svg.png', meaning: 'Contournement obligatoire par la droite', choices: ['Contournement obligatoire par la droite', 'Voie unique à droite', 'Tourner à droite obligatoire', 'Cédez le passage à droite'] },
  { code: 'B22a', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/France_road_sign_B22a.svg/330px-France_road_sign_B22a.svg.png', meaning: 'Piste obligatoire pour cycles', choices: ['Piste obligatoire pour cycles', 'Voie partagée', 'Trottoir cyclable', 'Cyclistes admis'] },
  { code: 'B22b', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/France_road_sign_B22b.svg/330px-France_road_sign_B22b.svg.png', meaning: 'Chemin obligatoire pour piétons', choices: ['Chemin obligatoire pour piétons', 'Trottoir', 'Zone piétonne', 'Piste cyclable'] },
  { code: 'B22c', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/France_road_sign_B22c.svg/330px-France_road_sign_B22c.svg.png', meaning: 'Chemin obligatoire pour piétons et cycles', choices: ['Chemin obligatoire pour piétons et cycles', 'Voie partagée auto-vélo', 'Zone piétonne', 'Piste cyclable séparée'] },
  { code: 'B25', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/France_road_sign_B25_%2830%29.svg/330px-France_road_sign_B25_%2830%29.svg.png', meaning: 'Vitesse minimale obligatoire', choices: ['Vitesse minimale obligatoire', 'Vitesse maximale', 'Vitesse conseillée', 'Limitation de vitesse'] },
  { code: 'B27a', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/France_road_sign_B27a.svg/330px-France_road_sign_B27a.svg.png', meaning: 'Voie réservée aux véhicules de transport en commun', choices: ['Voie réservée aux véhicules de transport en commun', 'Voie de bus à double sens', 'Voie de tramway', 'Couloir vélo + bus'] },

  // ───── Fin d\'interdiction / fin d\'obligation ─────
  { code: 'B31', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/France_road_sign_B31.svg/330px-France_road_sign_B31.svg.png', meaning: 'Fin de toutes les interdictions précédemment signalées', choices: ['Fin de toutes les interdictions précédemment signalées', 'Fin de limitation de vitesse', 'Fin d\'interdiction de dépasser', 'Reprise de la circulation normale'] },
  { code: 'B33', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/France_road_sign_B33_%2850%29.svg/330px-France_road_sign_B33_%2850%29.svg.png', meaning: 'Fin de limitation de vitesse', choices: ['Fin de limitation de vitesse', 'Fin de zone 30', 'Fin d\'interdiction de dépasser', 'Reprise vitesse normale'] },
  { code: 'B34', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/France_road_sign_B34.svg/330px-France_road_sign_B34.svg.png', meaning: 'Fin d\'interdiction de dépasser', choices: ['Fin d\'interdiction de dépasser', 'Dépassement autorisé', 'Fin de limitation', 'Reprise circulation normale'] },

  // ───── Panneaux d\'intersection et de priorité (AB) ─────
  { code: 'AB1', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/France_road_sign_AB1.svg/330px-France_road_sign_AB1.svg.png', meaning: 'Intersection où le conducteur est tenu de céder le passage aux véhicules venant de droite', choices: ['Intersection où le conducteur est tenu de céder le passage aux véhicules venant de droite', 'Stop', 'Cédez le passage', 'Carrefour à sens giratoire'] },
  { code: 'AB2', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/France_road_sign_AB2.svg/330px-France_road_sign_AB2.svg.png', meaning: 'Carrefour avec une route où les véhicules circulant sur celle-ci doivent céder le passage', choices: ['Carrefour avec une route où les véhicules circulant sur celle-ci doivent céder le passage', 'Voie prioritaire', 'Cédez le passage', 'Carrefour avec voie de droite prioritaire'] },
  { code: 'AB3a', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/France_road_sign_AB3a.svg/330px-France_road_sign_AB3a.svg.png', meaning: 'Cédez le passage à l\'intersection', choices: ['Cédez le passage à l\'intersection', 'Stop', 'Priorité à droite', 'Carrefour à sens giratoire'] },
  { code: 'AB4', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/France_road_sign_AB4.svg/330px-France_road_sign_AB4.svg.png', meaning: 'Arrêt à l\'intersection (Stop)', choices: ['Arrêt à l\'intersection (Stop)', 'Cédez le passage', 'Priorité à droite', 'Sens interdit'] },
  { code: 'AB5', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/France_road_sign_AB5.svg/330px-France_road_sign_AB5.svg.png', meaning: 'Annonce de feux tricolores', choices: ['Annonce de feux tricolores', 'Stop', 'Cédez le passage', 'Carrefour à sens giratoire'] },
  { code: 'AB6', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/France_road_sign_AB6.svg/330px-France_road_sign_AB6.svg.png', meaning: 'Indication d\'une route à caractère prioritaire', choices: ['Indication d\'une route à caractère prioritaire', 'Fin de route prioritaire', 'Route nationale', 'Voie réservée'] },
  { code: 'AB7', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/France_road_sign_AB7.svg/330px-France_road_sign_AB7.svg.png', meaning: 'Fin de route à caractère prioritaire', choices: ['Fin de route à caractère prioritaire', 'Route prioritaire', 'Cédez le passage', 'Fin d\'agglomération'] },
  { code: 'AB25', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/France_road_sign_AB25.svg/330px-France_road_sign_AB25.svg.png', meaning: 'Carrefour à sens giratoire', choices: ['Carrefour à sens giratoire', 'Cédez le passage', 'Demi-tour obligatoire', 'Trois directions'] },

  // ───── Panneaux d\'indication (C) ─────
  { code: 'C1a', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/France_road_sign_C1a.svg/330px-France_road_sign_C1a.svg.png', meaning: 'Lieu aménagé pour le stationnement', choices: ['Lieu aménagé pour le stationnement', 'Aire de repos', 'Parking surveillé', 'Arrêt minute'] },
  { code: 'C5', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/France_road_sign_C5.svg/330px-France_road_sign_C5.svg.png', meaning: 'Station de taxis', choices: ['Station de taxis', 'Arrêt de bus', 'Aire de covoiturage', 'Voiture de location'] },
  { code: 'C6', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/France_road_sign_C6.svg/330px-France_road_sign_C6.svg.png', meaning: 'Arrêt d\'autobus', choices: ['Arrêt d\'autobus', 'Station de taxis', 'Arrêt de tramway', 'Gare routière'] },
  { code: 'C7', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Algeria_road_sign-C7.svg/330px-Algeria_road_sign-C7.svg.png', meaning: 'Arrêt de tramway', choices: ['Arrêt de tramway', 'Arrêt d\'autobus', 'Passage à niveau', 'Voie ferrée'] },
  { code: 'C12', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/France_road_sign_C12.svg/330px-France_road_sign_C12.svg.png', meaning: 'Circulation à sens unique', choices: ['Circulation à sens unique', 'Voie réservée', 'Direction obligatoire', 'Voie unique'] },
  { code: 'C13a', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/France_road_sign_C13a.svg/330px-France_road_sign_C13a.svg.png', meaning: 'Impasse', choices: ['Impasse', 'Voie sans issue piétonne', 'Voie privée', 'Cul-de-sac avec sortie piéton'] },
  { code: 'C18', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/France_road_sign_C18.svg/330px-France_road_sign_C18.svg.png', meaning: 'Créneau de dépassement', choices: ['Créneau de dépassement', 'Élargissement de chaussée', 'Voie auxiliaire', 'Voie de dégagement'] },
  { code: 'C20a', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/France_road_sign_C20a.svg/330px-France_road_sign_C20a.svg.png', meaning: 'Passage pour piétons', choices: ['Passage pour piétons', 'Trottoir', 'Zone piétonne', 'Sortie d\'école'] },
  { code: 'C24a', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/France_road_sign_C24a.svg/330px-France_road_sign_C24a.svg.png', meaning: 'Conditions particulières de circulation par voie', choices: ['Conditions particulières de circulation par voie', 'Indication de direction par voie', 'Voies de signalisation', 'Voie réservée aux poids lourds'] },
  { code: 'C25a', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/France_road_sign_C25a.svg/330px-France_road_sign_C25a.svg.png', meaning: 'Réduction du nombre de voies', choices: ['Réduction du nombre de voies', 'Élargissement de chaussée', 'Fusion de voies', 'Voie de droite supprimée'] },
  { code: 'C27', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/France_road_sign_C27.svg/330px-France_road_sign_C27.svg.png', meaning: 'Surélévation de chaussée', choices: ['Surélévation de chaussée', 'Cassis', 'Ralentisseur', 'Plateau surélevé'] },
  { code: 'C28', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/France_road_sign_C28.svg/330px-France_road_sign_C28.svg.png', meaning: 'Section dont l\'accès est réglementé par feux d\'affectation de voies', choices: ['Section dont l\'accès est réglementé par feux d\'affectation de voies', 'Tunnel à feux', 'Voie réversible', 'Voie auxiliaire'] },
  { code: 'C29a', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/France_road_sign_C29a.svg/330px-France_road_sign_C29a.svg.png', meaning: 'Tunnel', choices: ['Tunnel', 'Pont', 'Souterrain piéton', 'Passage couvert'] },
  { code: 'C50', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/France_road_sign_C50.svg/330px-France_road_sign_C50.svg.png', meaning: 'Indications diverses', choices: ['Indications diverses', 'Information touristique', 'Service public', 'Aire de repos'] },
  { code: 'C107', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/France_road_sign_C107.svg/330px-France_road_sign_C107.svg.png', meaning: 'Section d\'autoroute', choices: ['Section d\'autoroute', 'Voie express', 'Route à 4 voies', 'Périphérique'] },
  { code: 'C108', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/France_road_sign_C108.svg/330px-France_road_sign_C108.svg.png', meaning: 'Fin d\'autoroute', choices: ['Fin d\'autoroute', 'Sortie d\'autoroute', 'Fin de voie express', 'Fin de péage'] },
  { code: 'C109', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/France_road_sign_C109.svg/330px-France_road_sign_C109.svg.png', meaning: 'Section de route à accès réglementé', choices: ['Section de route à accès réglementé', 'Voie express', 'Route nationale', 'Périphérique'] },
  { code: 'C111', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/France_road_sign_C111.svg/330px-France_road_sign_C111.svg.png', meaning: 'Tunnel', choices: ['Tunnel', 'Pont', 'Voie souterraine', 'Passage couvert'] },
  { code: 'C113', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/France_road_sign_C113.svg/330px-France_road_sign_C113.svg.png', meaning: 'Piste ou bande cyclable conseillée et réservée aux cycles', choices: ['Piste ou bande cyclable conseillée et réservée aux cycles', 'Voie partagée vélo-piéton', 'Trottoir cyclable', 'Voie réservée aux vélos électriques'] },
  { code: 'C114', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/France_road_sign_C114.svg/330px-France_road_sign_C114.svg.png', meaning: 'Fin d\'une piste ou bande cyclable conseillée et réservée', choices: ['Fin d\'une piste ou bande cyclable conseillée et réservée', 'Fin de voie cyclable', 'Reprise circulation auto', 'Fin de zone partagée'] },
  { code: 'C115', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/France_road_sign_C115.svg/330px-France_road_sign_C115.svg.png', meaning: 'Voie verte', choices: ['Voie verte', 'Piste cyclable', 'Sentier de randonnée', 'Zone piétonne'] },
  { code: 'C116', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/France_road_sign_C116.svg/330px-France_road_sign_C116.svg.png', meaning: 'Fin d\'une voie verte', choices: ['Fin d\'une voie verte', 'Fin de piste cyclable', 'Reprise route', 'Fin de zone piétonne'] },
  // C118, C119, C202a, C203, C204 retirés en 2026-04-30 :
  // le naming Commons `France_road_sign_<code>.svg` ne matche pas pour ces
  // panneaux (peut-être renommés ou archivés sur Wikimedia). 84 panneaux
  // restants couvrent largement le besoin du Quiz CEO.
];
