const words = [
    {"mot":"Avion","categorie":"technologie"},
    {"mot":"Banque","categorie":"lieu"},
    {"mot":"Plage","categorie":"lieu"},
    {"mot":"Clé","categorie":"objet"},
    {"mot":"Verre","categorie":"objet"},
    {"mot":"Montagne","categorie":"nature"},
    {"mot":"Ombre","categorie":"concept"},
    {"mot":"Machine","categorie":"technologie"},
    {"mot":"Feuille","categorie":"nature"},
    {"mot":"Canon","categorie":"objet"},
    {"mot":"Couronne","categorie":"objet"},
    {"mot":"Robot","categorie":"technologie"},
    {"mot":"Tempête","categorie":"nature"},
    {"mot":"Pont","categorie":"lieu"},
    {"mot":"Pomme","categorie":"nature"},
    {"mot":"Livre","categorie":"objet"},
    {"mot":"Étoile","categorie":"nature"},
    {"mot":"Train","categorie":"technologie"},
    {"mot":"Or","categorie":"objet"},
    {"mot":"Prison","categorie":"lieu"},
    {"mot":"Carte","categorie":"objet"},
    {"mot":"Souris","categorie":"animal"},
    {"mot":"Dragon","categorie":"animal"},
    {"mot":"Police","categorie":"personnage"},
    {"mot":"Feu","categorie":"nature"},
    {"mot":"Glace","categorie":"nature"},
    {"mot":"Cercle","categorie":"concept"},
    {"mot":"Jardin","categorie":"lieu"},
    {"mot":"Docteur","categorie":"personnage"},
    {"mot":"Pirate","categorie":"personnage"},
    {"mot":"Lune","categorie":"nature"},
    {"mot":"Bateau","categorie":"technologie"},
    {"mot":"Masque","categorie":"objet"},
    {"mot":"Écran","categorie":"technologie"},
    {"mot":"Château","categorie":"lieu"},
    {"mot":"Vent","categorie":"nature"},
    {"mot":"Neige","categorie":"nature"},
    {"mot":"Tour","categorie":"lieu"},
    {"mot":"Argent","categorie":"objet"},
    {"mot":"Serpent","categorie":"animal"},
    {"mot":"Soleil","categorie":"nature"},
    {"mot":"Forêt","categorie":"nature"},
    {"mot":"Mur","categorie":"objet"},
    {"mot":"Lunettes","categorie":"objet"},
    {"mot":"Bombe","categorie":"objet"},
    {"mot":"Reine","categorie":"personnage"},
    {"mot":"Roi","categorie":"personnage"},
    {"mot":"Soldat","categorie":"personnage"},
    {"mot":"Pêche","categorie":"nature"},
    {"mot":"Fromage","categorie":"objet"},
    {"mot":"Table","categorie":"objet"},
    {"mot":"Chaîne","categorie":"objet"},
    {"mot":"Main","categorie":"objet"},
    {"mot":"Fantôme","categorie":"personnage"},
    {"mot":"Savon","categorie":"objet"},
    {"mot":"Hôpital","categorie":"lieu"},
    {"mot":"Désert","categorie":"nature"},
    {"mot":"Miroir","categorie":"objet"},
    {"mot":"Port","categorie":"lieu"},
    {"mot":"Sabre","categorie":"objet"},
    {"mot":"Vague","categorie":"nature"},
    {"mot":"Café","categorie":"objet"},
    {"mot":"Éclair","categorie":"nature"},
    {"mot":"Tunnel","categorie":"lieu"},
    {"mot":"Bougie","categorie":"objet"},
    {"mot":"Plume","categorie":"nature"},
    {"mot":"Géant","categorie":"personnage"},
    {"mot":"Nain","categorie":"personnage"},
    {"mot":"Rivière","categorie":"nature"},
    {"mot":"Clown","categorie":"personnage"},
    {"mot":"Usine","categorie":"lieu"},
    {"mot":"Satellite","categorie":"technologie"},
    {"mot":"Horloge","categorie":"objet"},
    {"mot":"Cheval","categorie":"animal"},
    {"mot":"Nuage","categorie":"nature"},
    {"mot":"Parfum","categorie":"objet"},
    {"mot":"École","categorie":"lieu"},
    {"mot":"Fil","categorie":"objet"},
    {"mot":"Caméra","categorie":"technologie"},
    {"mot":"Monstre","categorie":"personnage"},
    {"mot":"Épée","categorie":"objet"},
    {"mot":"Grotte","categorie":"lieu"},
    {"mot":"Corde","categorie":"objet"},
    {"mot":"Trésor","categorie":"objet"},
    {"mot":"Brique","categorie":"objet"},
    {"mot":"Lumière","categorie":"concept"},
    {"mot":"Aigle","categorie":"animal"},
    {"mot":"Statue","categorie":"objet"},
    {"mot":"Marteau","categorie":"objet"},
    {"mot":"Serre","categorie":"lieu"},
    {"mot":"Pyramide","categorie":"lieu"},
    {"mot":"Balcon","categorie":"lieu"},
    {"mot":"Température","categorie":"concept"},
    {"mot":"Coquillage","categorie":"nature"},
    {"mot":"Poison","categorie":"objet"},
    {"mot":"Sac","categorie":"objet"},
    {"mot":"Radar","categorie":"technologie"},
    {"mot":"Climat","categorie":"concept"},
    {"mot":"Wagon","categorie":"technologie"},
    {"mot":"Boussole","categorie":"objet"},
    {"mot":"Casque","categorie":"objet"},
    {"mot":"Crâne","categorie":"objet"},
    {"mot":"Piste","categorie":"lieu"},
    {"mot":"Aéroport","categorie":"lieu"},
    {"mot":"Costume","categorie":"objet"},
    {"mot":"Colonne","categorie":"objet"},
    {"mot":"Prairie","categorie":"nature"},
    {"mot":"Moteur","categorie":"technologie"},
    {"mot":"Moustache","categorie":"objet"},
    {"mot":"Énergie","categorie":"concept"},
    {"mot":"Fumée","categorie":"nature"},
    {"mot":"Lanterne","categorie":"objet"},
    {"mot":"Pipeline","categorie":"technologie"},
    {"mot":"Trappe","categorie":"objet"},
    {"mot":"Glacier","categorie":"nature"},
    {"mot":"Spirale","categorie":"concept"},
    {"mot":"Canard","categorie":"animal"},
    {"mot":"Barrière","categorie":"objet"},
    {"mot":"Bulle","categorie":"concept"},
    {"mot":"Cristal","categorie":"nature"},
    {"mot":"Tissu","categorie":"objet"},
    {"mot":"Fossile","categorie":"nature"},
    {"mot":"Cabane","categorie":"lieu"},
    {"mot":"Graffiti","categorie":"objet"},
    {"mot":"Balance","categorie":"objet"},
    {"mot":"Sable","categorie":"nature"},
    {"mot":"Plomb","categorie":"objet"},
    {"mot":"Ancre","categorie":"objet"},
    {"mot":"Tambour","categorie":"objet"},
    {"mot":"Bureau","categorie":"lieu"},
    {"mot":"Algorithme","categorie":"concept"},
    {"mot":"Puzzle","categorie":"objet"},
    {"mot":"Cage","categorie":"objet"},
    {"mot":"Corail","categorie":"nature"},
    {"mot":"Balle","categorie":"objet"},
    {"mot":"Circuit","categorie":"technologie"},
    {"mot":"Flèche","categorie":"objet"},
    {"mot":"Igloo","categorie":"lieu"},
    {"mot":"Falaise","categorie":"nature"},
    {"mot":"Colis","categorie":"objet"},
    {"mot":"Bouteille","categorie":"objet"},
    {"mot":"Vitrine","categorie":"objet"},
    {"mot":"Encre","categorie":"objet"},
    {"mot":"Tracteur","categorie":"technologie"},
    {"mot":"Phare","categorie":"lieu"},
    {"mot":"Éponge","categorie":"objet"},
    {"mot":"Labo","categorie":"lieu"},
    {"mot":"Plateau","categorie":"lieu"},
    {"mot":"Règle","categorie":"objet"},
    {"mot":"Labyrinthe","categorie":"lieu"},
    {"mot":"Valise","categorie":"objet"},
    {"mot":"Projecteur","categorie":"technologie"},
    {"mot":"Chiffre","categorie":"concept"},
    {"mot":"Roue","categorie":"objet"},
    {"mot":"Clavier","categorie":"technologie"},
    {"mot":"Signal","categorie":"concept"},
    {"mot":"Forgeron","categorie":"personnage"},
    {"mot":"Cactus","categorie":"nature"},
    {"mot":"Antenne","categorie":"technologie"},
    {"mot":"Plaque","categorie":"objet"},
    {"mot":"Épingle","categorie":"objet"},
    {"mot":"Drapeau","categorie":"objet"},
    {"mot":"Bassin","categorie":"lieu"},
    {"mot":"Rideau","categorie":"objet"},
    {"mot":"Squelette","categorie":"objet"},
    {"mot":"Glissière","categorie":"objet"},
    {"mot":"Voile","categorie":"objet"},
    {"mot":"Compas","categorie":"objet"},
    {"mot":"Éruption","categorie":"nature"},
    {"mot":"Coffre","categorie":"objet"},
    {"mot":"Camouflage","categorie":"concept"},
    {"mot":"Bison","categorie":"animal"},
    {"mot":"Molette","categorie":"objet"},
    {"mot":"Hologramme","categorie":"technologie"},
    {"mot":"Cabine","categorie":"lieu"},
    {"mot":"Harpon","categorie":"objet"},
    {"mot":"Trophée","categorie":"objet"},
    {"mot":"Silhouette","categorie":"concept"},
    {"mot":"Cartouche","categorie":"objet"},
    {"mot":"Sifflet","categorie":"objet"},
    {"mot":"Ruine","categorie":"lieu"},
    {"mot":"Scanner","categorie":"technologie"},
    {"mot":"Spirite","categorie":"personnage"},
    {"mot":"Dalle","categorie":"objet"},
    {"mot":"Bunker","categorie":"lieu"},
    {"mot":"Cascade","categorie":"nature"},
    {"mot":"Galaxie","categorie":"nature"},
    {"mot":"Micro","categorie":"technologie"},
    {"mot":"Sabot","categorie":"objet"},
    {"mot":"Tente","categorie":"lieu"},
    {"mot":"Câble","categorie":"objet"},
    {"mot":"Brouillard","categorie":"nature"}
];

const pseudos = [
    { "mot": "Al4r1c", "categorie": "Pseudo" },
    { "mot": "Kiru4", "categorie": "Pseudo" },
    { "mot": "Eikichi", "categorie": "Pseudo" },
    { "mot": "Tlz1", "categorie": "Pseudo" },
    { "mot": "Le Mari de Poki", "categorie": "Pseudo" },
    { "mot": "Era", "categorie": "Pseudo" },
    { "mot": "Kirua Black", "categorie": "Pseudo" },
    { "mot": "Kirua White", "categorie": "Pseudo" },
    { "mot": "Seummy", "categorie": "Pseudo" },
    { "mot": "Aku le Chaman", "categorie": "Pseudo" },
    { "mot": "YouYou", "categorie": "Pseudo" },
    { "mot": "Satowned", "categorie": "Pseudo" },
    { "mot": "Rochel", "categorie": "Pseudo" },
    { "mot": "Khana", "categorie": "Pseudo" },
    { "mot": "King Casu", "categorie": "Pseudo" },
    { "mot": "Quantique", "categorie": "Pseudo" },
    { "mot": "Matthieu", "categorie": "Pseudo" },
    { "mot": "Mathieu", "categorie": "Pseudo" },
    { "mot": "Yann", "categorie": "Pseudo" },
    { "mot": "Thomas", "categorie": "Pseudo" },
    { "mot": "Jonathan", "categorie": "Pseudo" },
    { "mot": "Vincent", "categorie": "Pseudo" },
    { "mot": "Alenvert Aishtein", "categorie": "Pseudo" }
];

const streamers = [
    { "mot": "Squeezie", "categorie": "Streamer" },
    { "mot": "Gotaga", "categorie": "Streamer" },
    { "mot": "Kamet0", "categorie": "Streamer" },
    { "mot": "JLTomy", "categorie": "Streamer" },
    { "mot": "AmineMaTue", "categorie": "Streamer" },
    { "mot": "ZeratoR", "categorie": "Streamer" },
    { "mot": "LeBouseuh", "categorie": "Streamer" },
    { "mot": "Domingo", "categorie": "Streamer" },
    { "mot": "Doigby", "categorie": "Streamer" },
    { "mot": "WankilStudio", "categorie": "Streamer" },
    { "mot": "Mickalow", "categorie": "Streamer" },
    { "mot": "Sardoche", "categorie": "Streamer" },
    { "mot": "Laink", "categorie": "Streamer" },
    { "mot": "Etoiles", "categorie": "Streamer" },
    { "mot": "Trayton", "categorie": "Streamer" },
    { "mot": "Anyme", "categorie": "Streamer" },
    { "mot": "Antoine Daniel", "categorie": "Streamer" },
    { "mot": "Baghera Jones", "categorie": "Streamer" },
    { "mot": "Michou", "categorie": "Streamer" },
    { "mot": "Inoxtag", "categorie": "Streamer" },
    { "mot": "Mastu", "categorie": "Streamer" },
    { "mot": "Byilhann", "categorie": "Streamer" },
    { "mot": "Jiraya", "categorie": "Streamer" },
    { "mot": "Horty underscore", "categorie": "Streamer" },
    { "mot": "Angle Droit", "categorie": "Streamer" },
    { "mot": "Mynthos", "categorie": "Streamer" },
    { "mot": "Bob Lennon", "categorie": "Streamer" },
    { "mot": "Ultia", "categorie": "Streamer" },
    { "mot": "Ponce", "categorie": "Streamer" },
    { "mot": "Joueur du Grenier", "categorie": "Streamer" },
    { "mot": "Samueletienne", "categorie": "Streamer" },
    { "mot": "M4F Gaming", "categorie": "Streamer" },
    { "mot": "Ultia Moman", "categorie": "Streamer" },
    { "mot": "DamDam", "categorie": "Streamer" },
    { "mot": "Gomart", "categorie": "Streamer" },
    { "mot": "Emiru", "categorie": "Streamer" },
    { "mot": "Amouranth", "categorie": "Streamer" },
    { "mot": "Pokimane", "categorie": "Streamer" },
    { "mot": "OTP LoL", "categorie": "Streamer" },
    { "mot": "CroissantStrike", "categorie": "Streamer" },
    { "mot": "TheGreatReview", "categorie": "Streamer" },
    { "mot": "Ego", "categorie": "Streamer" },
    { "mot": "DrFeelGood", "categorie": "Streamer" },
    { "mot": "LittleBigWhale", "categorie": "Streamer" },
    { "mot": "Lutti", "categorie": "Streamer" },
    { "mot": "Jean Massiet", "categorie": "Streamer" },
    { "mot": "Chips & Noi", "categorie": "Streamer" },
    { "mot": "Mister MV", "categorie": "Streamer" },
    { "mot": "Caedrel", "categorie": "Streamer" },
    { "mot": "Helydia", "categorie": "Streamer" },
    { "mot": "Rivenzi", "categorie": "Streamer" },
    { "mot": "Alphacast", "categorie": "Streamer" },
    { "mot": "Valkyrae", "categorie": "Streamer" },
    { "mot": "Gom4rt", "categorie": "Streamer" },
    { "mot": "Solary", "categorie": "Streamer" },
    { "mot": "Shaunz", "categorie": "Streamer" },
    { "mot": "Ogaming", "categorie": "Streamer" },
    { "mot": "Zevent", "categorie": "Streamer" },
    { "mot": "GP Explorer", "categorie": "Streamer" },
    { "mot": "Lestream", "categorie": "Streamer" }
];

const esport = [
    { "mot": "Vitality", "categorie": "Esport" },
    { "mot": "Karmine Corp", "categorie": "Esport" },
    { "mot": "Fnatic", "categorie": "Esport" },
    { "mot": "T1", "categorie": "Esport" },
    { "mot": "GenG", "categorie": "Esport" },
    { "mot": "KT Rolster", "categorie": "Esport" },
    { "mot": "Los Ratones", "categorie": "Esport" },
    { "mot": "G2", "categorie": "Esport" }
];

const jeux = [
    { "mot": "Super Mario Bros", "categorie": "Jeu" },
    { "mot": "Ocarina of Time", "categorie": "Jeu" },
    { "mot": "Breath of the Wild", "categorie": "Jeu" },
    { "mot": "Minecraft", "categorie": "Jeu" },
    { "mot": "GTA", "categorie": "Jeu" },
    { "mot": "Red Dead Redemption", "categorie": "Jeu" },
    { "mot": "The Witcher", "categorie": "Jeu" },
    { "mot": "Skyrim", "categorie": "Jeu" },
    { "mot": "Dark Souls", "categorie": "Jeu" },
    { "mot": "Elden Ring", "categorie": "Jeu" },
    { "mot": "Bloodborne", "categorie": "Jeu" },
    { "mot": "God of War", "categorie": "Jeu" },
    { "mot": "The Last of Us", "categorie": "Jeu" },
    { "mot": "Halo", "categorie": "Jeu" },
    { "mot": "Call of Duty", "categorie": "Jeu" },
    { "mot": "World of Warcraft", "categorie": "Jeu" },
    { "mot": "League of Legends", "categorie": "Jeu" },
    { "mot": "Counter-Strike", "categorie": "Jeu" },
    { "mot": "Clair Obscur: Expedition 33", "categorie": "Jeu" },
    { "mot": "Valorant", "categorie": "Jeu" },
    { "mot": "Fortnite", "categorie": "Jeu" },
    { "mot": "Apex Legends", "categorie": "Jeu" },
    { "mot": "PUBG", "categorie": "Jeu" },
    { "mot": "Doom", "categorie": "Jeu" },
    { "mot": "Half-Life", "categorie": "Jeu" },
    { "mot": "H1Z1", "categorie": "Jeu" },
    { "mot": "Portal", "categorie": "Jeu" },
    { "mot": "BioShock", "categorie": "Jeu" },
    { "mot": "Resident Evil", "categorie": "Jeu" },
    { "mot": "Silent Hill", "categorie": "Jeu" },
    { "mot": "Metal Gear Solid", "categorie": "Jeu" },
    { "mot": "Final Fantasy", "categorie": "Jeu" },
    { "mot": "Pokémon", "categorie": "Jeu" },
    { "mot": "Mario Kart", "categorie": "Jeu" },
    { "mot": "Animal Crossing", "categorie": "Jeu" },
    { "mot": "Mass Effect", "categorie": "Jeu" },
    { "mot": "Dragon Age", "categorie": "Jeu" },
    { "mot": "Cyberpunk 2077", "categorie": "Jeu" },
    { "mot": "Street Fighter II", "categorie": "Jeu" },
    { "mot": "Tekken", "categorie": "Jeu" },
    { "mot": "Mortal Kombat", "categorie": "Jeu" },
    { "mot": "Diablo", "categorie": "Jeu" },
    { "mot": "Hades", "categorie": "Jeu" },
    { "mot": "Hollow Knight", "categorie": "Jeu" },
    { "mot": "Celeste", "categorie": "Jeu" },
    { "mot": "Undertale", "categorie": "Jeu" },
    { "mot": "Among Us", "categorie": "Jeu" },
    { "mot": "Terraria", "categorie": "Jeu" },
    { "mot": "Stardew Valley", "categorie": "Jeu" },
    { "mot": "Sea of Thieves", "categorie": "Jeu" },
    { "mot": "Overwatch", "categorie": "Jeu" },
    { "mot": "Left 4 Dead", "categorie": "Jeu" },
    { "mot": "Dead Cells", "categorie": "Jeu" },
    { "mot": "Cuphead", "categorie": "Jeu" },
    { "mot": "Rayman Legends", "categorie": "Jeu" },
    { "mot": "Crash Bandicoot", "categorie": "Jeu" },
    { "mot": "Spyro the Dragon", "categorie": "Jeu" },
    { "mot": "Sonic the Hedgehog", "categorie": "Jeu" },
    { "mot": "Tomb Raider", "categorie": "Jeu" },
    { "mot": "Prince of Persia", "categorie": "Jeu" },
    { "mot": "Far Cry", "categorie": "Jeu" },
    { "mot": "Battlefield", "categorie": "Jeu" },
    { "mot": "FIFA", "categorie": "Jeu" },
    { "mot": "Pro Evolution Soccer", "categorie": "Jeu" },
    { "mot": "Age of Empires", "categorie": "Jeu" },
    { "mot": "StarCraft", "categorie": "Jeu" },
    { "mot": "Civilization", "categorie": "Jeu" },
    { "mot": "SimCity", "categorie": "Jeu" },
    { "mot": "The Sims", "categorie": "Jeu" },
    { "mot": "Roblox", "categorie": "Jeu" },
    { "mot": "Tetris", "categorie": "Jeu" }
];

const LoL = [
    {"mot":"Lame d'infini","categorie":"LoL"},
    {"mot":"Coiffe de Rabadon","categorie":"LoL"},
    {"mot":"Trinité","categorie":"LoL"},
    {"mot":"Ange gardien","categorie":"LoL"},
    {"mot":"Soif-de-sang","categorie":"LoL"},
    {"mot":"Gage de Sterak","categorie":"LoL"},
    {"mot":"Épée vespérale de Draktharr","categorie":"LoL"},
    {"mot":"Étreinte démoniaque","categorie":"LoL"},
    {"mot":"Bâton du vide","categorie":"LoL"},
    {"mot":"Fléau de liche","categorie":"LoL"},
    {"mot":"Danseur fantôme","categorie":"LoL"},
    {"mot":"Force de la trinité","categorie":"LoL"},
    {"mot":"Cotte épineuse","categorie":"LoL"},
    {"mot":"Cœur gelé","categorie":"LoL"},
    {"mot":"Visage spirituel","categorie":"LoL"},
    {"mot":"Hydre vorace","categorie":"LoL"},
    {"mot":"Lame du roi déchu","categorie":"LoL"},
    {"mot":"Plaque du mort","categorie":"LoL"},
    {"mot":"Morellonomicon","categorie":"LoL"},
    {"mot":"ARAM","categorie":"LoL"},
    {"mot":"Zhonya","categorie":"LoL"},
    {"mot":"Faker","categorie":"LoL"},
    {"mot":"Uzi","categorie":"LoL"},
    {"mot":"Caps","categorie":"LoL"},
    {"mot":"Rekkles","categorie":"LoL"},
    {"mot":"Perkz","categorie":"LoL"},
    {"mot":"Doublelift","categorie":"LoL"},
    {"mot":"TheShy","categorie":"LoL"},
    {"mot":"Deft","categorie":"LoL"},
    {"mot":"Bjergsen","categorie":"LoL"},
    {"mot":"Chovy","categorie":"LoL"},
    {"mot":"ShowMaker","categorie":"LoL"},
    {"mot":"Keria","categorie":"LoL"},
    {"mot":"Impact","categorie":"LoL"},
    {"mot":"Bang","categorie":"LoL"},
    {"mot":"Wolf","categorie":"LoL"},
    {"mot":"Mata","categorie":"LoL"},
    {"mot":"Ruler","categorie":"LoL"},
    {"mot":"Canyon","categorie":"LoL"},
    {"mot":"Nuguri","categorie":"LoL"},
    {"mot":"Score","categorie":"LoL"}
];

const racisme = [
    {"mot":"Bamboula","categorie":"Compliment"},
    {"mot":"Bougnoule","categorie":"Compliment"},
    {"mot":"Chintok","categorie":"Compliment"},
    {"mot":"Nigga","categorie":"Compliment"},
    {"mot":"Rital","categorie":"Compliment"},
    {"mot":"Arabe","categorie":"Compliment"},
    {"mot":"Renoi","categorie":"Compliment"},
    {"mot":"Pak pak","categorie":"Compliment"},

];



const expression = [
    {"mot":"Palala","categorie":"Discord"},
    {"mot":"J'ai bait","categorie":"Discord"},
    {"mot":"Dictateur","categorie":"Discord"},
    {"mot":"Kardashian","categorie":"Discord"},
    {"mot":"Carglass","categorie":"Discord"},
    {"mot":"Rasengan","categorie":"Discord"},
    {"mot":"Shudaderu","categorie":"Discord"},
    {"mot":"Toulouuuuse","categorie":"Discord"},
    {"mot":"Jennie","categorie":"Discord"},
    {"mot":"Espagnolette","categorie":"Discord"},
    {"mot":"Tête de noisette","categorie":"Discord"},
    {"mot":"Tarot africain","categorie":"Discord"},
    {"mot":"Ta gueule","categorie":"Discord"},
    {"mot":"C'est rigolo","categorie":"Discord"},
    {"mot":"Wejdene","categorie":"Discord"},
    {"mot":"Papa japonais","categorie":"Discord"},
    {"mot":"Orange","categorie":"Discord"},
    {"mot":"CEO","categorie":"Discord"},
    {"mot":"Salle de pause","categorie":"Discord"},
    {"mot":"1v5","categorie":"Discord"},
    {"mot":"Les gars, le mieux est l'ennemi du bien","categorie":"Discord"}

];